### ISSUE TITLE
External config

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#103]
Would be great to have some kind of external configuration file to read in runtime.

**Comment by giongto35** [comment]
I thought about that but I cannot find clear usecase for it. And when im the one maintaining the deployment, so I can update the config manually by redeploy.
How should I run the project with external config. I don't think external config file should be shared publicly also. :/

**Comment by sergystepanov** [comment]
@giongto35, I was thinking to add some kind of json config file for workers to be able to override a default libretro configuration (all params which are not simple key-values), because right now it is a little bit annoying when you have to change by hands hardcoded Linux core lib paths in config.go files and then recompile the whole app, also it is easy to mess up that way and push your config into the repository.
What I think, maybe, it would be better to define the main configuration object with some default values and if you need to change them then allow to override it by running overworker with a cmd param -c /path/to/my.config.json pointing to a file with your desirable value overrides and keep your config in secret if you will.

**Comment by giongto35** [comment]
It is a valid concern. As we discuss in https://github.com/giongto35/cloud-game/issues/105, we can see the need for external config. 
If your usecase is watching from a local file and update, it can work. However, how to make it is publicly contributed, and update all servers according to that, then it's a problem. I prefer doing the proper way, to solve both use cases. One of my thinking is to have a config repo, and any change will update the config file in all servers.

It's quite tedious and I think i cannot prioritize it now. I think the service is not so big, so build is not so slow. Do you run using `go run cmd/overlord/main.go` and `go run cmd/overworker/main.go` ?

**Comment by sergystepanov** [comment]
You are right, it's not that important, I will add all that I want in my fork. Feel free to close this issue in case you don't need it.

> Do you run using go run cmd/overlord/main.go and go run cmd/overworker/main.go ?
Nope, make build & make run each time (: Will try as you said. (I've been working with Go just for a couple weeks and not yet familiar with its toolchain and syntax)

**Comment by giongto35** [comment]
yes, with `go run cmd/overlord/main.go` and `go run cmd/overworker/main.go`. It will be more comfortable.
And for updating emulator related stuff, rerun `cmd/over/overworker/main.go` is enough :D
