### ISSUE TITLE
Colors seem different

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#110]
Colors seem different from RetroArch, as example:
this:
![image](https://user-images.githubusercontent.com/846874/66743875-9c2f9000-ee83-11e9-9317-e416346fc6de.png)

RetroArch:
![Super Mario Bros-191014-125751](https://user-images.githubusercontent.com/846874/66743614-01cf4c80-ee83-11e9-80ee-543e4c97ea89.png)

**Comment by giongto35** [comment]
This is the color on my machine
![image](https://user-images.githubusercontent.com/7755543/66759607-25ba7e80-eed3-11e9-889f-7a80ebe0bb9f.png)

**Comment by sergystepanov** [comment]
Strange
![image](https://user-images.githubusercontent.com/846874/66761298-618e1d80-eeac-11e9-94fb-217259d0e415.png)

Seems yours is #9593f5 and mine is
![image](https://user-images.githubusercontent.com/846874/66761566-eed17200-eeac-11e9-862b-13e1fed0fe81.png)

It is way off from the original.

**Comment by giongto35** [comment]
:D nice finding, mine and yours are almost similar. Will try to see what is the reason :/

**Comment by giongto35** [comment]
Do you still have the problem with coloring :|

**Comment by sergystepanov** [comment]
Yeah. This' probably NES pallet issue.

**Comment by sergystepanov** [comment]
Sadly, something isn't right with color not only with NES.
Here is PSX, still, blue colors are off (for some reason it shifts colors of pasted print-screen images, but in the original they noticeably off in the blues).
![image](https://user-images.githubusercontent.com/846874/79799619-6b18a680-8363-11ea-967e-ef80cec263b8.png)

**Comment by sergystepanov** [comment]
Um, raw output is ok, it seems.
![test](https://user-images.githubusercontent.com/846874/79860358-35170900-83db-11ea-9df3-4e56a8330cfc.jpeg)

😕 In Chrome it uses color of the monitor but you can force it to use sRGB as example (chrome://flags/#force-color-profile). That explains why it shifts colors of screenshots.
In Firefox colors should be ok even with the different monitor profile, but, sadly, cloudretro's webrtc stuff is not ported there and won't run.

Problem solved. (:
