### ISSUE TITLE
[bug] The server returns a bunch of duplicate addresses for the ping check 

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#114]
It seems the server unnecessary duplicates addresses for latencyCheck. Is this a bug (I haven't looked at this part yet)?
As example, two overworkers on localhost:
![image](https://user-images.githubusercontent.com/846874/67036564-87255c00-f124-11e9-8176-631366723a2f.png)
And here is current cloudretro.io:
![image](https://user-images.githubusercontent.com/846874/67036798-eedba700-f124-11e9-9707-42bf42186728.png)

**Comment by giongto35** [comment]
It working for me. 

![image](https://user-images.githubusercontent.com/7755543/67037936-0df02e00-f151-11e9-8a02-b539fc10922c.png)

I just recently updated something on client-side and it may cause malfunction if the webpage is still cached on your side. Can you clear browser cache (ctr shift R) and check again.

**Comment by sergystepanov** [comment]
Check a list from the server, not the list after check what you're showing on the picture.
This:
![image](https://user-images.githubusercontent.com/846874/67039295-b2f71080-f129-11e9-82b1-741eb954ddd4.png)

**Comment by giongto35** [comment]
ah I see, the duplication is because I run few processes (3-5) game instances per host, so I can maximize the CPU.
And yes, it seems redundant to check the same host multiple times. I think you can optimize that part also :D Thank you for that.

**Comment by giongto35** [comment]
If you see anything on client-side part that doesn't make sense, feel free to modify it also. I'm not good at write frontend (:

**Comment by sergystepanov** [comment]
Ok, I'll fix it on the server. To change a list on a map will be enough, I guess.
