### ISSUE TITLE
URI encode / decode JS bug for the latest room changes

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#120]
When escape function in the [controller.js](https://github.com/giongto35/cloud-game/blob/50343faaad1f95d450e4672fcb8652c9721994e3/web/js/controller.js#L219):
```
copyToClipboard(window.location.href.split('?')[0] + `?id=${escape(roomID)}`)
```
escapes `roomId___gameName` then result link contains escaped characters for `;,/?:@&=+$`, as example: 
```
Legend of Zelda, The - A Link To The Past Four Swords (U) [!] -> 
Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20To%20The%20Past%20Four%20Swords%20(U)%20%5B!%5D
```
but corresponding [parser](https://github.com/giongto35/cloud-game/blob/b7f47f5519661abd68e8353b496ae8a93c4589b2/web/js/ws.js#L309) uses `decodeURI` function, which leaves described above characters escaped, so on the server side it won't find the game by its name and a worker just crashes:
```
I1022 17:06:32.121056   11960 browser.go:88] Received room response from browser:  5e3024468942a6fd___Legend of Zelda%2C The - A Link To The Past Four Swords (U) [!]
I1022 17:06:32.122056   11812 room.go:101] Room 5e3024468942a6fd___Legend of Zelda%2C The - A Link To The Past Four Swords (U) [!] started. GamePath: , GameName:
I1022 17:06:32.122056   11812 nanoarch.go:237] error loading , err 34
```

It can be fixed by using decodeURIComponent function instead.
I've already fixed it in the new frontend, but not sure when I'll be ready to PR, so wanna let you know about this bug.

**Comment by giongto35** [comment]
oh, I'm not aware of this bug. Seems like it happens with this legend of Zelda path due to "," character. Thanks for pointing that out : D. I'm waiting for your PR.
