### ISSUE TITLE
Move away from WebRTC DataChannel, using socket for game input.

### ISSUE THREAD

**Issue by giongto35** [giongto35/cloud-game#126]
WebRTC Datachannel has some bug (when the connection disconnect abnormally)
`ortc ERROR: 2019/10/23 19:24:00 Failed to accept data channel: unexpected packet type: WebRTC  #Binary`
In addition, WebRTC Datachannel seems not be currently supported by some browser.
Because game input payload is small, better use WebSocket for input.

**Comment by sergystepanov** [comment]
@giongto35, and how does its latency compare to UDP-based DataChannels? Does it matter?

**Comment by giongto35** [comment]
WebRTC Data Channel is based on SCTP, you can see the comparison here https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/network/sctp_intro.html
As I understand, SCTP is message-oriented while TCP is byte-oriented, so we gain advantage with SCTP if our message is a big atomic data/ However, our use-case is user-input, which is not big.
At first, I used it because It comes together with the WebRTC toolset. However, I'm seeing it is causing some incompatibility, so I think I need to get rid of it :D

**Comment by sergystepanov** [comment]
I see, thanks for the explanation. I thought DataChannels can use either TCP or UDP for transmission just like peer connections.
