### ISSUE TITLE
WebRTC ice candidate errors

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#127]
If you add ice candidates error handler, i.e.:
```
    pc.onicecandidateerror = (error) => {
        console.error(error);
    }
```
a bunch of messages will be shown in the console later
![image](https://user-images.githubusercontent.com/846874/67501063-48dfed80-f68c-11e9-82b7-59820f37065f.png)

Does anyone have same errors with this handler or is it just an issue with my dev environment?

**Comment by sergystepanov** [comment]
Also, if you start some game right away, before **** allocate request timeout in 30 seconds, it will close the connection on the server for some reason ??? and will exit the game.

![image](https://user-images.githubusercontent.com/846874/67503194-df61de00-f68f-11e9-9f4b-8ed9fc5de427.png)

**Comment by sergystepanov** [comment]
Apparently, Chrome shouldn't even [support](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidateerror#Browser_compatibility) this property (:
I guess, it's too early to use this WebRTC function.

**Comment by giongto35** [comment]
:D, Yes, WebRTC is not in fully stable status. It's interesting technology, help me a lot. However, relying on that also creates some problems with browser compatible which I'm facing :-<
