### ISSUE TITLE
Possible bug with touch high frequency tap

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#128]
Possible bug with the touch input. Seems it can't process fast button tapping for some reason. 
Tested just in the Chrome desktop.

![touchbug](https://user-images.githubusercontent.com/846874/67621543-0f88b880-f819-11e9-9877-bd8e21fa0242.gif)

**Comment by giongto35** [comment]
oh interesting, Are you checking over local or cloudretro

I think frequency tap causes this problem because we poll key state every few ms and detect the change. If the tap is too fast, the key state might seems not changed between two polling.

**Comment by sergystepanov** [comment]
I'm checking on Cloudretro.
At least I see that it sends twice a new state to the server.

Here it is, I added log function when it should send something to the server.
![touchbug2](https://user-images.githubusercontent.com/846874/67624403-c8122480-f838-11e9-9577-fae93d7c7161.gif)

**Comment by giongto35** [comment]
I still think it's some polling event issue, either in frontend or server. The polling for input event from or cannot catch up with the frequency of tap. :-? I'm not sure need further investigation.

When was the last time you can run on Android? :/ How come it no longer work

**Comment by sergystepanov** [comment]
> When was the last time you can run on Android? :/ How come it no longer work
Maybe two weeks ago, my local instance runs just fine (with some bugs in touch control handlers after rewriting :). Sadly, I don't know how to debug Android Chrome and don't have that much spare time for it right now.
