### ISSUE TITLE
Not work on Mac OS. dlopen error.

### ISSUE THREAD

**Issue by indieyourself** [giongto35/cloud-game#133]
error loading assets/emulator/libretro/cores/mgba_libretro.so, err 100

**Comment by giongto35** [comment]
Ah I m aware of this issue but haven't fixed it properly. The core library to use for mac os should not be mgba_libretro.so but it is mgba_libretro.dylib.
The cores are different among the OS. I need to fix the issue by providing correct core to the corresponding OS.
In mean time, you can try running with docker. I think Docker should work.

**Comment by indieyourself** [comment]
It works after i replace the .so with .dylib.
