### ISSUE TITLE
Self-update, Libretro cores downloader / updater

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#135]
I was wondering whether it'd be useful to have libretro core downloader / updater inside overworkers based on sys.GOOS rather than using manual assets and hard coded dynamic lib names (so, dll, ...):

0. Remove all the cores from the repo assets
1. Download static worker binary
2. Either auto-download needed cores during the first run or exec `worker -download-cores`
3. Download cores based on the current system by sys.GOOS -> kinda `http://buildbot.libretro.com/nightly/{OS}/x86_64/latest/`
4. Load cores with the extension based on sys.GOOS
4.5 Possible auto-updater: `worker -update-cores`
5. Profit

**Comment by sergystepanov** [comment]
Or just write a multi-os release builder (on GitHub) which will pack right assets instead...

**Comment by giongto35** [comment]
This is good idea indeed.
I will vote on `worker -download-cores`. Or make it init script will be better (can download some games together)
Regarding to 4. I currently have this patch here: https://github.com/giongto35/cloud-game/pull/136/files . We just try every core till it is able to load, so we don't need to check OS.

**Comment by sergystepanov** [comment]
> Regarding to 4. I currently have this patch here: https://github.com/giongto35/cloud-game/pull/136/files . We just try every core till it is able to load, so we don't need to check OS.

That's an interesting approach (:, well, I can't think of any side effects apart from arguably "bad practice" abuse, so let it be.
