### ISSUE TITLE
Can't press all 4 directions on the circle pad

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#139]
During PSX testing I found that you can't press all 4 directions simultaneously in the circle pad, it allows to press just 3 buttons.
Gonna look into that later.
PSX homebrew test [app](https://www.psx-place.com/resources/psxtest.395/).

![image](https://user-images.githubusercontent.com/846874/69496660-8206ba00-0ee5-11ea-81c0-da509429e94f.png)

**Comment by sergystepanov** [comment]
It appears to be just a limitation of the laptop keyboard.

![image](https://user-images.githubusercontent.com/846874/69498620-d8322800-0efa-11ea-9680-c247fc239d4e.png)

**Comment by giongto35** [comment]
:D
