### ISSUE TITLE
Static compilation

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#157]
While I'm trying to make auto-release builder work, it's not clear whether static builds of workers are achievable in general. Couldn't make it compile without a wall of linker errors. 
Looking at this code, maybe it worked before somehow?
https://github.com/giongto35/cloud-game/blob/8484eca29330c133185da79e99f9745a469ca71a/Makefile#L24-L31

Would be great to have statically linked binaries for releases, rather than lib copies from the system (as I described in the windows part of the readme). 😞

**Comment by giongto35** [comment]
@sadlil  you wrote the build.cross before right? Did you ever successfully build it statically?

**Comment by sergystepanov** [comment]
Statics _seems_ to be working with the simple addition of missing pthreads, math and ogg/opus libs:
```bash
go build -tags netgo -ldflags '-extldflags "-lpthread -lm -logg -lopus -static"' -o bin/overworker_static ./cmd/overworker
```
Also old Ubuntu distros like 16.x don't have /usr/lib/.../pkgconfig/vpx.pc pkgconfig metadata because of outdated vpx lib. Not sure if it matters.
https://github.com/giongto35/cloud-game/blob/8484eca29330c133185da79e99f9745a469ca71a/pkg/encoder/vpx-encoder/encoder.go#L16
Yet it still needs testing.

**Comment by sadlil** [comment]
> @sadlil you wrote the build.cross before right? Did you ever successfully build it statically? I'm curious about that as well. :-s

I haven't been able to build it statically earlier. Had a few problems and didn't able to look towards later.

But the approach suggested by @sergystepanov looks good to me. May be we could give it a try.

**Comment by sergystepanov** [comment]
My conclusion is that static linking not worth it, in our case of the static linking against worker's C libs. While it runs just fine (win/nix), there are some potential problems, especially with glibc, which may cause quite a headache later on reducing all the benefits practically to zero. In my opinion, the current (unreleased) approach of packing the list of dynamically linked libs with the executable (ldd, otool) is way more prevalent and fits the best.
