### ISSUE TITLE
Rotated image on some games (mainly flight simulators) - FBNeo

### ISSUE THREAD

**Issue by jk7gr** [giongto35/cloud-game#158]
Dear all,
I am amazed by your work. I have spend a lot of time to understand and build my server. I understand parameterization of the core is very limited at the moment with dimensions and aspect ration to be provided. However the issue I am facing is that some games run rotated by 90 decrease to maintain a landscape type of ratio.
![image](https://user-images.githubusercontent.com/17036347/78334310-36030a80-7594-11ea-8de4-64c3f922dd0a.png)
Is this something I can configure?
Thank you!

**Comment by sergystepanov** [comment]
Hi @jk7gr! It is always good to hear that more people find a common interest in this project. (:
Speaking about rotated game video, I've never thought about this problem until now. 
At the moment it's not possible to a user rotate the screen (actually, you can turn your monitor or smartphone with your own hands (: ) but manually you can do something like this:

![image](https://user-images.githubusercontent.com/846874/78348792-48d50980-75ab-11ea-93d6-209974752ab5.png)

I think, in order to add this feature we should first discuss the best way of its implementation from a user perspective. To add client-side options?
From the dev perspective, I think, the best and easiest way is to rotate canvas in a browser like on the picture above. Guess, It won't be CPU (or GPU, because right now rendering stuff in browsers is GPU accelerated) demanding, by any stretch.
I will try to look how it's implemented in Retroarch.

**Comment by jk7gr** [comment]
hi @sergystepanov really much appreciate the fast response here. 
I think the existence of a rotate button is fine for the moment. It will allow the run of the content because currently is hard to rotate the TFT panel :) (smartphone I agree the rotation is easier). 
In the long run, if this is somehow tackled behind scenes, it will allow a cleaner GUI.

**Comment by sergystepanov** [comment]
I believe we can make rotation work automatically based on core-provided w/h to aspect ratio mismatch: as example a game on the screenshot has 320/240 [1.(3)] != 240/320 [0.75] then call Libretro core rotation with 90* CCW but I not sure if all the cores rotate portrait games that way.

https://github.com/libretro/RetroArch/blob/1d7cae2ceb6c6dcb00e0b2b43dd49df2d19bda22/libretro-common/include/libretro.h#L489-L494

![image](https://user-images.githubusercontent.com/846874/78365881-62d11500-75c8-11ea-9d80-e2168afbb74e.png)

**Comment by jk7gr** [comment]
dear all,
any news on this?

Thank you!

**Comment by sergystepanov** [comment]
Hey!

Guess, no one started this issue yet (: I'm kinda busy right now.
So, to fix this portrait games you have to use so called TATE mode of the cores. Speaking of FBNeo, there is an [option](https://github.com/libretro/FBNeo/blob/cf5aa816107ca9ce89850a458895303bf60d9668/src/burner/libretro/retro_common.cpp#L94-L105) `fbneo-vertical-mode = enabled` that will rotate portrait games properly (not sure how it'll fit to already set screen size, though).
Now the hard part: at the moment core settings are not implemented in the app (as far as I know), @jk7gr, it'd be great if you could take a look at it and try to implement it? That would be really helpful for us.

**Comment by sergystepanov** [comment]
Alright, finally I got this, how it works (:
Right now my rotation algo is quite ineffective, so I need to read and try some stuff, and probably rewrite some parts of emulator. It's will be done when I'll got time for proper implementation (:

![screencapture-localhost-8000-2020-05-20-21_57_03](https://user-images.githubusercontent.com/846874/82486050-fdd46e80-9ae4-11ea-857d-33e851a993fd.png)

**Comment by giongto35** [comment]
@sergystepanov So you rotate the image programmatically during rendering and the libretro core doesn't have rotate support right now?

**Comment by sergystepanov** [comment]
@giongto35, yeah, that's how ReatroArch and every frontend works, even made it near zero cost already (: I'll make a PR for you to check as always in a couple of days (and fix my amazing Go code (: ).
Essentially, there is an core environment var callback that says how much the image is rotated (0, 90,  180, 270) and we're _just_ derotating it (reading packed image bytes some special way for each rotation).

**Comment by giongto35** [comment]
@sergystepanov I see :'( I think it's reasonable if libRetro doesn't support it. Thank you very much for the investigation.  It's ok if we do it on our frontend :+1:

**Comment by sergystepanov** [comment]
Hey @jk7gr! We've merged a fix for that, if you want you could try it out with your games. Feel free to close the issue or ask any questions as well. (:

**Comment by jk7gr** [comment]
> Hey @jk7gr! We've merged a fix for that, if you want you could try it out with your games. Feel free to close the issue or ask any questions as well. (:

As soon as the docker hub image is updated I will pull this down on my node and will let you know. :) Thank you!!!!

**Comment by jk7gr** [comment]
IT WORKED!!! Good job!
