### ISSUE TITLE
Possible memory leak in the menu

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#163]
There is a strange (small) memory leaking progression. To check.

Tested on cloudretro.io.

![image](https://user-images.githubusercontent.com/846874/79569551-77310980-80c0-11ea-9d6d-6aa6d587bb9c.png)

**Comment by giongto35** [comment]
oh. It's an interesting point. As backend developer, I never thought about front end performance. This leak looks troublesome. I will try checking it : D

**Comment by sergystepanov** [comment]
Every developer (especially, if you expect to be a senior dev) ever so or not so slightly should think about the performance of every part in conjunction with the others and make rough estimation to which extent it contributes to the overall app performance metric. 😛 

Generally speaking, I don't believe that this' a true leak, more like poorly written DOM manipulation code, in any case that looks suspicious.

**Comment by giongto35** [comment]
:( I'm not used to debug these front-end performances, I took a look at it yesterday but no clue :D 
Did you catch this issue when you doing the performance graph? I feel the performance visualization you are working looks so good but feel like you haven't finished. Do you measure the latency of a frame from when it start render when it deliver?

**Comment by sergystepanov** [comment]
Just one look and you've already given up (:
Yes, because of graphs I'm checking new code for leaks and adequate performance, and yes, I have not done yet. Right now I'm toying with canvas stuff.
At the moment there is one metric in the client side stats module and it's your ping-pong latency in the ws.
As for the frame metrics and the server side stats module, can't remember what exactly I wrote there (hope, my local branch is intact) but it is just libretro rendering times in which I interested.
I believe you can extract RTT/RTD times separately from the WebRTC connections on the client side, then just slap it (unsynchronized (: ) onto current server frame time and call it a day. 👍

**Comment by giongto35** [comment]
I see. Actually, I really want to measure the full frame delivery: from libretro rendering time + RTT time but seems like a lot of work to do. What you currently do is one step toward that, at least with canvas we can throw any information we got.
On my side, I'm still trying to figure out how to make cloudretro runs on IOS =.=!

**Comment by sergystepanov** [comment]
If [this](https://stackoverflow.com/a/14838977) is true that JS stores stack frames in the heap then it's unfixable. What a 💩 language. I'm closing this until further notice. (:
