### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by tobimook** [giongto35/cloud-game#164]
Hi I found this project yesterday and it looks amazing. It was really cool to be able to play a PSX game from a browser.
I started with the 2.2.0 release, so there might be some changes in master already.
I am going to get this up and running on my Kubernetes cluster, but the first thing I noticed is that the docker image is quite large. **(1.6 GB)**.
So I used one of my favorite docker tools https://dockersl.im/ and made it more manageable. When I have some time I would like to look more into the docker build process and set up a multi-stage build so it is cleaner from the start.

Here is the command that I used: 
`./docker-slim build --target cloud-game:2.2.0 --entrypoint 'bash -c "coordinator --v=5 & worker --coordinatorhost localhost:8000"' --include-path /cloud-game/ --include-shell`

And the results: 

|REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
| --- | --- | --- | --- | --- |
|cloud-game.slim  | latest | b81ff8b56dc6 | 6 seconds ago | 261MB
|cloud-game | 2.2.0 | 9feaf879f08a | 2 hours ago | 1.63GB
|golang |  1.12 | ffcaee6f7d8b | 2 months ago | 810MB

Once I have the Kubernetes manifest, I will share with here to help someone else get it up and running.

**Comment by giongto35** [comment]
I also have trouble with docker build size, I think it is quite slow indeed. One of the reasons is that I upload Golang vendor into the docker build I think. But it's truly amazing that docker slim can help reduce the size from 1.63GB -> 261MB without any manual manipulation. 
Multi-stage can help some speed up, I would love to have your help on that. :D Thank you very much.

**Comment by sergystepanov** [comment]
Doesn't even run properly on Windows, and who needs it anyway (:

> Multi-stage can help some speed up

Multi-stage build won't help with `docker build` speed (proper context or .dockerignore do help), it helps in shrinking the size of the resulting image. It's even possible to shrink it to ~50Mb or less with [Alpine](https://hub.docker.com/_/alpine?tab=tags) and release build of the app (~30Mb).

I'm looking forward to see proper k8s config wich is interesting. Thanks for help/

**Comment by giongto35** [comment]
@sergystepanov  thank you for correct my understanding on multi-stage docker build :+1: 
I think I'm going to check k8s config as well.

**Comment by tobimook** [comment]
HI guys, 
Yes I am a Linux users, so most of what I use doesn't work in Windows without a VM ;-).
I agree the main reason to use a multi-stage build would be to have a smaller image at the end.
I have finished my first draft of my Kubernetes manifest, but I am having an issue, so I will open a new issue for that. Once I take a look at the Dockerfile, I will update here.

**Comment by sergystepanov** [comment]
Fixed in #190.
