### ISSUE TITLE
Kubernetes Manifest

### ISSUE THREAD

**Issue by tobimook** [giongto35/cloud-game#165]
I have set up my first draft of a Kubernetes manifest to run 1 Coordinator pod and 2 Worker pods. [cloud-game-example.yaml.txt](https://github.com/giongto35/cloud-game/files/4498130/cloud-game-example.yaml.txt)

Just to let you know I am using [k3s](https://www.k3s.io) for my Kubernetes cluster. It uses Traefik as the default Ingress Controller, and I am using NFS for the Persistent Volume to store the game files. So this manifest file is specifically built for that, but can be easily adjusted for other Ingress Controllers or Storageclasses. 

The pods start up, and I am able to get to the web interface from my ingress address, but the list of games is empty. I can verify that the files exist in the running containers in the /cloud-game/assets/games folder. 
I even did a test where I only spun up one container with the coordinator and worker as per the Make file. Not mounting the share in /cloud-game/assets/games and just using the games provided from the repo, that are saved in the image, gives the same result.

Using the same image with Docker on my desktop works as expected. I am using the following commands as I found out I do not need to run the containers as privileged for them to work.

docker run -v /data/cloud-game-2.2.0/assets/games:/cloud-game/assets/games -d --name cloud-game-front -p 8000:8000 -p 9000:9000 cloud-game.slim bash -c "coordinator --v=5" 

docker run -v /data/cloud-game-2.2.0/assets/games:/cloud-game/assets/games -d --name cloud-game-worker1 cloud-game.slim bash -c "worker --coordinatorhost 172.17.0.2:8000" 

docker run -v /data/cloud-game-2.2.0/assets/games:/cloud-game/assets/games -d --name cloud-game-worker2 cloud-game.slim bash -c "worker --coordinatorhost 172.17.0.2:8000"

So looking at the logs for the coordinator in the Kubernetes cluster, I do not see the line:
`I0419 00:43:34.728558       1 handlers.go:133] A user connected to coordinator  /ws?room_id=&zone=`  or anything past that.
The last line I have is:
`Is public: false zone: ` which seems like it is missing something.

So I have taken a quick look at the existing issues, and nothing seems to match. I will need to dig into the actual code to find out what is going on, but hopefully I can get some hints. :-)

For reference, here are the log files.
[Kubernetes-worker2.log](https://github.com/giongto35/cloud-game/files/4498154/Kubernetes-worker2.log)
[Kubernetes-worker1.log](https://github.com/giongto35/cloud-game/files/4498155/Kubernetes-worker1.log)
[Kubernetes-coordinator.log](https://github.com/giongto35/cloud-game/files/4498164/Kubernetes-coordinator.log)
[Local-worker2.log](https://github.com/giongto35/cloud-game/files/4498157/Local-worker2.log)
[Local-worker1.log](https://github.com/giongto35/cloud-game/files/4498158/Local-worker1.log)
[Local-coordinator.log](https://github.com/giongto35/cloud-game/files/4498159/Local-coordinator.log)

Thanks and have a good one.

**Comment by giongto35** [comment]
Seems like the peer connection cannot set up with Kubernetes environment. Can you open all ports in kubernetes container to ease the p2p connection first to check if it work?

**Comment by tobimook** [comment]
Hi @giongto35, sorry I am not the service management is a 1 to 1 ratio, so I would need to know what ports are being used by the coordinator to communicate with the browser client. I can then set that up.

I will also try my local docker setup, but try to access port 8000 from another computer.

**Comment by tobimook** [comment]
I had some time to do some more tests, and I am getting the proper response from my Pixel 3 over Wi-Fi, but not from any of my desktops.
I updated the ingress to include an address using xip.io, so I didn't have to mess around with hosts files or setting up a live DNS record for my phone.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-game
spec:
  rules:
  - host: 192.168.1.22.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud-game-coordinator
          servicePort: 8000
  - host: games.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud-game-coordinator
          servicePort: 8000

So right now it looks like my [pi-hole](https://pi-hole.net), is causing an issue with resolving xip.io addresses on any of my computers at home (Linux and Windows). So I might have to set up a live DNS record that can resolve properly to fix this issue.

Otherwise, the game list shows up on my phone using the built-in games from the repo and the list of games from my NFS mount. So that is working. :-)

**Comment by giongto35** [comment]
Thank you for a very detailed analysis. Seems like you are making a good progress when it's working with your phone (y). 
Peer Connection is set up by random port, so we cannot know the specific one.
When I run docker for production, I run docker in host mode. Which is open all port to container
`docker run --privileged -d --network=host -v /cloud-game/games:/cloud-game/assets/games`.
I think Kubernetes should have the way to do the same :-?
I don't know much about Kubernetes set up (need to read about it first), so I think I'm not able to help now.

**Comment by tobimook** [comment]
By design, you can not access all ports of a container running in Kubernetes. There is security in place to make sure that only ports that are necessary are shared outside the cluster or even between pods of containers. Is there a range of ports that would be used for the end user connections? Such as 10000-20000 ? I Should see that in the code as well, but I haven't had time to dig in yet.

**Comment by giongto35** [comment]
Hi @tobimook ,

Thank you so much indeed, you made a very good foundation. I spent last weekend to read some documents about Kubernetes and K3s to help you. Currently, I can configure my staging environment based on your yaml file. I made some progress but may take more time to have it fully works. Can you commit your yaml file to `kube/kubeconfig.yaml` and I will take over your work from now. I will let you know when it is completed.

BTW I have a question why you set this flag "imagePullPolicy: Never". Is it kind of good practice? what is the problem of pulling image.

**Comment by giongto35** [comment]
https://github.com/kubernetes/kubernetes/issues/23864 seeing the same problem here. Maybe it's not achievable :-
