### ISSUE TITLE
Makefile $PWD/games Docker install error

### ISSUE THREAD

**Issue by baxpace** [giongto35/cloud-game#166]
I changed the $PWD/games value to $(pwd)/games instead of using an absolute path and the docker container is installed correctly: 

`docker run --privileged -v $(pwd)/games:/cloud-game/games -d --name cloud-game-local -p 8000:8000 -p 9000:9000 cloud-game-local bash -c "coordinator --v=5 & worker --coordinatorhost localhost:8000"
`

Amazing tool!  Having a blast trying everything out!

**Comment by giongto35** [comment]
oh I wondered how long it have failed :(  Thank you so much for fixing it. 
I verified, can you make a PR for that @baxpace

**Comment by giongto35** [comment]
@baxpace seems like it is quite serious issue for newcomers. I will apply the change directly. 
If later you find any issue and it can be a quick fix, please file it as Pull Request, so we can make action faster :p

**Comment by baxpace** [comment]
Will do!
