### ISSUE TITLE
Application settings UI

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#171]
Add settings UI.

To think about a generic approach with auto-building based on metadata (types)?

TBD.

**Comment by giongto35** [comment]
What will be configurable in the setting?

**Comment by sergystepanov** [comment]
Everything that you need. Any param of the settings module which stores params from different modules of the app. Maybe, it'll be a generic auto-builder with manual overrides, or just a hardcoded interface.
Personally, I'll try to add keyboard config if it's possible without much pain.

**Comment by giongto35** [comment]
: D oh sound good. I'm curious how is the configuration stored? Is it on local storage and user will have same setting every time he open the browser?

**Comment by sergystepanov** [comment]
You can take a look how it's implemented right [now](https://github.com/giongto35/cloud-game/pull/173/files#diff-be9a724c48b78b87a5ecc311312aeefc).
Basically, I added the provider dependency as an abstract layer for a persistence storage. One of which is LocalStorage, another one is the void -- a fallback-to-defaults provider (or null-object). If you ever need a server-side persistence, well, it'll be quite easy to roll it out as a new provider (or composition of providers, or decoration).
Regarding some kind of cross-device storage, there is a basic import/export functionality which is still needed a thorough planning. 😟

**Comment by giongto35** [comment]
I see, so storage can be different among different devices right? What is the best practice to support cross-device storage?
If we have setting in server-side, we need to support setting based on user right? it is a lot of work, so can go forward with local storage for now.
