### ISSUE TITLE
WebRTC won't start in Firefox (Windows 10)

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#176]
Is it just me or the app still isn't working in Firefox? It says in the browser console: `ICE failed, your TURN server appears to be broken, see about:webrtc for more details`
Is this suppose to work now without additional configuration?

FF: 75.0 Windows

<pre>
I0427 23:52:40.728461    8564 handlers.go:161] Coordinator: A user is connecting...
I0427 23:52:40.729464    8564 browser.go:35] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Generated worker ID
I0427 23:52:40.731461    8564 browser.go:30] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Get Room  Zone  From URL /ws?room_id=&zone=
I0427 23:52:40.731461    8564 browser.go:35] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Send sync[http://localhost:9000/echo]http://localhost:9000/echo
I0427 23:52:40.755463    4088 worker.go:75] &{0xc000068aa0 0xc000574000 {} 0x4a3240 false false false false 0xc0000608c0 {0xc0000d0700 map[] false false} map[Access-Control-Allow-Origin:[*]] true 0 -1 0 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc0004a0070 0} echo
I0427 23:52:40.789460    8564 browser.go:35] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Latency mapmap[0xc000180480:41]
I0427 23:52:40.826462    8564 browser.go:30] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Received initwebrtc request -> relay to worker: 6a1a220d-5c62-4f5b-a8b4-eea0c246d828
I0427 23:52:40.828462    4088 coordinator.go:57] Received a request to createOffer from browser via coordinator
I0427 23:52:40.828462    4088 webrtc.go:111] === StartClient ===
I0427 23:52:40.933462    4088 webrtc.go:131] Add video track
I0427 23:52:40.933462    4088 webrtc.go:142] Add audio track
I0427 23:52:40.934460    4088 webrtc.go:200] Created Offer
I0427 23:52:40.934460    4088 webrtc.go:181] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.234.33 63191
typ host
I0427 23:52:40.935466    4088 coordinator.go:89] Start peerconnection 5a74aa09-9b6d-4c7c-9bff-941b63c24e05
I0427 23:52:40.935466    8564 worker.go:41] Worker 6a1a220d-5c62-4f5b-a8b4-eea0c246d828] Received IceCandidate from worker -> relay to browser
I0427 23:52:40.935466    4088 webrtc.go:181] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.1.121 63192 typ host
I0427 23:52:40.935466    8564 browser.go:35] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Received SDP from worker -> sending back to browser
I0427 23:52:40.936462    4088 webrtc.go:181] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.56.1 63193 typ host
I0427 23:52:40.936462    8564 worker.go:41] Worker 6a1a220d-5c62-4f5b-a8b4-eea0c246d828] Received IceCandidate from worker -> relay to browser
I0427 23:52:40.936462    4088 webrtc.go:181] OnIceCandidate: candidate:foundation 1 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194
I0427 23:52:40.937463    8564 worker.go:41] Worker 6a1a220d-5c62-4f5b-a8b4-eea0c246d828] Received IceCandidate from worker -> relay to browser
I0427 23:52:40.938462    8564 worker.go:41] Worker 6a1a220d-5c62-4f5b-a8b4-eea0c246d828] Received IceCandidate from worker -> relay to browser
I0427 23:52:40.939464    8564 worker.go:41] Worker 6a1a220d-5c62-4f5b-a8b4-eea0c246d828] Received IceCandidate from worker -> relay to browser
I0427 23:52:40.975462    8564 browser.go:35] Browser 5a74aa09-9b6d-4c7c-9bff-941b63c24e05] Received browser answered SDP -> relay to worker
I0427 23:52:40.982463    4088 coordinator.go:106] Received answer SDP from browser
I0427 23:52:40.984465    4088 webrtc.go:233] Set Remote Description
I0427 23:52:40.985462    4088 webrtc.go:165] ICE Connection State has changed: checking
I0427 23:52:50.985852    4088 webrtc.go:165] ICE Connection State has changed: failed
</pre>

<details>
<summary>FF log</summary>

<pre>
(registry/INFO) insert 'ice' (registry) succeeded: ice
(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref
(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type
(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64
(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e
(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e
(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05
(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63
(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d
(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d
(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00
(registry/INFO) insert 'stun' (registry) succeeded: stun
(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client
(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7
(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000
(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp
(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0
(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10
(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \000
(generic/ERR) UDP socket error:Internal error at Z:/task_1585933993/build/src/dom/network/UDPSocketParent.cpp:268 this=00000270B834C000
(ice/ERR) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): failed to find default addresses
(generic/ERR) UDP socket error:Internal error at Z:/task_1585933993/build/src/dom/network/UDPSocketParent.cpp:268 this=00000270B834E000
(ice/ERR) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): failed to find default addresses
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_0 - 01f5805e:45385da4adf81024c3fcd93ae27bfec0
(ice/INFO) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) no such component for candidate candidate:foundation 2 udp 2130706431 192.168.234.33 63191 typ host generation 0
(ice/INFO) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) no such component for candidate candidate:foundation 2 udp 2130706431 192.168.1.121 63192 typ host generation 0
(ice/INFO) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) no such component for candidate candidate:foundation 2 udp 2130706431 192.168.56.1 63193 typ host generation 0
(ice/INFO) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) no such component for candidate candidate:foundation 2 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
(generic/ERR) UDP socket error:Internal error at Z:/task_1585933993/build/src/dom/network/UDPSocketParent.cpp:268 this=00000270B834E000
(ice/ERR) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): failed to find default addresses
(generic/ERR) UDP socket error:Internal error at Z:/task_1585933993/build/src/dom/network/UDPSocketParent.cpp:268 this=00000270B8350C00
(ice/ERR) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): failed to find default addresses
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_0 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_3 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_4 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_0 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_3 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_4 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_0 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_3 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_4 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_0 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_3 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
(ice/WARNING) ICE(PC:1588020760802000 (id=10737418241 url=http://localhost:8000/)): peer (PC:1588020760802000 (id=10737418241 url=http://localhost:8000/):default) has no stream matching stream PC:1588020760802000 (id=10737418241 url=http://localhost:8000/) transport-id=transport_4 - 9d8a2bf7:e0e1a833f36d9e0fe0012984ec6dd249
+++++++ END ++++++++
</pre>
</details>
<details>
<summary>SDP</summary>

<pre>
SDP
Local SDP (Offer)
v=0
o=mozilla...THIS_IS_SDPARTA-75.0 2487803064638739471 1 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 91:36:AF:63:EF:86:2D:1F:DB:C1:7E:E4:7A:C9:16:A4:AD:0F:D0:A5:4B:F1:08:65:36:3B:32:8A:19:B8:FD:58
a=group:BUNDLE 0 1 2 3 4
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 96 98 126 97
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:96 max-fs=12288;max-fr=60
a=fmtp:98 max-fs=12288;max-fr=60
a=ice-pwd:e0e1a833f36d9e0fe0012984ec6dd249
a=ice-ufrag:9d8a2bf7
a=mid:0
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 goog-remb
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:96 VP8/90000
a=rtpmap:98 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:3368318818 cname:{569eb366-f0a8-49c2-ae9b-5093168654e2}
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8 9 101
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:e0e1a833f36d9e0fe0012984ec6dd249
a=ice-ufrag:9d8a2bf7
a=mid:1
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000/1
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:2076023069 cname:{569eb366-f0a8-49c2-ae9b-5093168654e2}
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:e0e1a833f36d9e0fe0012984ec6dd249
a=ice-ufrag:9d8a2bf7
a=mid:2
a=sctpmap:5000 webrtc-datachannel 256
a=setup:actpass
a=max-message-size:1073741823
m=video 0 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 0.0.0.0
a=bundle-only
a=sendrecv
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:e0e1a833f36d9e0fe0012984ec6dd249
a=ice-ufrag:9d8a2bf7
a=mid:3
a=msid:- {db5d210c-451c-4174-bbae-da94bd1c1626}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:1210881150 cname:{569eb366-f0a8-49c2-ae9b-5093168654e2}
m=audio 0 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=bundle-only
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:e0e1a833f36d9e0fe0012984ec6dd249
a=ice-ufrag:9d8a2bf7
a=mid:4
a=msid:- {e0e11a51-926c-4e84-803f-8a1f46be31b7}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:1103474835 cname:{569eb366-f0a8-49c2-ae9b-5093168654e2}

Remote SDP (Answer)
v=0
o=- 821757822 1588020760 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 56:52:08:AD:85:F0:F2:04:BE:05:17:F8:9A:75:B5:65:31:1A:C1:B2:68:90:23:5F:AA:87:05:2F:DA:F9:3D:09
a=group:BUNDLE 0 1 2
m=video 9 UDP/TLS/RTP/SAVPF 96 98 102
c=IN IP4 0.0.0.0
a=candidate:foundation 1 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 1 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=candidate:foundation 2 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=candidate:foundation 1 udp 2130706431 192.168.234.33 63191 typ host
a=candidate:foundation 1 udp 2130706431 192.168.1.121 63192 typ host
a=candidate:foundation 1 udp 2130706431 192.168.56.1 63193 typ host
a=candidate:foundation 1 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194
a=sendrecv
a=end-of-candidates
a=fmtp:102 profile-level-id=42001f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:vRStOTenOAAheuTypEDtRIewUaZaLmkQ
a=ice-ufrag:vRStOTenOAAheuTy
a=mid:0
a=msid:game-video video
a=rtcp-mux
a=rtpmap:96 VP8/90000
a=rtpmap:98 VP9/90000
a=rtpmap:102 H264/90000
a=setup:actpass
a=ssrc:271976615 cname:game-video
a=ssrc:271976615 msid:game-video video
a=ssrc:271976615 mslabel:game-video
a=ssrc:271976615 label:video
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8 9
c=IN IP4 0.0.0.0
a=candidate:foundation 1 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 1 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=candidate:foundation 2 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=sendrecv
a=end-of-candidates
a=fmtp:111 maxplaybackrate=0;stereo=0;useinbandfec=1
a=ice-pwd:vRStOTenOAAheuTypEDtRIewUaZaLmkQ
a=ice-ufrag:vRStOTenOAAheuTy
a=mid:1
a=msid:game-audio audio
a=rtcp-mux
a=rtpmap:111 OPUS/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000/1
a=setup:actpass
a=ssrc:1333919895 cname:game-audio
a=ssrc:1333919895 msid:game-audio audio
a=ssrc:1333919895 mslabel:game-audio
a=ssrc:1333919895 label:audio
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=candidate:foundation 1 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.234.33 63191 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.121 63192 typ host generation 0
a=candidate:foundation 1 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.56.1 63193 typ host generation 0
a=candidate:foundation 1 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=candidate:foundation 2 udp 1694498815 95.30.103.36 63194 typ srflx raddr 0.0.0.0 rport 63194 generation 0
a=sendrecv
a=end-of-candidates
a=ice-pwd:vRStOTenOAAheuTypEDtRIewUaZaLmkQ
a=ice-ufrag:vRStOTenOAAheuTy
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
a=setup:actpass
</pre>
</details>

**Comment by giongto35** [comment]
It works on my side. Can you try with your chrome again.
![image](https://user-images.githubusercontent.com/7755543/80444007-21235800-8943-11ea-8b44-890fbfd5c76e.png)

**Comment by trichimtrich** [comment]
seems you run the game server on local.
in that case, config of the turn address is still sent with your public ip address
https://github.com/giongto35/cloud-game/blob/974ff64033300dc0b6739047899d049092a605b8/pkg/config/config.go#L20
https://github.com/giongto35/cloud-game/blob/5dcf4ac95f9e2d53edbcd88104d6b1c48121b4f1/pkg/coordinator/handlers.go#L138
@giongto35 do we run a turn server in same host with game server all the time, this code seems fragile, an depends on that fact.

**Comment by giongto35** [comment]
@trichimtrich yes it runs all the time on production. Actually, with current host configuration, I don't think we need that setup.

**Comment by sergystepanov** [comment]
> seems you run the game server on local.
> in that case, config of the turn address is still sent with your public ip address
> https://github.com/giongto35/cloud-game/blob/974ff64033300dc0b6739047899d049092a605b8/pkg/config/config.go#L20
> 

Yes, I'm running it from the makefile on localhost.
Yes, cloudretro.io is working in FF.
But local run in Chrome is working, in Firefox (any existing version) it is not working. What's the difference between them?
So, I'm not sure if I understand you correctly, but it receives the same config as Chrome: public stun, stun and turn from localhost.
This [thing](https://test.webrtc.org/?turnURI=turn%3Alocalhost%3A3478&turnUsername=root&turnCredential=root) says that local turn is connectable in FF.

**Comment by trichimtrich** [comment]
please share your setup (infra + run cmd), i will try to reproduce this.
also did the previous version (before rtc fix) work in your FF local?

**Comment by giongto35** [comment]
@trichimtrich FF never work even before the rtc fix. I think @sergystepanov is just curious about why Firefox worked on prod now but still fail on local

**Comment by trichimtrich** [comment]
oh ic, just curious if it has the same error message.
the rtc api suppose to be no diffierent between browsers, any connectivity problem might be from the infra setup (docker, firewall, ...)

**Comment by sergystepanov** [comment]
Old version has the same message.
Firefox works on my second OS Ubuntu (bare metal), same laptop. In W10 it does not. Strange. Would be great if someone could try to run it in Windows 10.
I will try to run it on a different PC.
This is the run script: `./bin/coordinator --v=5 & ./bin/worker --coordinatorhost localhost:8000`
I'm not using any kind of virtualization and firewalls (except hardware-based one on the router)
and I'm running it on the main OS with fresh installed FF.
I'd just like to know why Chrome is working and FF won't. This' kinda ridiculous.

**Comment by sergystepanov** [comment]
And I think, this stuff should be removed from both the client and the server:
https://github.com/giongto35/cloud-game/blob/974ff64033300dc0b6739047899d049092a605b8/pkg/config/config.go#L8

**Comment by sergystepanov** [comment]
And here is new build of the app: https://github.com/sergystepanov/cloud-game/releases/tag/v2.4.8

**Comment by sergystepanov** [comment]
Um... tried another PC and it's working.
But:
in FF I have distorted audio [lol.zip](https://github.com/giongto35/cloud-game/files/4557970/lol.zip)
Chrome is OK. Is it works fine for you?

path handling for external assets in the app is really inconvenient for use

**Comment by sergystepanov** [comment]
Actually, there is no point in keeping this issue open, I guess, it's specific for me only (as always).

**Comment by trichimtrich** [comment]
I installed and tested on windows 10.
Both cloudgame, and testrtc failed with 'http://localhost' origin on Firefox.
I tried to redirect the localhost (127.0.0.1) to some thing else like 'http://abc.com', it works well.
Seems that is the problem only happened with Firefox, not sure why.

Can you try that on your side (change hosts file).
Also dont forget to change the `wss` scheme in `socket.js` to `ws`

**Comment by sergystepanov** [comment]
Oh, wow, it's working now, somehow.

**Comment by sergystepanov** [comment]
And the audio is distorted only on "Sushi the cat". Could you check this too?

**Comment by trichimtrich** [comment]
yes sure,
hmm i also notice if use local ip instead of 'localhost', it also works.
`127.0.0.1:8000` or `192.168.1.xxx:8000`

**Comment by sergystepanov** [comment]
Yeah. Strange. And still on another PC it's opening from localhost.
Anyway, for my purposes it's more than enough right now, thanks a bunch!

**Comment by trichimtrich** [comment]
close this and fork audio distortion bug into another issue for visibility.
