### ISSUE TITLE
Gamelist as hard dependency

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#178]
It seems that both coordinator and worker are dependent on `util/gamelist/games.go` or, to be more precise, on the `assets/games` folder. Was it a temporary ad hoc solution, or had it been justified as an appropriate architecture solution for the Cloud?

**Comment by giongto35** [comment]
I use the same deployment flow for both coordinator and worker. May I know what is your concern of this approach?

**Comment by sergystepanov** [comment]
No concerns, just interesting to learn an alternative point of view. As a person who was taught to abide by the list of SE sacred principles, one of which is decoupling, it is not always obvious what motivation was behind someone's decision, especially if you're a not that well versed in some programming field within, like me in the cloud. (:

**Comment by giongto35** [comment]
@sergystepanov err, actually I don't get your question. Do you mean Coordinator and Worker is sharing the same module and become coupled?

**Comment by sergystepanov** [comment]
My question was literal: what is it -- a hack or final solution, and why. And if now I understand correctly, by design one coordinator can't share workers from another machine, so there is one-coordinator-to-many workers on the same machine, then it doesn't matter, honestly.
If not:
One source of truth is a little bit different problem: i.e. they can go out of sync as two independent processes.
I meant that they both depend on that folder through that gamelist module and I'm have to specify exact same folder for both of them.
These kind of questions are better to be discussed in chat, I think.
