### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/giongto35/cloud-game/v2

### ISSUE THREAD

**Issue by KateGo520** [giongto35/cloud-game#181]
## Background
The github.com/giongto35/cloud-game uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release stream version is **v2**. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation and enforced since the most recent versions of Go. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Using `go get` (under go1.13 and go1.14) does not work for github.com/giongto35/cloud-game@v2+.
I consider this a pretty **high severity** issue since not doing so **prevents any other Go project also using Go Modules** to properly require ` giongto35/cloud-game ` on versions v2+ as a dependency, resulting in errors like:
```
invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

SO anyone using Go modules will not be able to easily use any newer version of giongto35/cloud-game

## Steps to Reproduce
1. Under a project making use of Go modules, run `go get` targeting any version >= v2.0.0 of the giongto35/cloud-game:

```
$ go get github.com/giongto35/cloud-game@v2.2.0
go: finding github.com/giongto35/cloud-game v2.2.0
go: finding github.com/giongto35/cloud-game v2.2.0
go get github.com/giongto35/cloud-game@v2.2.0: github.com/giongto35/cloud-game@v2.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

### Kill the go.mod files.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules). Importing specific versions would work, but they'd receive the `+incompatible` prefix and would need to be manually upgraded.

Probably best option short-term -- better to not use Go modules than use it incorrectly.

Also, best option for older branches/versions that aren't maintained.

### Make breaking changes
Patch the `go.mod` file to declare the `module` as `github.com/giongto35/cloud-game/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). AND adjust all internal imports.

This would probably only be acceptable on the v2 line, since it'd break any consumers.
Two methods can be use:
* a new branch in the same repo
* use the folders structure on mainline branch (see Major Subdirectory structure on the [Modules page](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)).

Then development would take place in the new branch/repository, with the existing only updated with tags and/or with new things to forward.

### Major version bump / repository change
Leave `v2` as a dead version and bump to v3 with the path changes.

### References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by KateGo520** [comment]
@sergystepanov  @giongto35

**Comment by giongto35** [comment]
Oh . Thank you very much. I was not aware of this Go Mod Issue. I will fix it ASAP. Thank you so much for the proposed solution as well : D

**Comment by KateGo520** [comment]
Thank you for your contribution ! ^_^

**Comment by sergystepanov** [comment]
There will be a lot of these spam bots in the future.
I wonder why they are doing this (:? Do they hope to hot fix their (golang) garbage language design until not everyone get used to use it as it's convenient for people now?
Also I wonder, why they did this before Go2 release.
Anyway, my opinion that we **might** do this: add /v3 postfix when we are ready for v3 release in the future but this' not critical at all.

**Comment by sergystepanov** [comment]
And, @KateGo520, could you elaborate a bit more on your motivation behind these carpet sendings? If you're not a bot ofc. (: (in other case I must to fill an abuse report to Github (: )

**Comment by KateGo520** [comment]
I am a Ph.D. student and my research topic is developing an effective technique to help open-source developers manage their Golang dependencies. I just provided the detection results of my detection tool and try to find a better way to help Go projects to adapt to module management mechanism. This is a non-trivial task. Guaranteeing the quality of our open-source community is our common goal. Thank for your support and understanding.
 
 
Best regards,
Kate

**Comment by sergystepanov** [comment]
Right, thank you for clarifying. I won't bother you with further discussion, it'll be better to leave it as is for the sake of the research. (:
Thank you for your contribution and wish you luck with Ph.D!
