### ISSUE TITLE
windows build fail. pkg-config return error.

### ISSUE THREAD

**Issue by ctinkong** [giongto35/cloud-game#184]
Hi, I build worker on win10 by msys64. and fail. error log like this:
```
# pkg-config --cflags  -- vpx
pkg-config: exit status 3221225595
# pkg-config --cflags  -- opus opus opus opusfile opus opusfile
pkg-config: exit status 3221225595
```
I have install libvpx, libopus, pkg-config, just like:
```
pacman -Sy --noconfirm --needed git make mingw-w64-x86_64-{gcc,pkg-config,dlfcn,libvpx,opusfile}
```
and successfully.

i don't know what happended. thanks.

**Comment by sergystepanov** [comment]
Hi @ctinkong, 

This error code means that you're trying to build 32bit libs with 64bit linker/compiler.
What version of Go are you using? Is it x64?
Could you print the output from the Mingw64 console of this:
```
pkg-config --cflags -- vpx
```
It should look like this: `-IC:/msys64/mingw64/include`

**Comment by ctinkong** [comment]
thanks @sergystepanov 
I have found the problem. before i install MSYS2, i install pkg-config with windows installation package and set the environment variable Path, when i build the worker, it use the pkg-config, which install is not by MSYS2.

but now happen new problem like this:
`$ go build -o bin/worker ./cmd/worker
# github.com/giongto35/cloud-game/cmd/worker
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: 找不到 -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: 找不到 -lmingw32
collect2: error：ld return 1`

i found libmingwex.a in the path:
`C:\msys64\mingw64\x86_64-w64-mingw32\lib`

did i need to indicate path? thanks.

**Comment by sergystepanov** [comment]
Seems it can't find mingw environment or your path variable is garbaged with previous installs.
Are you running this inside mingw64 terminal?

![image](https://user-images.githubusercontent.com/846874/82415536-570ab680-9a81-11ea-94a3-d089e919593d.png)

Could you run this:

> If this won't help, try to run go build inside mingw64 console with output redirect to some file (as my example d:/out.txt):
> ```
> go build -x -a -tags netgo -ldflags '-w' -o bin/worker ./cmd/worker 2>> /d/out.txt
> ```
> And attach the file here.

**Comment by ctinkong** [comment]
Can't find mingw environment, it seems that i use ConEmu to run MSYS2. Now i build it in MSYS2 and the problem has been fixed.
But another question comes
[out.txt](https://github.com/giongto35/cloud-game/files/4655379/out.txt)
 out:
···
$  go build -o bin/worker ./cmd/worker
# github.com/giongto35/cloud-game/cmd/worker
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\TinKong\AppData\Local\Temp\go-link-857344103\000011.o: in function `die':
/e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/vpx-encoder/tools_common.c:56: undefined reference to `__getreent'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/vpx-encoder/tools_common.c:56: undefined reference to `__getree
nt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\TinKong\AppData\Local\Temp\go-link-857344103\000011.o: in function `fatal':
/e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/vpx-encoder/tools_common.c:61: undefined reference to `__getreent'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/vpx-encoder/tools_common.c:61: undefined reference to `__getree
nt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/vpx-encoder/tools_common.c:61: undefined reference to `__getree
nt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\TinKong\AppData\Local\Temp\go-link-857344103\000011.o:/e/ispeed/dev/go/cloud-pc/src/github.com/giongto35/cloud-game/pkg/encoder/
vpx-encoder/tools_common.c:64: more undefined references to `__getreent' follow
collect2.exe: error: ld returned 1 exit status
···

The attach file is the result by:
```
go build -x -a -tags netgo -ldflags '-w' -o bin/worker ./cmd/worker 2>> /d/out.txt
```

**Comment by sergystepanov** [comment]
It shows that the build is successful (: You can even try to run that output file.
And if you run worker in Mingw64 shell this command it shows the same error?
```
go build -x -o bin/worker ./cmd/worker && ./bin/worker
```

**Comment by ctinkong** [comment]
I install MSYS2 again.The command:
```
go build -o bin/worker ./cmd/worker
```
still not work.
 But second command:
```
go build -x -a -tags netgo -ldflags '-w' -o bin/worker ./cmd/worker 2>> ./out.txt
```
working, and it successfully. Thank you.

**Comment by sergystepanov** [comment]
Sure, glad to help.

This flag just do this:
> -a
> force rebuilding of packages that are already up-to-date.
which is strange. You should probably try to delete any cache of Go and cleanly reinstall x64 version of it. And if possible (if you're not working with it) remove any traces of Cygwin or any other non-MSYS2 posix environments from the system.
