### ISSUE TITLE
How setup multitap in nestopia core?

### ISSUE THREAD

**Issue by Lightbass** [giongto35/cloud-game#192]
How setup multitap in nestopia core?
4 players not working without this feature

Maybe 4 players not working in any game and any core

**Comment by sergystepanov** [comment]
As far as I know Nestopia should have NstDatabase.xml in core's system folder.
Technically, 4p input should work, at least until Libretro core input callback.

**Comment by giongto35** [comment]
sorry @Lightbass , I missed this one.

I think I already integrated nestopia core.
I tested with 4 players in some games and it works. Can you tell me which game you tried.

**Comment by Lightbass** [comment]
R.C. Pro-Am 2 (U).nes

@giongto35 In this game.

**Comment by sergystepanov** [comment]
Can't find both [USA](https://nesdir.github.io/9EDD2159_USA.html) and [EU](https://nesdir.github.io/308DA987_Scandinavia.html) versions with proper CRCs. I think, only these two are in the [NstDatabase](https://github.com/0ldsk00l/nestopia/blob/master/NstDatabase.xml) packed with core.
```
    <game>
        <peripherals>
            <device type="fourplayer" />
        </peripherals>
        <cartridge system="NES-NTSC" dump="ok" crc="9EDD2159" sha1="FA189FC0F9277D5765E5DE19274AFBD28660F076">
            <board type="NES-AOROM" mapper="7">
                <prg size="256k" />
                <vram size="8k" />
            </board>
        </cartridge>
    </game>
```
Does a custom NstDatabase.xml will work with the app? Maybe try to add own ROM record with 4 player option into this file if it can be read by Nestopia.

**Comment by sergystepanov** [comment]
Actually, it calculates checksums without ROM header, so any USA ROM should be OK.
So, file isn't issue..

![image](https://user-images.githubusercontent.com/846874/85025706-682e0c80-b180-11ea-864f-59ddee8b1b39.png)

**Comment by sergystepanov** [comment]
So, I tested 4p mode in some [NES multitap games](https://en.wikipedia.org/wiki/NES_Four_Score#Games) including RCPro but none of them worked despite the fact that input is properly forwarded into all 4 ports in the core.

As it stated on the page of Nestopia Libretro [fork](https://docs.libretro.com/library/nestopia_ue/):

> Multitap support
> The Nestopia UE core uses the NstDatabase.xml database file to detect which games have multitap support.

I assume it should automatically enable multitap controller for such games from the file. But it seems that the core not doing it.
Games from the db are being searched by their crc + sha1 hashes and I can confirm that even proper ROMs still won't work with more than 2 players, so it's not ROM hashing issue.
In the latest nestopia core they integrated database file into the core, I can be wrong, but now it's not possible to change it without core recompile and it won't read .xml anymore.

There is a note for core options:
> 4 Player Adapter [nestopia_select_adapter] (auto|ntsc|famicom)
>
> Manually select a 4 Player Adapter if needed. Some games will not recognize the adapter correctly through the NstDatabase.xml database, this option should help fix that.

Some time ago I implemented core options change for testing purposes but even if we add it into the master branch I'm not sure whether it'll be a good thing to let users override core options on core-to-core basis and it's actually hard to implement.
Maybe, leave it as a plan B. (:

**Comment by Lightbass** [comment]
I am compile nestopia core with default NTSC multitap, but it not not working i checked this compiled core on Retroarch and it worked. I think the problem is not only in multitap mode, but has another problem. In any case, I just wanted to try. But it not interesting for me now. I just tell you about this problem. This project pretty cool,  but no one playing oldschool games with me, in online too)
Thanks for answer.

**Comment by sergystepanov** [comment]
It is multitap, I just checked and it's working with the manual option.

I completely forgot that with recently merged N64 feature, so it's possible to use core configs.
You can try to create some cfg file, as example in the dir: `assets\emulator\libretro\cores\nestopia_libretro.cfg` with the line:
`nestopia_select_adapter=ntsc`

and all the possible values:
```
#nestopia_blargg_ntsc_filter=Blargg NTSC Filter; disabled|composite|svideo|rgb|monochrome
#nestopia_palette=Palette; cxa2025as|consumer|canonical|alternative|rgb|pal|composite-direct-fbx|pvm-style-d93-fbx|ntsc-hardware-fbx|nes-classic-fbx-fs|raw|custom
#nestopia_nospritelimit=Remove Sprite Limit; disabled|enabled
#nestopia_overclock=CPU Speed (Overclock); 1x|2x
#nestopia_select_adapter=4 Player Adapter; auto|ntsc|famicom
nestopia_select_adapter=ntsc
#nestopia_fds_auto_insert=FDS Auto Instert; enabled|disabled
#nestopia_overscan_v=Mask Overscan (Vertical); enabled|disabled
#nestopia_overscan_h=Mask Overscan (Horizontal); disabled|enabled
#nestopia_aspect=Preferred Aspect Ratio; auto|ntsc|pal|4:3
#nestopia_genie_distortion=Game Genie Sound Distortion; disabled|enabled
#nestopia_favored_system=System Region; auto|ntsc|pal|famicom|dendy
#nestopia_ram_power_state=RAM Power-on State; 0x00|0xFF|random
#nestopia_button_shift=Shift Buttons Clockwise; disabled|enabled
#nestopia_turbo_pulse=Turbo Pulse Speed; 2|3|4|5|6|7|8|9
```

then add it into core config in `pkg\config\config.go`:
```
	"nes": {
		Path:   "assets/emulator/libretro/cores/nestopia_libretro",
here ->	Config: "assets/emulator/libretro/cores/nestopia_libretro.cfg",
		Width:  256,
		Height: 240,
	},
```

Then recompile the app. Should be OK.
But still, it's a hack. (;/

![feature004](https://user-images.githubusercontent.com/846874/85069090-33d84180-b1bc-11ea-85c8-2bf38fe8236f.gif)

I'm pretty sure, when this project will be a little bit mature, then there will be a lot of people to play to. At least a couple. (:
P.S. And don't worry, your English is fine.

**Comment by Lightbass** [comment]
Wow, good job man, may be i return to idea - play with 4 friends some old games)
