### ISSUE TITLE
How to get the game file?

### ISSUE THREAD

**Issue by lizhiqian-chandler** [giongto35/cloud-game#193]
I started a docker image, but there is no game. Please tell me how to get the game file.

**Comment by sergystepanov** [comment]
Hi @lizhiqian-chandler,
If I understand correctly, you can't see any games when start Docker image?
What operating system are you using?
How do you run Docker?

**Comment by lizhiqian-chandler** [comment]
> Hi @lizhiqian-chandler,
> If I understand correctly, you can't see any games when start Docker image?
> What operating system are you using?
> How do you run Docker?


Yes, u got me, i want play some video games fist o(*￣︶￣*)o 
 I run it use command “make dev.run-docker” 
server information：
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**Comment by sergystepanov** [comment]
Thanks. 
Any chance you could try to run it on Debian-based distro? For "production use" with Docker it supposed to and runs out of the box on Debian (Ubuntu). There are a lot of system where Docker's network is limited and won't work with the current version of the app at all (like ***dows).
If you have time and interest, you can tinker with it: check OS firewall, try Docker in host mode or just build and run it on the host os itself.

**Comment by lizhiqian-chandler** [comment]
Thanks a lot. I will try.

**Comment by lizhiqian-chandler** [comment]
Hi, I run docker-compose on new Ubuntu server, game still not shown. 
trace:
...
cloud-game-local | I0610 01:45:23.453769       7 coordinator.go:45] Starting monitoring server for coordinator
cloud-game-local | I0610 01:45:23.453805       7 monitoring.go:81] Monitoring server is disabled via config
...
cloud-game-local | I0610 01:45:23.459646       8 storage.go:25] Warn: Failed to create client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by lizhiqian-chandler** [comment]
> Thanks.
> Any chance you could try to run it on Debian-based distro? For "production use" with Docker it supposed to and runs out of the box on Debian (Ubuntu). There are a lot of system where Docker's network is limited and won't work with the current version of the app at all (like ***dows).
> If you have time and interest, you can tinker with it: check OS firewall, try Docker in host mode or just build and run it on the host os itself.

Hi, I got an Ubuntu server and I just did these steps：
1. git clone 
2. set env $CLOUD_GAME_GAMES_PATH
3.run docker-compose
pls tell me if I miss any other steps. 
BR
Chandler Lee

**Comment by akh64bit** [comment]
Hi @sergystepanov 
I am also seeing the same behaviour. 
Here is the steps to reproduce 
1) Clone the repo
2) Change .env file to CLOUD_GAME_GAMES_PATH=/opt/games/ (This path is local to my machine)
3) docker-compose up --build

I don't see any games in the browser. This is broken after recent changes. Earlier it used to work fine. Changes after issue #189 causing this issues.

Thanks.

**Comment by lizhiqian-chandler** [comment]
2020-06-10T01:45:23.454295401Z I0610 01:45:23.453590       7 main.go:27] Initializing coordinator server
2020-06-10T01:45:23.454327497Z I0610 01:45:23.453653       7 main.go:28] Coordinator configs {8800 http://localhost:8000   {6601 /coordinator false false}}
2020-06-10T01:45:23.454331361Z I0610 01:45:23.453769       7 coordinator.go:45] Starting monitoring server for coordinator
2020-06-10T01:45:23.454333989Z I0610 01:45:23.453805       7 monitoring.go:81] Monitoring server is disabled via config
2020-06-10T01:45:23.454336396Z I0610 01:45:23.453857       7 coordinator.go:103] Initializing Coordinator Server
2020-06-10T01:45:23.455771818Z I0610 01:45:23.455699       8 main.go:29] Initializing worker server
2020-06-10T01:45:23.456255270Z I0610 01:45:23.455834       8 worker.go:47] Starting monitoring server for overwork
2020-06-10T01:45:23.456401593Z I0610 01:45:23.455883       8 monitoring.go:53] Starting monitoring server at :6601
2020-06-10T01:45:23.456406856Z I0610 01:45:23.455890       8 monitoring.go:75] Prometheus metric is enabled at :6601/worker/metrics
2020-06-10T01:45:23.460082891Z I0610 01:45:23.459646       8 storage.go:25] Warn: Failed to create client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2020-06-10T01:45:23.460099419Z I0610 01:45:23.459659       8 worker.go:154] Listening at port: localhost: 9000
2020-06-10T01:45:23.460102466Z I0610 01:45:23.459723       8 handlers.go:95] Worker connecting to coordinator: ws://localhost:8000/wso?zone=
2020-06-10T01:45:23.460151402Z I0610 01:45:23.460102       7 handlers.go:87] Coordinator: A worker is connecting...
2020-06-10T01:45:23.460251453Z I0610 01:45:23.460212       8 handlers.go:72] Connected to coordinator successfully. &{0xc000345200} <nil>
2020-06-10T01:45:23.460293373Z I0610 01:45:23.460263       7 worker.go:41] Worker f93b025c-5cf0-4a64-b0b7-d257efc88c3f] Generated worker ID
2020-06-10T01:45:23.460304522Z I0610 01:45:23.460274       7 worker.go:41] Worker f93b025c-5cf0-4a64-b0b7-d257efc88c3f] Address:127.0.0.1
2020-06-10T01:45:23.460307293Z I0610 01:45:23.460281       7 worker.go:36] Worker f93b025c-5cf0-4a64-b0b7-d257efc88c3f] Is public: false zone:
2020-06-10T01:45:23.460569943Z I0610 01:45:23.460493       8 coordinator.go:45] Received serverID  f93b025c-5cf0-4a64-b0b7-d257efc88c3f
2020-06-10T03:06:09.709613799Z I0610 03:06:09.709405       8 main.go:27] Initializing coordinator server
2020-06-10T03:06:09.709653520Z I0610 03:06:09.709463       8 main.go:28] Coordinator configs {8800 http://localhost:8000   {6601 /coordinator false false}}
2020-06-10T03:06:09.709659734Z I0610 03:06:09.709527       8 coordinator.go:103] Initializing Coordinator Server
2020-06-10T03:06:09.709774867Z I0610 03:06:09.709708       8 coordinator.go:45] Starting monitoring server for coordinator
2020-06-10T03:06:09.709834521Z I0610 03:06:09.709739       8 monitoring.go:81] Monitoring server is disabled via config
2020-06-10T03:06:09.714736905Z I0610 03:06:09.714594       9 main.go:29] Initializing worker server
2020-06-10T03:06:09.715077341Z I0610 03:06:09.714939       9 worker.go:47] Starting monitoring server for overwork
2020-06-10T03:06:09.715096232Z I0610 03:06:09.714989       9 monitoring.go:53] Starting monitoring server at :6601
2020-06-10T03:06:09.715099429Z I0610 03:06:09.714998       9 monitoring.go:75] Prometheus metric is enabled at :6601/worker/metrics
2020-06-10T03:06:09.719624306Z I0610 03:06:09.719202       9 storage.go:25] Warn: Failed to create client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2020-06-10T03:06:09.719637475Z I0610 03:06:09.719247       9 worker.go:154] Listening at port: localhost: 9000
2020-06-10T03:06:09.719649679Z I0610 03:06:09.719305       9 handlers.go:95] Worker connecting to coordinator: ws://localhost:8000/wso?zone=
2020-06-10T03:06:09.719815905Z I0610 03:06:09.719770       8 handlers.go:87] Coordinator: A worker is connecting...
2020-06-10T03:06:09.719955323Z I0610 03:06:09.719931       9 handlers.go:72] Connected to coordinator successfully. &{0xc000386340} <nil>
2020-06-10T03:06:09.719960811Z I0610 03:06:09.719933       8 worker.go:41] Worker 97e6687a-600e-43c2-9632-e5b46040c2ca] Generated worker ID
2020-06-10T03:06:09.720001376Z I0610 03:06:09.719945       8 worker.go:41] Worker 97e6687a-600e-43c2-9632-e5b46040c2ca] Address:127.0.0.1
2020-06-10T03:06:09.720005572Z I0610 03:06:09.719953       8 worker.go:36] Worker 97e6687a-600e-43c2-9632-e5b46040c2ca] Is public: false zone:
2020-06-10T03:06:09.720156332Z I0610 03:06:09.720131       9 coordinator.go:45] Received serverID  97e6687a-600e-43c2-9632-e5b46040c2ca

**Comment by sergystepanov** [comment]
Hey @lizhiqian-chandler, @akh64bit,

This is strange, since it's working just fine in Ubuntu.
Alright, could you post your container info:
- run the compose with your settings
- run separately `docker ps` to find `CONTAINER ID` of running cloud-game-local image, should be something like e562a0528234
- run `docker inspect {your container id}` and post the output into this topic
- run `docker exec -it {your container id} /bin/sh -c "ls assets/games" and post the output here as well

**Comment by akh64bit** [comment]
Thanks @giongto35 for quick reply. You right it had to do with CLOUD_GAME_GAMES_PATH settings. Looks like I was not properly mounting the folder in my docker settings.
I just tested and it works fine for me. Awesome.

**Comment by lizhiqian-chandler** [comment]
> I think it should be related to improper CLOUD_GAME_GAMES_PATH setting on user's side. I just update MakeFile so it's easier to run
> [42d7e16](https://github.com/giongto35/cloud-game/commit/42d7e166e89bd191ff9113c4886fff84d29364bd)
> 
> Can you repull and try running `make dev.run-docker` again? @lizhiqian-chandler @akh64bit ?
Thanks a lot for @giongto35 & @sergystepanov. i execute the command by steps. trace show another problem, slice bounds out of range [1:0]

root@edgegallery-x86-ubuntu-3:/usr/local/share/cloud-game# docker-compose up
Starting cloud-game-local
Attaching to cloud-game-local
cloud-game-local | panic: runtime error: slice bounds out of range [1:0]
cloud-game-local |
cloud-game-local | goroutine 1 [running]:
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.isValidGameType(...)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:63
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.getAllGames.func1(0xc00009e860, 0x13, 0xa66160, 0xc0000b3450, 0x0, 0x0, 0x4a52af, 0xc0000b3450)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:45 +0x277
cloud-game-local | path/filepath.walk(0xc00009e860, 0x13, 0xa66160, 0xc0000b3450, 0xc00009be88, 0x0, 0x0)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:360 +0x425
cloud-game-local | path/filepath.walk(0x9a2934, 0xc, 0xa66160, 0xc0000b24e0, 0xc00009be88, 0x0, 0x3f8c8cf1bfc5e)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:384 +0x2ff
cloud-game-local | path/filepath.Walk(0x9a2934, 0xc, 0xc00009be88, 0xc00009bea8, 0x79587d)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:406 +0xff
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.getAllGames(0x9a2934, 0xc, 0xc0000aa370, 0xc0000e8000, 0xc0000e8000)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:44 +0x6f
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.init.0()
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:25 +0x36
cloud-game-local | panic: runtime error: slice bounds out of range [1:0]
cloud-game-local |
cloud-game-local | goroutine 1 [running]:
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.isValidGameType(...)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:63
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.getAllGames.func1(0xc0000bc9c0, 0x13, 0xef1ba0, 0xc000289ad0, 0x0, 0x0, 0x4ade5f, 0xc000289ad0)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:45 +0x277
cloud-game-local | path/filepath.walk(0xc0000bc9c0, 0x13, 0xef1ba0, 0xc000289ad0, 0xc000107e58, 0x0, 0x0)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:360 +0x425
cloud-game-local | path/filepath.walk(0xdcc843, 0xc, 0xef1ba0, 0xc000288b60, 0xc000107e58, 0x0, 0xc000107e38)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:384 +0x2ff
cloud-game-local | path/filepath.Walk(0xdcc843, 0xc, 0xc000107e58, 0x41b52b, 0xc000107ea0)
cloud-game-local |      /usr/local/go/src/path/filepath/path.go:406 +0xff
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.getAllGames(0xdcc843, 0xc, 0x7, 0xc000294080, 0xc000292150)
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:44 +0x6f
cloud-game-local | github.com/giongto35/cloud-game/pkg/util/gamelist.init.0()
cloud-game-local |      /go/src/github.com/giongto35/cloud-game/pkg/util/gamelist/games.go:25 +0x36

**Comment by lizhiqian-chandler** [comment]
root@edgegallery-x86-ubuntu-3:~# docker inspect cf225bac9815
[
    {
        "Id": "cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4",
        "Created": "2020-06-11T02:10:33.226318792Z",
        "Path": "bash",
        "Args": [
            "-c",
            "coordinator --v=5 & worker --coordinatorhost localhost:8000"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 20530,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-06-11T02:27:12.820609893Z",
            "FinishedAt": "2020-06-11T02:24:01.576802363Z"
        },
        "Image": "sha256:1a2b94c3561f888f43d53125b7330ad5140f05a1ef8ae42a75fb7d7a75173598",
        "ResolvConfPath": "/var/lib/docker/containers/cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4/hostname",
        "HostsPath": "/var/lib/docker/containers/cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4/hosts",
        "LogPath": "/var/lib/docker/containers/cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4/cf225bac9815ab2c8f114d3479692fa5163a4c418dcb7e2873552a83647b52b4-json.log",
        "Name": "/cloud-game-local",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/usr/local/share/cloud-game/assets/games:/usr/local/share/cloud-game/assets/games:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {
                "3478/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3478"
                    }
                ],
                "3478/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "3478"
                    }
                ],
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ],
                "9000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5ff488162ac0f77d3bd8ded095ed4730af44760c33315b8646ad823793489719-init/diff:/var/lib/docker/overlay2/fa871eac5173ce25bf4d94eb43128a90fb8c0b7e46c0e13a9a40d22112967c01/diff:/var/lib/docker/overlay2/29d39488f964b09c30be65d8d15e199d21e0cf637ec9ed6db190fa80c459f1bb/diff:/var/lib/docker/overlay2/a2a61b68564571e7d62afc9f9481396261cdd71d01832f0d656f83d8aaa0b08d/diff:/var/lib/docker/overlay2/90f0e1cadec7b41ecfdd10bee0ef4eda93e6a555cc22fdf3dd11bdf5e548ef1d/diff:/var/lib/docker/overlay2/d75201b6d4546095110d60e0d431d6a7f7a04ccf0129a61ba596badb8d894426/diff:/var/lib/docker/overlay2/96ccd64dba7f4caea73beb994f189dc0b7af13af1536e564dee2823a09d15c68/diff:/var/lib/docker/overlay2/5bfd1660f5b2c221ed5646eb3cbb8fd0a992988572cb73d6c35e074ef3a1a910/diff",
                "MergedDir": "/var/lib/docker/overlay2/5ff488162ac0f77d3bd8ded095ed4730af44760c33315b8646ad823793489719/merged",
                "UpperDir": "/var/lib/docker/overlay2/5ff488162ac0f77d3bd8ded095ed4730af44760c33315b8646ad823793489719/diff",
                "WorkDir": "/var/lib/docker/overlay2/5ff488162ac0f77d3bd8ded095ed4730af44760c33315b8646ad823793489719/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/usr/local/share/cloud-game/assets/games",
                "Destination": "/usr/local/share/cloud-game/assets/games",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "edgegallery-x86-ubuntu-3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3478/tcp": {},
                "3478/udp": {},
                "8000/tcp": {},
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "bash",
                "-c",
                "coordinator --v=5 & worker --coordinatorhost localhost:8000"
            ],
            "Image": "cloud-game-local",
            "Volumes": {
                "/usr/local/share/cloud-game/assets/games": {}
            },
            "WorkingDir": "/usr/local/share/cloud-game",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "706aa4bd500f30b377c55ba0816ebf347baaf7c9dbdd2fc8802f01005c851068",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "cloudgame",
                "com.docker.compose.service": "cloud-game",
                "com.docker.compose.version": "1.8.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ff773cf579a90e9b5546286890c9a33211e3629dbb5061d84bc8bf855dca2e28",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2f8b493fa49c23a7092547be4d9e2555354a31ab9c178ff41e304e663a14622b",
                    "EndpointID": "47bcc5601adb8f168ad32619ab61d80fe073bd3525bcbc66227443964fb57ee6",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by giongto35** [comment]
@lizhiqian-chandler 

"Binds": [
"/usr/local/share/cloud-game/assets/games:/usr/local/share/cloud-game/assets/games:rw"
],

Your bind seems like wrong, you should set CLOUD_GAME_GAMES_PATH to your game folder instead. The way you do is not the correct way to set the environment
Instead of
> set env $CLOUD_GAME_GAMES_PATH
do
`export CLOUD_GAME_GAMES_PATH=/path/games`

Or Esier, you can use my updated utility script `**make dev.run-docker**`.

**Comment by lizhiqian-chandler** [comment]
> @lizhiqian-chandler
> 
> "Binds": [
> "/usr/local/share/cloud-game/assets/games:/usr/local/share/cloud-game/assets/games:rw"
> ],
> 
> Your bind seems like wrong, you should set CLOUD_GAME_GAMES_PATH to your game folder instead. The way you do is not the correct way to set the environment
> Instead of
> 
> > set env $CLOUD_GAME_GAMES_PATH
> > do
> > `export CLOUD_GAME_GAMES_PATH=/path/games`
> 
> Or Esier, you can use my updated utility script `**make dev.run-docker**`.

I followed the steps you listed, game list still empty :(
![image](https://user-images.githubusercontent.com/66100998/84360766-34da0380-abfd-11ea-95a2-e19dc98e2722.png)

**Comment by lizhiqian-chandler** [comment]
> Thanks @giongto35 for quick reply. You right it had to do with CLOUD_GAME_GAMES_PATH settings. Looks like I was not properly mounting the folder in my docker settings.
> I just tested and it works fine for me. Awesome.

Hi, @akh64bit,  which file of game u use, can u share to me?

**Comment by sergystepanov** [comment]
@lizhiqian-chandler, Ubuntu that you're using is a standalone system, not a virtual machine or some kind of virtualization, and you're opening your browser on that Ubuntu system, right?
If it outputs a proper listing of games after `docker exec -it cf225bac9815 /bin/sh -c "ls assets/games"` then it's not games folder problem.

**Comment by giongto35** [comment]
@lizhiqian-chandler  I already put some games in this folder: https://github.com/giongto35/cloud-game/tree/master/assets/games
You should specify the path to this folder

Did you fail when running "make dev.run-docker" as well?

**Comment by lizhiqian-chandler** [comment]
> @lizhiqian-chandler I already put some games in this folder: https://github.com/giongto35/cloud-game/tree/master/assets/games
> You should specify the path to this folder
> 
> Did you fail when running "make dev.run-docker" as well?

yes i running program by make command.

**Comment by sergystepanov** [comment]
@lizhiqian-chandler, 
Well, I re-tested it on **4** freshly installed distros (Ubuntu 16, 18, 20, Debian 10), with Docker installed as it said in the official manual for this systems. Had no problems whatsoever. No idea what's wrong, can't reproduce.

_If you want_, we can try troubleshoot it one more time, **just follow the steps exactly**, described below:
1. Add into docker-compose.yml debug flags:
```
    environment:
      PIONS_LOG_DEBUG: pc,dtls
      PIONS_LOG_INFO: all
      PIONS_LOG_TRACE: ice
```
2. Run:
```
make dev.run-docker
```
3. As said before, get the inspect log of running container: docker ps and **docker inspect** by its id, and post it again here
3. Open in your browser `localhost:8000`
4. Wait 10 seconds
5. Get container logs and post them here (**docker logs** id)

If don't -- then build it or try binaries from my fork.
Cheers/

**Comment by lizhiqian-chandler** [comment]
I've got an page error
![image](https://user-images.githubusercontent.com/66100998/84454806-2f78c980-ac8e-11ea-9157-b6ee49f3eaea.png)

**Comment by lizhiqian-chandler** [comment]
> I've got an page error
> ![image](https://user-images.githubusercontent.com/66100998/84454806-2f78c980-ac8e-11ea-9157-b6ee49f3eaea.png)


Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by giongto35** [comment]
@lizhiqian-chandler what is the browser error? can we see the browser log as well?
and you should do as what sergy suggests `docker exec -it xxx /bin/sh -c "ls assets/games"` where xxx is your docker container ID to check if the game folder is mounted properly.

**Comment by lizhiqian-chandler** [comment]
http://119.8.125.174:8000/

**Comment by lizhiqian-chandler** [comment]
root@edgegallery-x86-ubuntu-3:~# docker exec -it 5a21077ff77b /bin/bash -c "ls assets/games"
'Super Mario Bros.nes'  'Sushi The Cat.gba'   anguna.gba   neogeo.zip
root@edgegallery-x86-ubuntu-3:~#

**Comment by sergystepanov** [comment]
@giongto35, he's running it not as localhost without https config that's why it fails. 
With ws it runs:
![image](https://user-images.githubusercontent.com/846874/84492282-a1f9a180-acae-11ea-80ae-70e5e8d5586f.png)

**Comment by sergystepanov** [comment]
Maybe change it 
```
  // if localhost, local LAN connection
        if (location.hostname === "localhost" || location.hostname === "127.0.0.1" || location.hostname.startsWith("192.168")) {
            scheme = "ws"
        } else {
            scheme = "wss"
        }
        conn = new WebSocket(`${scheme}://${location.host}/ws?${paramString.toString()}`);
```
If protocol is https then use wss? Without local domains check?
Also it seems, echo is not using app address, localhost instead.
I can a PR some time later today, if you want.

**Comment by lizhiqian-chandler** [comment]
> Maybe change it
> 
> ```
>   // if localhost, local LAN connection
>         if (location.hostname === "localhost" || location.hostname === "127.0.0.1" || location.hostname.startsWith("192.168")) {
>             scheme = "ws"
>         } else {
>             scheme = "wss"
>         }
>         conn = new WebSocket(`${scheme}://${location.host}/ws?${paramString.toString()}`);
> ```
> 
> If protocol is https then use wss? Without local domains check?
> Also it seems, echo is not using app address, localhost instead.
> I can a PR some time later today, if you want.

Thank u @sergystepanov, the system i test will be seperated for 2 parts, fe(front-end) and be(background-end), so really need ur help.
BR Chandler Lee

**Comment by giongto35** [comment]
Thank you @sergystepanov . It makes sense now.

**Comment by sergystepanov** [comment]
@giongto35, made a PR.
Could you show him how to change default /echo address from localhost? There is a coordinator param and environment switch?

**Comment by lizhiqian-chandler** [comment]
Hi, @giongto35 ,@sergystepanov. I‘ve modified the JS code of my local server, I can play game now, Thank you very much for your help!

**Comment by lizhiqian-chandler** [comment]
I can see 3 games, can u share me more? like Contra, kof98 and other classic games. 
![image](https://user-images.githubusercontent.com/66100998/84615846-aca97600-aefc-11ea-98b3-14622efe6e06.png)

**Comment by giongto35** [comment]
@lizhiqian-chandler good to hear that you successfully launch it :D 
due to copyright, I cannot include those games in the repo. You can search and download it like searching "contra roms" in Google. Just put the rom in game folder and it should work.

**Comment by lizhiqian-chandler** [comment]
> @lizhiqian-chandler good to hear that you successfully launch it :D
> due to copyright, I cannot include those games in the repo. You can search and download it like searching "contra roms" in Google. Just put the rom in game folder and it should work.

Thank u very much  : )

**Comment by aslily1234** [comment]
after modify [web/js/network/socket.js] like this
   `    const init = (roomId, zone) => {
        const params = new URLSearchParams({room_id: roomId, zone: zone}).toString()
        const address = `${location.protocol !== 'https:' ? 'ws' : 'wss'}://${location.host}/ws?${params}`;
        console.info(`[ws] connecting to ${address}`);

        // if localhost, local LAN connection
        if (location.hostname === "localhost" || location.hostname === "127.0.0.1" || location.hostname.startsWith("192.168")) {
            scheme = "ws"
        } else {
            scheme = "wss"
        }
        conn = new WebSocket(`${scheme}://${location.host}/ws?${params}`);

        // conn = new WebSocket(address);`

websocket still has error [failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR]

can anybody help？
