### ISSUE TITLE
N64 Support

### ISSUE THREAD

**Issue by 88hcsif** [giongto35/cloud-game#194]
Hi!
I have a branch that adds Nintendo 64 support.
It adds support for OpenGL cores in general but I only tested it with Mupen64plus and Mupen64plusNext and on a Raspberry Pi.
It probably needs more work to run on every system and with other OpenGL libretro libraries.
The branch also adds support for analog stick from frontend to backend.
And it adds a bunch of settings that let me run coordinator and worker over HTTPS on my Raspberry Pi.
What is the best way to send over a pull request to get some feedback and potentially merge these changes?
Could I get write access to create a remote branch?

**Comment by sergystepanov** [comment]
Hey! Oh, wow, you've even ported it to ARMx64.
I made a new branch [feature/n64](https://github.com/giongto35/cloud-game/tree/feature/n64), I think, you will be able to make a PR into it from your repo fork.
Looking forward to it.

**Comment by sergystepanov** [comment]
Actually, @giongto35, it'll be easier if you grant him full access to this branch `feature/n64`.
