### ISSUE TITLE
Swap A and B

### ISSUE THREAD

**Issue by 88hcsif** [giongto35/cloud-game#199]
Should we swap A and B?

https://docs.libretro.com/library/pcsx_rearmed/
https://docs.libretro.com/library/beetle_bsnes/
I think in most libretro cores B is meant to be the down most button and A is meant to be the right most.
That would also match the layout of Nintendo controllers (NES/SNES/Gameboy/N64) but it would conflict with the Xbox controller...
(But at the moment X and Y do not match the Xbox controller anyways)
I have not tried to play PS1 games, are cross and circle swapped?

**Comment by giongto35** [comment]
@88hcsif : I think you are right. I indeed feel not natural with my key input but don't know why : D. I think we can swap it.

**Comment by 88hcsif** [comment]
@sergystepanov Thanks for fixing this!
Do we need to change anything in https://github.com/giongto35/cloud-game/blob/master/web/js/input/joystick.js?
I only have a PS3 controller which currently needs a hack which probably I need to update.
I do not know how other controllers map the A and B buttons right now.
