### ISSUE TITLE
Port mapping problem

### ISSUE THREAD

**Issue by lizhiqian-chandler** [giongto35/cloud-game#200]
Hi, sorry to disturb, after i run server successfully, Unfortunately that server is borrowed from other team, when i build game server on my own server, some ports has been taken by other server, i do some port mapping.
![image](https://user-images.githubusercontent.com/66100998/84845089-6e3bc480-b07e-11ea-83f1-b356d57ea1cb.png)
but game can not show. trace follows:
```
cloud-game-local | I0617 01:21:14.571645      10 webrtc.go:115] === StartClient ===
cloud-game-local | ice WARNING: 2020/06/17 01:21:14 could not get server reflexive address udp6 stun:stun.l.google.com:19302: write udp6 [::]:55330->[2404:6800:4008:c01::7f]:19302: sendto: network is unreachable
cloud-game-local | I0617 01:21:14.629433      10 webrtc.go:135] Add video track
cloud-game-local | I0617 01:21:14.629756      10 webrtc.go:225] Created Offer
cloud-game-local | pc INFO: 2020/06/17 01:21:14 signaling state changed to have-local-offer
cloud-game-local | I0617 01:21:14.629941      10 coordinator.go:89] Start peerconnection 0e2a73db-a703-4eb5-abaf-6e3ad61582d1
cloud-game-local | I0617 01:21:14.629980      10 webrtc.go:186] OnIceCandidate: candidate:foundation 1 udp 2130706431 172.17.0.2 55984 typ host
cloud-game-local | I0617 01:21:14.630101      10 webrtc.go:186] OnIceCandidate: candidate:foundation 1 udp 1694498815 159.138.63.8 56211 typ srflx raddr 0.0.0.0 rport 56211
cloud-game-local | I0617 01:21:14.630177       9 browser.go:35] Browser 0e2a73db-a703-4eb5-abaf-6e3ad61582d1] Received SDP from worker -> sending back to browser
cloud-game-local | I0617 01:21:14.630212       9 worker.go:41] Worker eac5c499-eded-4cc2-8b0f-43ee6cb95228] Received IceCandidate from worker -> relay to browser
cloud-game-local | I0617 01:21:14.630255       9 worker.go:41] Worker eac5c499-eded-4cc2-8b0f-43ee6cb95228] Received IceCandidate from worker -> relay to browser
cloud-game-local | I0617 01:21:14.630270       9 worker.go:41] Worker eac5c499-eded-4cc2-8b0f-43ee6cb95228] Received IceCandidate from worker -> relay to browser
cloud-game-local | I0617 01:21:14.773509       9 browser.go:35] Browser 0e2a73db-a703-4eb5-abaf-6e3ad61582d1] Received browser answered SDP -> relay to worker
cloud-game-local | I0617 01:21:14.773734      10 coordinator.go:106] Received answer SDP from browser
cloud-game-local | pc INFO: 2020/06/17 01:21:14 signaling state changed to stable
cloud-game-local | I0617 01:21:14.773918      10 webrtc.go:258] Set Remote Description
cloud-game-local | ice DEBUG: 01:21:14.774009 agent.go:597: Started agent: isControlling? true, remoteUfrag: "ZWsA", remotePwd: "pN6UUm6XAJ68fkE4nQcUn6J6"
cloud-game-local | ice INFO: 2020/06/17 01:21:14 Setting new connection state: Checking
cloud-game-local | ice TRACE: 01:21:14.774052 selection.go:96: pinging all candidates
cloud-game-local | pc INFO: 2020/06/17 01:21:14 ICE connection state changed: checking
cloud-game-local | I0617 01:21:14.774087      10 webrtc.go:170] ICE Connection State has changed: checking
cloud-game-local | I0617 01:21:14.788388       9 browser.go:35] Browser 0e2a73db-a703-4eb5-abaf-6e3ad61582d1] Received IceCandidate from browser -> relay to worker
cloud-game-local | I0617 01:21:14.788541      10 coordinator.go:127] Received remote Ice Candidate from browser
cloud-game-local | I0617 01:21:14.788568      10 webrtc.go:269] Decoded Ice: candidate:2693824611 1 udp 2113937151 494facd4-1346-47d2-a1ce-26c536ac6b7a.local 57250 typ host generation 0 ufrag ZWsA network-cost 999
cloud-game-local | I0617 01:21:14.788668      10 webrtc.go:277] Add Ice Candidate: candidate:2693824611 1 udp 2113937151 494facd4-1346-47d2-a1ce-26c536ac6b7a.local 57250 typ host generation 0 ufrag ZWsA network-cost 999
cloud-game-local | ice TRACE: 01:21:16.774177 selection.go:96: pinging all candidates
cloud-game-local | ice TRACE: 01:21:18.774180 selection.go:96: pinging all candidates
cloud-game-local | ice TRACE: 01:21:20.774166 selection.go:96: pinging all candidates
cloud-game-local | ice TRACE: 01:21:22.774158 selection.go:96: pinging all candidates
cloud-game-local | ice TRACE: 01:21:24.774097 selection.go:96: pinging all candidates
cloud-game-local | ice TRACE: 01:21:24.774176 selection.go:40: check timeout reached and no valid candidate pair found, marking connection as failed
cloud-game-local | ice INFO: 2020/06/17 01:21:24 Setting new connection state: Failed
cloud-game-local | pc INFO: 2020/06/17 01:21:24 ICE connection state changed: failed
cloud-game-local | pc INFO: 2020/06/17 01:21:24 peer connection state changed: failed
cloud-game-local | I0617 01:21:24.774802      10 webrtc.go:170] ICE Connection State has changed: failed
```

**Comment by sergystepanov** [comment]
Hey,

No problem, when you run it in `host` mode which is default for Ubuntu's Docker, it ignores your port mappings, basically it runs with port config of the app itself on your host machine.
It's not possible atm to run it in bridge mode with active port forwarding as you're trying to do, instead you should change unavailable ports in the app config.
I assume there are only two ports: 8000 and 9000 that are busy on your machine, right?
Can't say right away how to change them, I'll need to see code, will look later.

**Comment by giongto35** [comment]
Hi @lizhiqian-chandler,
I would love to hear bug report. It is the way to fix and improve the project.
Seems like it's the issue of WebRTC initialization. Are you trying to run on a remote cloud server and trying to connect to it? 

@sergystepanov, he didn't say he ran on host mode. And when you mention "is it possible to change them", what is them here?

**Comment by sergystepanov** [comment]
@giongto35, 8000, 9000.

**Comment by lizhiqian-chandler** [comment]
> Hi @lizhiqian-chandler,
> I would love to hear bug report. It is the way to fix and improve the project.
> Seems like it's the issue of WebRTC initialization. Are you trying to run on a remote cloud server and trying to connect to it?
> And how do you open the page. Is it like "http://172.18.0.1:32380/" ?
> 
> @sergystepanov, he didn't say he ran on host mode. And when you mention "is it possible to change them", what is them here?

@giongto35, yes, I deploy the image on remote cloud server, 8000 and 9000 port is foribidden. so i mapping port 8000 to 32380, with bridge mode.
PS: 
Our team is working on an edge computing solution, I found cloud-game is good to show, after testing cloud-game by docker way, I will test its deployment on k8s. step by step.  : )

**Comment by giongto35** [comment]
I don't know what is the easiest way to deploy on remote server. You should run docker in host network mode so that webRTC can run. And as sergy mentioned, docker bridge is not compatible with host mode, so you should use OS port mapping and let docker run in host mode

// Using OS iptables to map port 32380 to port 8000
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8000; iptables-save;
// Run Docker in host mode
add `network_mode: "host"` to dockercompose

**Comment by sergystepanov** [comment]
> And as sergy mentioned, docker bridge is not compatible with host mode, so you should use OS port mapping and let docker run in host mode
> 
> // Using OS iptables to map port 32380 to port 8000
> iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8000; iptables-save;
> // Run Docker in host mode
> add `network_mode: "host"` to dockercompose

If he turns on the `host` mode, wouldn't it make a conflict between host machine's 8000, 9000 ports and exposed by Docker app ports?

**Comment by lizhiqian-chandler** [comment]
So, guess i need to find other way to do that, thank both of u two : ）

**Comment by sergystepanov** [comment]
Hey,

I've made a fix in `fix/port-config` branch that you might wanna check out.
To change the ports with flags:
```
coordinator --httpPort=8001 --pingServer=http://localhost:9001
worker --coordinatorhost localhost:8001 --httpPort=9001
```
