### ISSUE TITLE
Chrome forced WebRTC stereo downmix to mono mitigation

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#201]
According to ongoing Chromium bug 818180: [WebRTC Stereo heard as mono in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=818180), it plays any stereo track as downmixed mono. And Firefox doesn't seem to be affected by this issue.
If you explicitly set [stereo preference](https://tools.ietf.org/html/draft-spittka-payload-rtp-opus-03#page-12) for remote sdp, then during the offer/answer negotiation of a WebRTC connection it will ignore these channel preferences on the client.
As a temporary dirty fix it's possible to force stereo mode by manually editing local SDP value, i.e.:
```javascript
...
answer = await connection.createAnswer({});
answer.sdp = answer.sdp.replace('useinbandfec=1', 'useinbandfec=1;stereo=1;sprop-stereo=1');
await connection.setLocalDescription(answer);
...
```
Successfully tested on Chrome 80+.

**Comment by giongto35** [comment]
interesting. How did you figure that? Did you sense the difference between stereo and mono sound : D

**Comment by sergystepanov** [comment]
Compare sushi the cat in both browsers since it has noticible channel separation. It felt strange, I mean the sound, from the beginning and with latest FF support it became evident.
