### ISSUE TITLE
Can't see any game when i deploy this project on public cloud, but it's ok for local test.

### ISSUE THREAD

**Issue by aslily1234** [giongto35/cloud-game#216]
deploy on public cloud, Can't see any game
<img width="936" alt="test" src="https://user-images.githubusercontent.com/8610207/86349082-2c706800-bc93-11ea-93a4-ea0cf3465352.png">

Running this command  **[ go run cmd/worker/main.go --coordinatorhost localhost:8000]**  produces this output
`I0702 18:25:28.043531   10349 coordinator.go:57] Received a request to createOffer from browser via coordinator
I0702 18:25:28.043621   10349 webrtc.go:120] === StartClient ===
I0702 18:25:33.060331   10349 webrtc.go:140] Add video track
I0702 18:25:33.060674   10349 webrtc.go:230] Created Offer
I0702 18:25:33.060908   10349 coordinator.go:89] Start peerconnection 068f71c9-22b1-4446-a7bd-93e2cca0ca80
I0702 18:25:33.060968   10349 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.0.14 44035 typ host
I0702 18:25:33.209218   10349 coordinator.go:106] Received answer SDP from browser
I0702 18:25:33.209461   10349 webrtc.go:263] Set Remote Description
I0702 18:25:33.209556   10349 webrtc.go:175] ICE Connection State has changed: checking
I0702 18:25:33.259256   10349 coordinator.go:127] Received remote Ice Candidate from browser
I0702 18:25:33.259303   10349 webrtc.go:274] Decoded Ice: candidate:3006760579 1 udp 2113937151 3342d772-465f-4f23-972c-9de2fdba397d.local 60439 typ host generation 0 ufrag dmfa network-cost 999
I0702 18:25:33.259374   10349 webrtc.go:282] Add Ice Candidate: candidate:3006760579 1 udp 2113937151 3342d772-465f-4f23-972c-9de2fdba397d.local 60439 typ host generation 0 ufrag dmfa network-cost 999
I0702 18:25:43.209787   10349 webrtc.go:175] _**ICE Connection State has changed: failed**_`

however, when i test on local , it's ok.

Running this command  **[ go run cmd/worker/main.go --coordinatorhost localhost:8000]**  produces this output
`
I0702 18:28:01.050538   54449 coordinator.go:57] Received a request to createOffer from browser via coordinator
I0702 18:28:01.050709   54449 webrtc.go:120] === StartClient ===
I0702 18:28:06.142189   54449 webrtc.go:140] Add video track
I0702 18:28:06.142605   54449 webrtc.go:230] Created Offer
I0702 18:28:06.142791   54449 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.3.8 61384 typ host
I0702 18:28:06.142905   54449 coordinator.go:89] Start peerconnection d4a5fcaa-0487-4620-b29a-4411a842f2f7
I0702 18:28:06.222716   54449 coordinator.go:106] Received answer SDP from browser
I0702 18:28:06.223093   54449 webrtc.go:263] Set Remote Description
I0702 18:28:06.223271   54449 webrtc.go:175] ICE Connection State has changed: checking
I0702 18:28:06.237462   54449 coordinator.go:127] Received remote Ice Candidate from browser
I0702 18:28:06.237490   54449 webrtc.go:274] Decoded Ice: candidate:1687531457 1 udp 2113937151 c24a83d7-f188-4123-971d-70b021d202c5.local 64315 typ host generation 0 ufrag EvJp network-cost 999
I0702 18:28:06.237589   54449 webrtc.go:282] Add Ice Candidate: candidate:1687531457 1 udp 2113937151 c24a83d7-f188-4123-971d-70b021d202c5.local 64315 typ host generation 0 ufrag EvJp network-cost 999
I0702 18:28:08.290335   54449 webrtc.go:175] **_ICE Connection State has changed: connected_**`

**Comment by aslily1234** [comment]
how to fixed {ICE Connection State has changed: failed} problem? can anyone help me ?

**Comment by giongto35** [comment]
Hi @aslily1234 ,
"localhost:8000" is local ip, you should substitute it with the address of public address : D. If you deploy on a host with IP 227.14.23.45 for example, you should run "go run cmd/worker/main.go --coordinatorhost 227.14.23.45:8000"

**Comment by aslily1234** [comment]
@giongto35 thanks for your time. but after changing to public address, still the same error:
`I0703 09:07:01.906322    7203 webrtc.go:140] Add video track
I0703 09:07:01.906602    7203 webrtc.go:230] Created Offer
I0703 09:07:01.906722    7203 coordinator.go:89] Start peerconnection 88d0a6f2-a596-424e-b0e8-86efbb47592a
I0703 09:07:01.906749    7203 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 172.18.0.1 49874 typ host
I0703 09:07:01.906821    7203 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 172.17.0.1 47985 typ host
I0703 09:07:01.906850    7203 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 192.168.0.14 55404 typ host
I0703 09:07:02.049474    7203 coordinator.go:127] Received remote Ice Candidate from browser
I0703 09:07:02.049511    7203 webrtc.go:274] Decoded Ice: candidate:3006760579 1 udp 2113937151 09037eb4-c31a-46bb-bd86-97f74715d238.local 63698 typ host generation 0 ufrag nrgJ network-cost 999
I0703 09:07:02.049521    7203 webrtc.go:278] Add Ice candidate from peer failed
I0703 09:07:02.049525    7203 coordinator.go:135] Error: Cannot add IceCandidate of client: 88d0a6f2-a596-424e-b0e8-86efbb47592a
I0703 09:07:02.049556    7203 coordinator.go:106] Received answer SDP from browser
I0703 09:07:02.049702    7203 webrtc.go:263] Set Remote Description
I0703 09:07:02.049783    7203 webrtc.go:175] ICE Connection State has changed: checking
I0703 09:07:12.049906    7203 webrtc.go:175] ICE Connection State has changed: failed`

![image](https://user-images.githubusercontent.com/8610207/86421536-f8d22400-bd0c-11ea-97da-45bf4d83ba73.png)

**Comment by aslily1234** [comment]
and i have changed Security group to allow [8000 , 9000] for [TCP, UDP] , but still the same error

**Comment by wtuickqmq** [comment]
I also encountered a similar problem, and it is on the local network. I installed uubuntu in wsl2 of win10

**Comment by giongto35** [comment]
@aslily1234 Can you open all ports or disable firewall. WebRTC mechanism have a mechanism to dynamically open port. https://stackoverflow.com/questions/29563830/use-specific-ports-for-webrtc

**Comment by giongto35** [comment]
@wtuickqmq can you try with "make dev.run-docker". Can you show me the browser log + console log?

**Comment by aslily1234** [comment]
@wtuickqmq @giongto35 i fixed this problem. the key point is the TURN server. 
after changing TURN server from [stun:stun.l.google.com:19302] to [stun:stun2.l.google.com:19302] , the problem is disappeared.

Specific steps：
    vim cloud_game_root_dir/pkg/config/config.go
    vim cloud_game_root_dir/webrtc/webrtc.go 

    change [stun:stun.l.google.com:19302] to [stun:stun2.l.google.com:19302] and save the files

Other options: 
stun:stun1.l.google.com:19302
stun:stun2.l.google.com:19302
stun:stun3.l.google.com:19302
stun:stun4.l.google.com:19302

**Comment by giongto35** [comment]
@aslily1234  ah I see. I remember I faced this issue once before. It also fails when the STUN server is stun:stun.l.google.com but works after I change to a different one. I don't know the reason though. Good to hear that you managed to fix it.
