### ISSUE TITLE
Add support for virtual gamepad?

### ISSUE THREAD

**Issue by poVoq** [giongto35/cloud-game#223]
There is a pretty cool project that allows one to remotely connect smartphones as virtual gamepads:

https://github.com/jehervy/node-virtual-gamepads

It might already work to some extend, but nicely integrate it would allow playing with multiple players on one screen or use a different screen to play via the connected smart-phone.

Thanks for looking into it :)

**Comment by giongto35** [comment]
Hi @poVoq ,

Thank you for your interest in the project and suggestion.

I took a look at the virtual gamepad. I think as the owner replied, our side already has the gamepad. 
Besides, multiplayer is also already supported in our service with deep-link as well. https://github.com/giongto35/cloud-game#crowd-play-play-game-together

**Comment by poVoq** [comment]
Maybe an option for a deep-link with game-pad only (no actual game stream) would be good to add? That would reduce the server resources used in a scenario as outlined above where a single screen is used for multiple players.

**Comment by sergystepanov** [comment]
@poVoq, so, you mean run some game, let's say, one stream will be on a big screen just as audio and video and a couple of others as a controller interface on tablets and phones. Actually, it makes sense not from the server resources offload perspective but more from the UX side. I think it could be added to some memo-roadmap-todo list somewhere. (:

And that project is interesting to look at as a history. Coffeescript made me shed a nostalgic tear.
