### ISSUE TITLE
having trouble running N64 on ubuntu, No available video device

### ISSUE THREAD

**Issue by ravelab** [giongto35/cloud-game#225]
Am I missing a video driver? Other emulators work. Thanks

-----------------------------------
--- System audio and video info ---
-----------------------------------
  Aspect ratio:  1.3333333730697632
  Base width:  320
  Base height:  240
  Max width:  320
  Max height:  240
  Sample rate:  44100
  FPS:  60
-----------------------------------
panic: 

goroutine 17 [running, locked to thread]:
github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch.initVideo()
        /root/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:376 +0x993
github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch._cgoexpwrap_58c817539c33_initVideo()
        _cgo_gotypes.go:752 +0x25
make: *** [Makefile:77: dev.run] Error 2

**Comment by giongto35** [comment]
Hi @ravelab ,
Thank you for reporting it : D. I will try checking it later.

**Comment by sergystepanov** [comment]
I think this is related solely to SDL2 render route of the app if I understand the error from the message correctly: `No available video device` -- that's the SDL2 error.

It's similar to what I have inside WSL2:
![image](https://user-images.githubusercontent.com/846874/93072762-870e4300-f68a-11ea-98fd-36c4f3f7a976.png)

Guess, it needs X11 server (local: `DISPLAY=:0`, or some remote), and since n64 emulator is hardware-accelerated -- some GPU drivers (Mesa or proprietary).
@giongto35, will it work with xvfb (in mem "goodbye gpu-acceleration" mode)? Just curious, never worked with it.

(also want to mention that it didn't work for me when I tried to run initial PR, because my CPU has only ancient GL version support)

**Comment by giongto35** [comment]
@sergystepanov you made some good observations here. Let me try with XVFB, I think It can solve this problem on Linux Container.

regarding to 
```
It'll be easier to debug by running glxinfo with glxgears from mesa-utils, if 'gears' are OK then n64 should work as well.

Oh, wow! WSL2 can work in direct mode:
```
I'm not totally get this point. Are you talking about running N64 in window environment with Ubuntu?

**Comment by sergystepanov** [comment]
Yes, X Window, I mean one possible scenario that will help with OpenGL debugging for him if you are going to do so.
As always, there is no mention of his run environment, maybe he's willing to run it on a desktop.

**Comment by giongto35** [comment]
@ravelab can I know if you are running on a cloud server or on your desktop machine?

**Comment by sergystepanov** [comment]
Yay! In a meantime I made it run on WSL2 Ubuntu with Windows X Server forwarding. It runs with xvfb also (with 90% CPU utilization (:L )

![d34](https://user-images.githubusercontent.com/846874/93122558-5e5c6c80-f6cf-11ea-958a-c6b3468794bb.gif)

**Comment by ravelab** [comment]
> @ravelab can I know if you are running on a cloud server or on your desktop machine?

cloud server, with no GPU

**Comment by sergystepanov** [comment]
@giongto35, take a look at the PR.
It might be a good idea to add something into the README about minimal X Server config regarding OpenGL cores.

**Comment by sergystepanov** [comment]
@ravelab, have you tried xvfb-based (hack) approach in your fork? Is it working? Will it be enough for your purposes? (:

**Comment by sergystepanov** [comment]
@giongto35, I tested shared display (what I wrote additionally in the merged PR to you) and it's working.
If you want, you can try, test and update docs / Docker scripts.
```
xvfb :99 &
export DISPLAY=:99
```

**Comment by ravelab** [comment]
@sergystepanov thanks for the PR. I pull the latest of git@github.com:giongto35/cloud-game.git, I'm not getting "no available video device", but I'm getting black screen for the streamed video. I tried changing docker-compose.yml to - DISPLAY=:99, but still not working. Am I missing something? Thanks

**Comment by sergystepanov** [comment]
@ravelab, could you print your `worker` log after n64 game is opened?
Also, could you try these:
```
xvfb :99 &
export DISPLAY=:99
export MESA_GL_VERSION_OVERRIDE=3.3COMPAT
```

**Comment by ravelab** [comment]
the docker-compose works!

**Comment by sergystepanov** [comment]
Cool. Seems that an OpenGL compatibility profile was needed as well.
And for a desktop system like Ubuntu, it's enough to export local display `export DISPLAY=:0`, I think.
