### ISSUE TITLE
SSL cert problem with cloudretro EU mirror

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#235]
Doesn't work with ajax-requests, some problem with certs, my guess.
More precisely, the Let's Encrypt cert is expired a month ago. Broken Certbot auto-renewing?
```
GET https://eu.cloudretro.io/echo?_=1601727709666 net::ERR_CERT_DATE_INVALID
```

**Comment by giongto35** [comment]
oh, it indeed failed. I restarted the machine and it works. 
I should investigate the issue before doing that. =.= so inexperienced. I think it's the cert is expired.
