### ISSUE TITLE
No game list

### ISSUE THREAD

**Issue by sharicov** [giongto35/cloud-game#238]
Game list (roms) not available in docker
Adding rom manually to /usr/local/share/cloud-game/assets/games in the dock doesn't help

**Comment by sergystepanov** [comment]
What's in the logs?

**Comment by sharicov** [comment]
Where are logs located?

**Comment by sergystepanov** [comment]
Normally, you run this for the server logs:
```
docker logs cloud-game-local
```
(or what your container called)
For the client (browser) logs you can press F12 and click on the "Console" tab then reload the app page to see what it prints out.
