### ISSUE TITLE
Game Persistent

### ISSUE THREAD

**Issue by cadeath** [giongto35/cloud-game#239]
Is it possible to load previews games? I refreshed my browser and my game is gone. 

Thanks

**Comment by sergystepanov** [comment]
Yes, it's possible. There is a button "Share" that can copy a link for the room with a game you run. If you (re)open the room by this link, then it loads it from the last save you make. And the app stores game states in the `{home}/{user}/.cr/save` directory where you can look up your old rooms and games to try to restore.

**Comment by cadeath** [comment]
> Yes, it's possible. There is a button "Share" that can copy a link for the room with a game you run. If you (re)open the room by this link (paste it), then it loads the game in the room from the last save you make (one room -- one game). And the app stores game states in the `{home}/{user}/.cr/save` directory where you can look up your old rooms and games to try to restore if you need them.

Thank you for your reply. However, I tested a Docker and Pokemon Sapphire but when I loaded the shared link, it restarted and no saved file.

**Comment by sergystepanov** [comment]
@cadeath, did you save the game with the cloud-game save button? And also it should make an autosave when you press the quit button as well.

**Comment by giongto35** [comment]
hmm, I just retested it on cloudretro.io and it doesn't work anymore. Seems like the feature is broken....

**Comment by sergystepanov** [comment]
If you save your game first it works. That how it worked for me (I thought that was a feature).
Something with the first ROM save on room close then.

**Comment by sergystepanov** [comment]
@cadeath, could you try now with the latest master fixes? Click "Share" and try to use this link.

**Comment by giongto35** [comment]
I forgot to deploy to prod today, so he can either check if it's work on master on prod.
@sergystepanov  I think his opinion is that if the person is playing a game, we should make it persistent, if the user refresh, they still see the same game. Something like local storage can help. This feature will be nice to have btw.

**Comment by sergystepanov** [comment]
@giongto35, sure, it'd be nice to have, but I immediately see a dozen of corner cases, without even taking into account the immense refactoring effort it would require. We could call this feature "resume playing". And with the current multiplayer support, I can't imagine how it would work 🙄.

**Comment by cadeath** [comment]
> @cadeath, could you try now with the latest master fixes? Click "Share" and try to use this link.

thank you for the support. I will check the new fix and rebuild my container.

**Comment by cadeath** [comment]
After I pull the master, here are the steps I executed on the webapp.

1. I load the pokemon
2. enter name
3. save game
4. Click "save" button on the GUI
5. Click "share" button on the GUI
6. Click "quit" button on the GUI
7. paste the copied URL on the address bar (the one copied after clicking share)
8. It loaded on the same state.

I acknowledged that the "Share" button is now fixed, but can we have a reset button to restart the game only? In pokemon, there is this mystery gift that only be activated on the main screen. The "continue" menu on the main screen is also used to load Game Save.

Thank you guys

PS
You are all great, this repo is awesome!

**Comment by sergystepanov** [comment]
@giongto35, is it possible to add reset without destroying erm... user experience with shared multiplayer games including cloud-retro.io? I thought before about the allowance of "dangerous" emulator functionality in the multiplayer (save+load too), maybe, some kind of basic autorization+autehntification system is the right direction? The main idea is a party leader who could do admin stuff in the game rooms auto-assigned at the moment of room creation. (no idea how to transfer these privileges from user to user). Have you thought about that? Any simple solutions?

**Comment by giongto35** [comment]
@sergystepanov 
Yes, you correctly raised my concern about the reset button that can ruin collaborative game. I faced it with the demo Pokemon Emerald when it keeps getting restart. 
Maybe we have a flag for each game. If the game is shared with more than two different sessions, the game is converted to "community" game; and reset is not allowed.
