### ISSUE TITLE
About translation contribute

### ISSUE THREAD

**Issue by bnk159hair** [giongto35/cloud-game#246]
Hello, we are Korean university students. This project is an area we are interested in, so we would like to contribute.
We want to contribute through the Korean translation of the project. Is it okay to contribute?

**Comment by sergystepanov** [comment]
Hello!

Of course, all contributions are welcome. Feel free to contribute in any form however you see fit.

**Comment by giongto35** [comment]
@bnk159hair Hi, It's really nice to see your interest in the project. What kind of translation do you want to contribute? I think it will be hard to localize the game but I'm really welcome for translation on readme and documentation.
