### ISSUE TITLE
Add Libretro core manager module

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#248]
The basic idea is to let workers manage their core list instead of keeping each os/arch core library combination (nix, osx, win, arm) in the repo, cluttering the source.
A proposed solution:

- [x] add configuration params to workers which will describe a list of supported Libretro cores;
- [x] add manager module to workers that allow downloading and persistence of cores according to the config and runtime OS/ARCH info;
- (optionally) add the ability for cascade cores update from the coordinator;
- (optionally) create a separate mirror repository for keeping a selected list of cores from the official Libretro repo;
- [x] remove Libretro cores from the repository.

TBD.

**Comment by giongto35** [comment]
oh it's really nice. Where will we download the core, is it from nightly build?

**Comment by sergystepanov** [comment]
@giongto35, yes, nightly builds, as far as I know, it's the only place with Libretro cores. As a safety measure (if it will be down), I'll consider making a partial mirror of their nightly repo which will be auto-generated and updated with Github CI (Actions), maybe.

(I really want to implement a p2p mesh from the workers allowing them to download cores from each other, but it's, probably, hard to do (: )
