### ISSUE TITLE
Got black screen for the streamed video

### ISSUE THREAD

**Issue by hwwxj** [giongto35/cloud-game#252]
Is the docker necessary to run the game? 
I just tried to run the game in the local server without docker,  now I can hear the audio from browser, but no video there, just a black screen. BTW, I can still control the game according to the audio.
and I also find that 
the data after    coreVideoRefresh->ReadFramebuffer->ReadPixels   is filled with zero,  seems there is no images in framebuffer.

func ReadFramebuffer(bytes int, w int, h int) []byte {
	data := make([]byte, bytes)
	gl.BindFramebuffer(gl.FRAMEBUFFER, opt.fbo)
	gl.ReadPixels(0, 0, int32(w), int32(h), opt.pixType, opt.pixFormat, gl.Ptr(&data[0]))
	log.Printf("ReadPixels data is %v.", data)
	gl.BindFramebuffer(gl.FRAMEBUFFER, 0)
	return data
}

Is this caused by not using the docker?

the log is shown below：

I1225 19:16:11.005479   13873 room.go:286] Start WebRTC session
I1225 19:16:11.005498   13873 room.go:158] Check  /root/.cr/save/3f1303b86e2a31f9___FIFA99.dat  on online storage :  false
I1225 19:16:11.005507   13873 room.go:425] Check if game is on cloud storage
I1225 19:16:11.005518   13873 room.go:160] Warn: Room 3f1303b86e2a31f9___FIFA99 is not in online storage, error cloud storage was not initialized
I1225 19:16:11.005525   13873 room.go:164] Room 3f1303b86e2a31f9___FIFA99 started. GameName: FIFA99, WithGame: false
I1225 19:16:11.005556   13872 browser.go:39] Browser e0cc4f6f-b603-4e6a-8fd0-860e76d55fc3] Received room response from browser: 3f1303b86e2a31f9___FIFA99
I1225 19:16:11.005594   13872 worker.go:49] Coordinator: Received registerRoom room 3f1303b86e2a31f9___FIFA99 from worker f892b821-1d68-4a73-a107-8c6e4b659616
I1225 19:16:11.005610   13872 worker.go:51] Coordinator: Current room list is: map[3f1303b86e2a31f9___FIFA99:f892b821-1d68-4a73-a107-8c6e4b659616]
I1225 19:16:11.009928   13873 nanoarch.go:254] [Log] [Libretro] Initialization...
I1225 19:16:11.010455   13873 nanoarch.go:487] Libretro API version: 1
I1225 19:16:11.010484   13873 nanoarch.go:518] ROM size: 16777216
I1225 19:16:11.010494   13873 nanoarch.go:532]   library_name: Mupen64Plus-Next OpenGL
I1225 19:16:11.010502   13873 nanoarch.go:533]   library_version: 2.0.5 f68044f
I1225 19:16:11.010512   13873 nanoarch.go:534]   valid_extensions: n64|v64|z64|bin|u1
I1225 19:16:11.010519   13873 nanoarch.go:535]   need_fullpath: false
I1225 19:16:11.010524   13873 nanoarch.go:536]   block_extract: false
I1225 19:16:11.039622   13873 nanoarch.go:254] [Log] [Libretro] Loading the game...
I1225 19:16:11.039795   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-rdp-plugin value:gliden64
I1225 19:16:11.039813   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-rsp-plugin value:hle
I1225 19:16:11.039822   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-BilinearMode value:standard
I1225 19:16:11.039831   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-FXAA value:0
I1225 19:16:11.039840   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-FrameDuping value:False
I1225 19:16:11.039855   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-Framerate value:Original
I1225 19:16:11.039865   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-virefresh value:Auto
I1225 19:16:11.039875   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-NoiseEmulation value:True
I1225 19:16:11.039883   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableLODEmulation value:True
I1225 19:16:11.039887   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableFBEmulation value:True
I1225 19:16:11.039892   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableCopyColorToRDRAM value:Off
I1225 19:16:11.039902   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableCopyDepthToRDRAM value:Software
I1225 19:16:11.039914   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableHWLighting value:False
I1225 19:16:11.039922   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-CorrectTexrectCoords value:Off
I1225 19:16:11.039930   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-BackgroundMode value:OnePiece
I1225 19:16:11.039938   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableNativeResTexrects value:Disabled
I1225 19:16:11.039942   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txFilterMode value:None
I1225 19:16:11.039947   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txEnhancementMode value:None
I1225 19:16:11.039954   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txFilterIgnoreBG value:True
I1225 19:16:11.039969   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txHiresEnable value:False
I1225 19:16:11.039977   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txCacheCompression value:True
I1225 19:16:11.039984   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-txHiresFullAlphaChannel value:False
I1225 19:16:11.039990   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-MaxTxCacheSize value:8000
I1225 19:16:11.039996   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableLegacyBlending value:True
I1225 19:16:11.040003   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableFragmentDepthWrite value:False
I1225 19:16:11.040009   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableShadersStorage value:True
I1225 19:16:11.040015   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableTextureCache value:True
I1225 19:16:11.040024   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableEnhancedTextureStorage value:False
I1225 19:16:11.040030   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableEnhancedHighResStorage value:False
I1225 19:16:11.040037   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-cpucore value:dynamic_recompiler
I1225 19:16:11.040046   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-aspect value:4:3
I1225 19:16:11.040053   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-43screensize value:320x240
I1225 19:16:11.040068   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-astick-deadzone value:15
I1225 19:16:11.040075   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-astick-sensitivity value:100
I1225 19:16:11.040082   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-CountPerOp value:0
I1225 19:16:11.040089   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-r-cbutton value:C1
I1225 19:16:11.040095   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-l-cbutton value:C2
I1225 19:16:11.040103   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-d-cbutton value:C3
I1225 19:16:11.040110   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-u-cbutton value:C4
I1225 19:16:11.040117   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-EnableOverscan value:Enabled
I1225 19:16:11.040125   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-OverscanTop value:0
I1225 19:16:11.040132   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-OverscanLeft value:0
I1225 19:16:11.040140   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-OverscanRight value:0
I1225 19:16:11.040147   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-OverscanBottom value:0
I1225 19:16:11.040154   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-alt-map value:False
I1225 19:16:11.040162   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-ForceDisableExtraMem value:False
I1225 19:16:11.040169   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-pak1 value:memory
I1225 19:16:11.040177   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-pak2 value:none
I1225 19:16:11.040184   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-pak3 value:none
I1225 19:16:11.040192   13873 nanoarch.go:315] [Env]: get variable: key:mupen64plus-pak4 value:none
I1225 19:16:11.048578   13873 nanoarch.go:254] [Log] mupen64plus: Using full mem base
I1225 19:16:11.053382   13873 nanoarch.go:254] [Log] mupen64plus: [EmuThread] M64CMD_ROM_OPEN
I1225 19:16:11.088787   13873 nanoarch.go:254] [Log] mupen64plus: Goodname: FIFA 99 (U) [!]
I1225 19:16:11.088800   13873 nanoarch.go:254] [Log] mupen64plus: Name: FIFA 99
I1225 19:16:11.088810   13873 nanoarch.go:254] [Log] mupen64plus: MD5: 148DE3073727B9FD156F10AFADD46864
I1225 19:16:11.088816   13873 nanoarch.go:254] [Log] mupen64plus: CRC: 7613A630 3ED696F3
I1225 19:16:11.088822   13873 nanoarch.go:254] [Log] mupen64plus: Imagetype: .z64 (native)
I1225 19:16:11.088829   13873 nanoarch.go:254] [Log] mupen64plus: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
I1225 19:16:11.088836   13873 nanoarch.go:254] [Log] mupen64plus: ClockRate = F
I1225 19:16:11.088840   13873 nanoarch.go:254] [Log] mupen64plus: Version: 1444
I1225 19:16:11.088847   13873 nanoarch.go:254] [Log] mupen64plus: Manufacturer: Nintendo
I1225 19:16:11.088855   13873 nanoarch.go:254] [Log] mupen64plus: Cartridge_ID: 4639
I1225 19:16:11.088862   13873 nanoarch.go:254] [Log] mupen64plus: Country: USA
I1225 19:16:11.088869   13873 nanoarch.go:254] [Log] mupen64plus: PC = 80000400
I1225 19:16:11.088876   13873 nanoarch.go:254] [Log] mupen64plus: Save type: 5
I1225 19:16:11.089405   13873 nanoarch.go:254] [Log] mupen64plus: [EmuThread] M64CMD_ROM_GET_HEADER
I1225 19:16:11.089418   13873 nanoarch.go:572] -----------------------------------
I1225 19:16:11.089425   13873 nanoarch.go:573] ---  Core audio and video info  ---
I1225 19:16:11.089431   13873 nanoarch.go:574] -----------------------------------
I1225 19:16:11.089441   13873 nanoarch.go:575]   Frame: 320x240 (320x240)
I1225 19:16:11.089452   13873 nanoarch.go:578]   AR:    1.3333333730697632
I1225 19:16:11.089472   13873 nanoarch.go:579]   FPS:   60
I1225 19:16:11.089478   13873 nanoarch.go:580]   Audio: 44100Hz
I1225 19:16:11.089486   13873 nanoarch.go:581] -----------------------------------
I1225 19:16:11.089610   13873 sdl.go:36] [SDL] [OpenGL] initialization...
I1225 19:16:16.773614   13873 sdl.go:48] [OpenGL] CONTEXT_PROFILE_CORE
I1225 19:16:17.367371   13873 sdl.go:109]  [SDL] GLCreateContext = 0x7fab6002a0f0
I1225 19:16:17.370357   13873 opengl.go:150] [OpenGL] Version: 3.0 Mesa 18.0.5
I1225 19:16:17.370371   13873 opengl.go:151] [OpenGL] Vendor: VMware, Inc.
I1225 19:16:17.370381   13873 opengl.go:155] [OpenGL] Renderer: llvmpipe (LLVM 6.0, 256 bits)
I1225 19:16:17.370388   13873 opengl.go:156] [OpenGL] GLSL Version: 1.30
I1225 19:16:17.371189   13873 nanoarch.go:254] [Log] mupen64plus: context_reset()
plugin_start_gfx
I1225 19:16:17.373065   13873 room.go:196] Viewport custom size is disabled, base size will be used instead 320x240
I1225 19:16:17.373114   13873 room.go:203] meta:  {assets/emulator/libretro/cores/mupen64plus_next_libretro assets/emulator/libretro/cores/mupen64plus_next_libretro.cfg 320 240 44100 60 320 240 1.3333333730697632 {<nil> false} true true false false}
I1225 19:16:17.373284   13873 naemulator.go:251] Error: Cannot load open /root/.cr/save/3f1303b86e2a31f9___FIFA99.dat: no such file or directory
I1225 19:16:17.373309   13873 media.go:74] Enter fan audio
I1225 19:16:17.373339   13873 media.go:134] Video Encoder:  VP8
I1225 19:16:17.390559   13873 nanoarch.go:254] [Log] mupen64plus: [EmuThread] M64CMD_EXECUTE
I1225 19:16:17.394977   13873 nanoarch.go:254] [Log] mupen64plus: Game controller 0 (Standard controller) has a Memory pak plugged in
I1225 19:16:17.395003   13873 nanoarch.go:254] [Log] mupen64plus: Game controller 1 (Standard controller) has nothing plugged in
I1225 19:16:17.395020   13873 nanoarch.go:254] [Log] mupen64plus: Game controller 2 (Standard controller) has nothing plugged in
I1225 19:16:17.395033   13873 nanoarch.go:254] [Log] mupen64plus: Game controller 3 (Standard controller) has nothing plugged in
I1225 19:16:17.395663   13873 nanoarch.go:254] [Log] mupen64plus: Using CIC type X102
I1225 19:16:17.460332   13873 nanoarch.go:254] [Log] mupen64plus: Initializing 4 RDRAM modules for a total of 8 MB
I1225 19:16:17.463911   13873 nanoarch.go:254] [Log] mupen64plus: Starting R4300 emulator: Dynamic Recompiler
I1225 19:16:17.467916   13873 nanoarch.go:254] [Log] mupen64plus: Init new dynarec

（no more logs）

**Comment by sergystepanov** [comment]
No, Docker is not mandatory. If you look closely into the script:
https://github.com/giongto35/cloud-game/blob/ef56695af191d6df36885842f7100af777e93e97/docker-compose.yml#L9-L14

there is an environment variable for the MESA OpenGL driver `MESA_GL_VERSION_OVERRIDE` which is a hack for old GPUs actually, so try to set it in your system like that:
```
export MESA_GL_VERSION_OVERRIDE=3.3
```
or
```
export MESA_GL_VERSION_OVERRIDE=3.3COMPAT
```

**Comment by hwwxj** [comment]
it works！ thanks！
