### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#256]
It is time to get your hands dirty and try to run this app as a k8s cluster.

TBD...

### Goals
- You are not Google
- Easy deployment
- Scaleability (scale-out, as well as downscale)
- CDN

### Literature

1. Orchestrating GPU-accelerated streaming apps using WebRTC ([link](https://cloud.google.com/solutions/orchestrating-gpu-accelerated-streaming-apps-using-webrtc))
2. GPU-accelerated streaming using WebRTC ([link](https://cloud.google.com/solutions/gpu-accelerated-streaming-using-webrtc))
3. Designing Distributed Systems: Patterns and Paradigms for Scalable, Reliable Services. — Brendan Burns, 2018 ([Amazon](https://www.amazon.com/Designing-Distributed-Systems-Patterns-Paradigms/dp/1491983647))
4. Kubernetes in Action (1st Edition) — Marko Luksa, 2018 ([Manning](https://www.manning.com/books/kubernetes-in-action))

**Comment by giongto35** [comment]
OMG, your references are so good. I will try to read and summarize it as well!!
