### ISSUE TITLE
How to change ports to another?

### ISSUE THREAD

**Issue by Karplyak** [giongto35/cloud-game#260]
Ports 9000 and 8000 conflicts with portainer.

**Comment by sergystepanov** [comment]
There are 2.5 ways to change them:
1. In the config file `cloud-game/configs/config.yaml`
coordinator -> server -> port
https://github.com/giongto35/cloud-game/blob/132c067cc129a122283662697bc298cf27308a41/configs/config.yaml#L39-L40
coordinator -> publicDomain (port should be from the param up above)
https://github.com/giongto35/cloud-game/blob/132c067cc129a122283662697bc298cf27308a41/configs/config.yaml#L34-L35
worker -> network -> coordinatorAddress (port should be from the param up above)
https://github.com/giongto35/cloud-game/blob/132c067cc129a122283662697bc298cf27308a41/configs/config.yaml#L45-L48
worker -> server -> port
https://github.com/giongto35/cloud-game/blob/132c067cc129a122283662697bc298cf27308a41/configs/config.yaml#L58-L59

2. Same but with the environment variables. Every param in the config file can be overridden in the system or Docker config as `CLOUD_GAME_{PARAM}_{SUBPARAM}`, i.e.:
```
CLOUD_GAME_COORDINATOR_SERVER_PORT=9999
CLOUD_GAME_COORDINATOR_PUBLICDOMAIN=http://localhost:9999
...
etc.
```

3. Both apps (coordinator and worker) have some runtime params:
```
worker --coordinatorhost localhost:8001 --port=9999
coordinator --port=8001
```

Param override chain is `app config file <- environment variables <- app runtime flags`.
Hope, this helps.

**Comment by Karplyak** [comment]
I tried to change ports in files, but platform don`t work. Sile is loadeded, but it don`t show any game.
In browser conlole it white this:
[rtcp] got ice candidate: {"candidate":"candidate:842163049 1 udp 1677729535 178.212.111.210 61915 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag VUuG network-cost 999","sdpMid":"0","sdpMLineIndex":0}
log.js?v=5:10 [rtcp] ice gathering completed
log.js?v=5:10 [rtcp] <- iceConnectionState: disconnected
log.js?v=5:10 [rtcp] disconnected...

From docker log:
I0113 13:10:23.318246       7 internalhandlers.go:108] Received remote Ice Candidate from browser
I0113 13:10:23.318822       7 webrtc.go:276] Decoded Ice: candidate:842163049 1 udp 1677729535 170.121.112.215 61915 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag VUuG network-cost 999
I0113 13:10:23.319249       7 webrtc.go:284] Add Ice Candidate: candidate:842163049 1 udp 1677729535 170.121.112.215 61915 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag VUuG network-cost 999
I0113 13:10:53.413756       7 webrtc.go:177] ICE Connection State has changed: failed/

P.S. Sorry about my english.

**Comment by sergystepanov** [comment]
@Karplyak, тогда, может, на русском, если Вам так будет удобнее?
Насколько я вижу, порты 8000 и 9000 получилось переопределить, теперь проблема с WebRTC.
Могу я узнать как Вы запускаете cloud-retro? Не с помощью Docker? Какая система (Windows, Linux)? Можно посмотреть Ваш файл конфигурации с правками?

**Comment by Karplyak** [comment]
Мне лучше общаться на украинском.
Я запускаю cloud-retro с помощью docker на системе Linux. 
Ссылка на правки:

https://github.com/Karplyak/cloud-game

**Comment by sergystepanov** [comment]
К сожалению, среди известных мне 4 языков немає української мови. Подумал, что русский мы должны знать оба с вероятностью 98%.
Думаю, что нужно просто раскомментировать # network_mode: "host" в Compose.

**Comment by Karplyak** [comment]
Раскомментирование # network_mode: "host" в Compose помогло. CLOUD GAME работает, но эмуляции mame уже нет. Спасибо за все.

**Comment by sergystepanov** [comment]
@Karplyak, рад помочь. А НеоГео я убрал из репозитория, потому что биосы запрещено распространять, а без romset оно не запустит игры.
Если что, то вот [коммит](https://github.com/giongto35/cloud-game/commit/a2b0a44a8dfb3a2df590a19f28cbd476b6eb6030), можно вручную скачать оттуда и восстановить конфиг.
