### ISSUE TITLE
Linear interpolation for the game screen

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#263]
It is possible to get rid of picture smoothing with video mirroring onto a preconfigured canvas (`image-rendering: pixelated`).
Could be helpful in the future for some client display scaling modes (integer scaling, smoothed, etc.)

#### Comparison
Despite transcoding artifacts, it has the nearest-neighbor scaling on the left and the default bilinear filter on the right. The original size of the game frame is 256x240 and it was scaled with an x2 factor in the browser.

https://user-images.githubusercontent.com/846874/104768637-0c138100-577f-11eb-9935-742cf96e1d4e.mov

**Comment by giongto35** [comment]
"video mirroring onto a preconfigured canvas":  Do you mean there is a CSS option for scaling on front-end right (both nearest neighbor and billinear is supported)
?

**Comment by sergystepanov** [comment]
It's working like [that](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas). Yes, right now I could find just 2.5 options for CSS [scaling](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).
The problem is that by default HTML5 <video> element uses a bilinear filter when the video container is being stretched and there is no option to change it there. If we would want to use Nearest algo on the server in that case it would be not-blurred just for the original game frame size. You might say Nearest Neighbor is a trash algo anyway with all these jitterings, jagged edges (going back to Earthbound scaling example issues (:) but in the form of [Integer scaling](https://tanalin.com/en/articles/integer-scaling/) it's very pleasant, compared to blur.

**Comment by sergystepanov** [comment]
It's working like [that](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas). Yes, right now I could find just 2.5 options for CSS [scaling](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).
The problem is that by default HTML5 <video> element uses a bilinear filter when the video container is being stretched and there is no option to change it there. If we would want to use Nearest algo on the server in that case it would be not-blurred just for the original game frame size. You might say Nearest Neighbor is a trash algo anyway with all these jitterings, jagged edges (going back to Earthbound scaling example issues (:) but in the form of [Integer scaling](https://tanalin.com/en/articles/integer-scaling/) it's very pleasant, compared to blur.

**Comment by giongto35** [comment]
he, so life is easy. Just scale down everything before scale-up. Have you tested the optimal screen size to have ~30FPS?

**Comment by sergystepanov** [comment]
> he, so life is easy. Just scale down everything before scale-up. Have you tested the optimal screen size to have ~30FPS?

I must say, it won't work for um... graphic-intensive consoles, starting from N64 and beyond. For primitive graphics and a limited color palette, we can scale-down it quite a lot and restretch it wherever.
I've not tested performance, first, we need a deterministic reproducible environment or a baseline system config. Since everything is CPU driven it will be CPU+RAM. Something like lo, med, hi Amazon [instances](https://aws.amazon.com/ru/ec2/instance-types/t3/).
As is, I can get 60 fps in any not 3D emulator with default frame size x2, up until N64 where I have to scale it down from defaults times two (:

**Comment by sergystepanov** [comment]
One more thing I'm planning to try in the future is an AI-based upscale like Nvidia DLSS. When we have a proper GStreamer AV pipeline because it's a pain to do manually ((post-)processing queue).

**Comment by giongto35** [comment]
Yes, we haven't push the project to the limit that we can apply GPU for streaming.
The AI-based upscale is mentioned a lot of time, it's the future of video call as well. I just don't know if it's really possible, the upscale AI model has to perform at around 100fps on front-end. I'm really curious and would like to know your experiment result as well .

**Comment by giongto35** [comment]
ah. When you mention: "proper GStreamer AV pipeline", what will be the change in our infrastructure to achieve that?

**Comment by sergystepanov** [comment]
I don't know yet, how it works with Go. First I would integrate AV-encoders instead of existing C-wrappers which requires no changes to our infrastructure. It's something like a [push-poll](https://github.com/notedit/gstreamer-go) on the pipeline.
