### ISSUE TITLE
Savefile for PSX memory card?

### ISSUE THREAD

**Issue by Lightbass** [giongto35/cloud-game#270]
Is it possible to do global savefile memory card for each game?
As i can see savefiles for memory card not save on server.

**Comment by sergystepanov** [comment]
Right now it's not possible. Only savestates are supported.

**Comment by Lightbass** [comment]
Savestates may break the game.
It's a pity

**Comment by sergystepanov** [comment]
@Lightbass, я попробовал добавить сохранение SRAM (Memory Stick) в #273. И, кажется, работает, только есть ряд проблем: 

- c HLE-биос у меня сохранения не заработали нормально, нужно закидывать оригинальный биос сюда `cloud-game\pkg\emulator\libretro\system`;
- у Libretro нет возможности сообщить, когда в игре сохраняют что-то на карту памяти, потому у всех карты сохраняются при закрытии приложения и постоянно каждые n минут. Я сделал только при выходе и при нажатии сохранить в cloud-retro;
- в cloud-retro нет кнопки сбросить, из-за чего в некоторых играх будет сложно загрузиться с карты из главного меню. Придётся руками копировать .srm файлы + принудительно вызывать загрузку состояния в cloud-retro.

В принципе, можно попробовать с правками из соответствующей ветки, но до слияния в основную мне ещё нужно долго и нудно тестировать, ещё подумать над проблемами выше.

https://user-images.githubusercontent.com/846874/106333400-a0aad280-6299-11eb-8458-1af7a3b651bc.mov
