### ISSUE TITLE
YCbCr corrections

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#286]
### Summary 
To try to correct conversion artifacts of YUV 4:2:0 images used in compressed video.

### Info
In both video encoders we use YUV 4:2:0 encoded frames.
YUV is a class of pixel formats used in video applications. YUV colors are represented with one "luminance" component called Y (equivalent to grey scale) and two "chrominance" components, called U (blue projection) and V (red projection) respectively.
YUV can also be referred to as YCbCr, although the terms mean slightly different things.

**Planar formats**
Planar formats use separate matrices for each of the 3 color components. In other words, there is one table of luminance pixel values, and two separate tables for the chrominance components. This segregated representation in memory of pixels is more convenient for video coding.

**YUV 4:2:0 (I420/J420/YV12)**

I420 has the luma "luminance" plane Y first, then the U chroma plane and last the V chroma plane.
The two chroma planes (blue and red projections) are sub-sampled in both the horizontal and vertical dimensions by a factor of 2. That is to say, for a 2×2 square of pixels, there are 4 Y samples but only 1 U sample and 1 V sample.
This format requires 4×8+8+8=48 bits per 4 pixels, so its depth is 12 bits per pixel.
I420 is by far the most common format.

A graphical illustration: Each letter represents one bit.

For a single I420 pixel: YYYYYYYY UU VV
For a 50-pixel I420 frame: YYYYYYYY×50 UU×50 VV×50 (or Y×8×50 U×2×50 V×2×50 for short)
For an n-pixel I420 frame: Y×8×n U×2×n V×2×n

J420
J420 is exactly like I420, but with a full range ("digital", 0-255) luma (Y) component instead of limited range ("analog", 16-240). The chroma planes are exactly the same as in I420.

YV12
YV12 is exactly like I420, but the order of the U and V planes is reversed. In the name, "YV" refers to the plane order: Y, then V (then U). "12" refers to the pixel depth: 12-bits per pixel as for I420.

**Color ranges**
[BT.601 studio (TV), full (PC) swing](https://en.wikipedia.org/wiki/YUV#Numerical_approximations)

Prior to the development of fast SIMD floating-point processors, most digital implementations of RGB → Y′UV used integer math, in particular fixed-point approximations. Approximation means that the precision of the used numbers is limited in favor of improved computation speeds.

Y′ values are conventionally shifted and scaled to the range [16, 235] (referred to as studio swing or "TV levels") rather than using the full range of [0, 255] (referred to as full swing or "PC levels"). The value 235 accommodates a maximal black-to-white overshoot of 255 − 235 = 20, or 20 / (235 − 16) = 9.1%, which is slightly larger than the theoretical maximal overshoot (Gibbs phenomenon) of about 8.9% of the maximal step. The toe-room is smaller, allowing only 16 / 219 = 7.3% overshoot, which is less than the theoretical maximal overshoot of 8.9%. This is why 16 is added to Y′ and why the Y′ coefficients in the basic transform sum to 220 instead of 255. U and V values, which may be positive or negative, are summed with 128 to make them always positive, giving a studio range of 16–240 for U and V. (These ranges are important in video editing and production since using the wrong range will result either in an image with "clipped" blacks and whites, or a low-contrast image.)

BT.601 (studio/full) swing. For getting the traditional "studio-swing" 8-bit representation of Y′UV for SDTV/BT.601 the following operations can be used:
1. Basic transform from 8-bit RGB to 16-bit values (Y′: unsigned, U/V: signed, matrix values got rounded so that the later-on desired Y′ range of [16..235] and U/V range of [16..240] is reached):
  ```
  Y'  |  66 129  25 | R |
  U = | -38 -74 112 | G |
  V   | 112 -94 -18 | B |
  ```
2. Scale down (">>8") to 8 bits with rounding ("+128") (Y′: unsigned, U/V: signed):
  ```
  Yt'= (Y'+ 128) >> 8
  Ut = (U + 128) >> 8
  Vt = (V + 128) >> 8
  ```
3. Add an offset to the values to eliminate any negative values (all results are 8-bit unsigned):
  ```
  Yu'= Yt' + 16
  Uu = Ut + 128
  Vu = Vt + 128
  ```
Full swing for BT.601. For getting a "full-swing" 8-bit representation of Y′UV for SDTV/BT.601 can be used with the same steps except for use of different weights on the first step.

> Our implementation uses studio swing integer math without SIMD. Generally speaking, `full swing` has the advantage of more picture information with less color banding or quantization errors but in our case, it's easier to stick with the studio range because VP8 codec doesn't support the full range (VP9 does) and we would have to implement both algorithms with some conditional switch on each codec.
> It is now accepted that SD content uses the BT.601 colorspace and HD uses BT.709.

### The problem
> We have YUV artifacts after RGB image conversion. So either YUV 4:2:0 converter is trash by itself or 4:2:0 is not meant for small images. 

<details>
  <summary>RGB/YUV (edited) image comparison...</summary>
  
![image](https://user-images.githubusercontent.com/846874/108930110-59c0ba80-7656-11eb-8f38-fec224ad2996.png)
</details>

<details>
  <summary>RGB/YUV raw image comparison...</summary>
  
![download (7)](https://user-images.githubusercontent.com/846874/108928908-06e60380-7654-11eb-95ee-acf9aaf516d3.png) ![download (5)](https://user-images.githubusercontent.com/846874/108928909-08173080-7654-11eb-8414-dbdc85d5c221.png)
</details>
<details>
  <summary>VP8 encoded clip...</summary>
  
![feature007](https://user-images.githubusercontent.com/846874/108913657-510ebb00-763b-11eb-8035-3eea7f907d50.gif)
</details>

<details>
  <summary>Direct RGB/YUV UV (4:4:4/4:2:0) comparison...</summary>

![image](https://user-images.githubusercontent.com/846874/109334679-15aa0180-7872-11eb-9409-ee9503efe910.png)
![image](https://user-images.githubusercontent.com/846874/109334859-51dd6200-7872-11eb-8a1b-20062a5ea31f.png)

![image](https://user-images.githubusercontent.com/846874/109335220-cfa16d80-7872-11eb-9170-7fccb05f6715.png)
![image](https://user-images.githubusercontent.com/846874/109335085-9a951b00-7872-11eb-98c4-4a09849bc233.png)
</details>

### Solutions

> 1. Since blue and red channels are very crippled it's possible just to upscale original frames by a factor of 2 or more.
>
> 2. Rework the existing YUV-converter in a way that it could interpolate chrominance values more precisely.
> In the [current algorithm](https://stackoverflow.com/a/9467305), we calculate a single chroma value for all 2x2 RGB/luma values just based on the first pixel:
> ```
> XO  X   XO  X
> 
> X   X   X   X
> ```
> This will lead to aliasing and color artifacts, instead, it is better to calculate a new chroma value for the average color between these 4 RGB pixels:
> ```
> X   X   X   X
>   O       O
> X   X   X   X
> ```
>
> 3. Try to use YUV 422 or 444 if codecs can support them. These formats should have fewer or no chrominance conversion artifacts but will reduce compression effectiveness as well as limit WebRTC client support.

### Implementation notes

The first solution can be implemented just by changing one configuration param:
https://github.com/giongto35/cloud-game/blob/90943f0cc4b916ccb959b20b32f755d231b64a24/configs/config.yaml#L64-L66
One disadvantage of this method is that change will scale output images for every emulator which could be heavy on the performance side.

The second one is implemented in the new PR. Added optimized multithreaded YUV converter with 2x2 chroma color estimation.
Try [sqrt](https://sighack.com/post/averaging-rgb-colors-the-right-way#:~:text=The%20typical%20approach%20to%20averaging,color%2C%20sum%20their%20squares%20instead.) -- slow.

The third solution seems to be hard to implement for both encoders because of difficulties in support of these image compression types.

#### Literature
001 / VideoLan Wiki ([site](https://wiki.videolan.org/YUV))
002 / Wikipedia YCbCr ([site](https://en.wikipedia.org/wiki/YCbCr))

#### Tools used
001 / yuvtoolkit ([site](http://www.yuvtoolkit.com/))
002 / rawpixels.net ([site](https://rawpixels.net/))

_Originally posted by @sergystepanov in https://github.com/giongto35/cloud-game/issues/285#issuecomment-784655254_

**Comment by giongto35** [comment]
You always come with a very detailed explanation, not only to talk about the problem, but also a learning material. I learn a lot from it. Thank you very much for valuable knowledge!!!
I think you have solution in mind as well. For small resolution games, anyway will work, so you can pick any way that is comfortable to you. Maybe we can consider the way that has faster (encoding time + packet size).

**Comment by sergystepanov** [comment]
I looked at the RetroArch source, they just scale the frames for crippled chroma subsampled colorspaces: 
https://github.com/libretro/RetroArch/blob/1681872763fa37e7c03c29b66308645dbc1efe0f/record/drivers/record_ffmpeg.c#L512-L516

I didn't explain and show how this happens (: will do it a bit later. 
I'm pretty sure that YUV converter from StackOverflow is not quite right. I just wanna try to fix it and properly understand YUV conversion in general.

**Comment by sergystepanov** [comment]
Um..., @giongto35, how do we actually can iterate chroma better, as for example 4x4 RGBA image:
```
x x x x
x x x x
x x x x
x x x x
```
We need average colors from pixels with x,y coordinates: 0:0 1:0 0:1 1:1, next: 2:0 3:0 2:1 3:1, and etc.

Original algo in Go for the first pixel in every 2x2 block is something like this:
```go
width, height := 4, 4
// U size = width*height/4 = 4
// U plane
for y := 0; y < height; y += 2 {
    for x := 0; x < width; x += 2 {
        i := y*width + x
        r := -38 * int32(rgba.Pix[4*i])
        g := -74 * int32(rgba.Pix[4*i+1])
        b := 112 * int32(rgba.Pix[4*i+2])
        yuv.data[dst_u] = byte((r+g+b)>>8) + 128
        dst_u++
     }
}
```

**Comment by giongto35** [comment]
what is the better approach you are thinking of? better in term of code simplification or better in term of time complexity? I see no problem with x:y -> (x+1:y x:y+1 x+1:y+1) and average

**Comment by sergystepanov** [comment]
Here is the full code of the original ported to Go:
```go
        width, height := yuv.w, yuv.h
	dst_y := 0
	dst_u := width * height
	dst_v := width*height + (width * height / 4)

	// Y plane
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			i := y*width + x
			r := 66 * int32(rgba.Pix[4*i])
			g := 129 * int32(rgba.Pix[4*i+1])
			b := 25 * int32(rgba.Pix[4*i+2])
			yuv.data[dst_y] = byte((r+g+b)>>8) + 16
			dst_y++
		}
	}

	// U plane
	for y := 0; y < height; y += 2 {
		for x := 0; x < width; x += 2 {
			i := y*width + x
			r := -38 * int32(rgba.Pix[4*i])
			g := -74 * int32(rgba.Pix[4*i+1])
			b := 112 * int32(rgba.Pix[4*i+2])
			yuv.data[dst_u] = byte((r+g+b)>>8) + 128
			dst_u++
		}
	}

	// V plane
	for y := 0; y < height; y += 2 {
		for x := 0; x < width; x += 2 {
			i := y*width + x
			r := 112 * int32(rgba.Pix[4*i])
			g := -94 * int32(rgba.Pix[4*i+1])
			b := -18 * int32(rgba.Pix[4*i+2])
			yuv.data[dst_v] = byte((r+g+b)>>8) + 128
			dst_v++
		}
	}

	return yuv
```
Maybe you have some thoughts on its optimization, know some cool tricks with matrices?
Only the time complexity matters.
Basically, we should iterate through every single pixel in order to get luma values -- that's the first loop, two others (for some reason were separated) are for chroma where we have to add 4 x/y to an array index conversions and r1+r2+r3+r4/4, b1+b2+b3+b4/4, g1+g2+g3+g4/4 estimation. Can we use the first loop only somehow, maybe? Or is it pointless (:

(There is one optimization not strictly related to this we can skip emulator frame conversion to RGB and convert to YUV right away.)

**Comment by giongto35** [comment]
ah got your point
Yes, using only one loop can help performance even with the same time complexity ( because it's faster to access data that is neighbor to each other) , in the above code, I think something like if (y%2==0 && x % 2==0) calc_chroma() is fine.
The other thing is to avoid allocating new frame each time. keep reuse a single yuv variable. Can keep profiling to see if there is 
any new allocation in the loop
One small trick is to use bit manipulation instead of Multiplication (x4 = << 2)
---
beyond that, I don't know how to make the code faster than O(x*y)

**Comment by giongto35** [comment]
If we even look further, we can try parallel programming, divide the matrix by to 16 rectangles ( 4 x 4 ). Each rectangle will be in charge in one goroutine.

**Comment by sergystepanov** [comment]
> Ah got your point
> Yes, using only one loop can help performance even with the same time complexity ( because it's faster to access data that is neighbor to each other) , in the above code, I think something like if (y%2==0 && x % 2==0) calc_chroma() is fine.

They actually discussed [that](https://stackoverflow.com/a/9466145) and an unrolled loop was faster.

> One small trick is to use bit manipulation instead of Multiplication (x4 = << 2)
Those 2 nanoseconds gains from that come in handy (:

> Beyond that, I don't know how to make the code faster than O(x*y) :-?
I think that's the limit.

> If we even look further, we can try parallel programming, divide the matrix by to 16 rectangles ( 4 x 4 ). Each rectangle will be in charge in one goroutine.
Actually, I was planning to leave it in C but you have a good point, I'll try it in Go with 2 threads -- one for luma, one for chromas.
4x4 is going to be too much of goroutine overhead, it's more like WxH/(CPU cores)... interesting.

There is a specialized lib [libswscale](https://github.com/FFmpeg/FFmpeg/tree/master/libswscale) with assembler optimizations that can convert bgr24toyuv420p, maybe try that also...

OK, thanks for your suggestions, I'll try to implement a couple of these and get back with my profiling results (:

**Comment by sergystepanov** [comment]
Rather strange results with average chromas. It almost fixed shimmering in Mario and completely in Sushi, it's more readable on some backgrounds (1st row -- old):
![PSXYUVV01](https://user-images.githubusercontent.com/846874/109710446-bb30de00-7bae-11eb-9f23-909b32777b5b.png)
But it tone downs some colors, like text halo in Xenogears, and original cranks it up (:
![XG001](https://user-images.githubusercontent.com/846874/109712286-e87e8b80-7bb0-11eb-881d-96c331e7c93e.png)

**Comment by sergystepanov** [comment]
Performance comparison (1080p, run 20 times):
```
name   old time/op    new time/op    delta
Yuv-4    2.84ms ± 4%    4.51ms ± 1%  +58.84%  (p=0.000 n=20+17)

name   old alloc/op   new alloc/op   delta
Yuv-4     101kB ± 1%     157kB ± 2%  +55.71%  (p=0.000 n=19+18)

name   old allocs/op  new allocs/op  delta
Yuv-4     10.6k ± 1%     16.5k ± 2%  +55.73%  (p=0.000 n=19+18)
```

**Comment by sergystepanov** [comment]
Tested with simple pthreads: on HD resolutions it's 30% faster with the additional thread for chroma computation, on SD it's 20% slower probably due to thread recreation overhead. With some thread pool (prod/consume) it's possible that it will be fast in both cases but to write your own thread pool isn't that easy.

**Comment by sergystepanov** [comment]
Ended up with a multithreaded version with Go green threads. Images are sliced by the number of CPUs * 2 and here is the result (:
```
name           old time/op    new time/op    delta
TopLeft-4        1.39ms ± 1%    0.15ms ± 1%   -88.96%  (p=0.000 n=9+9)
BetweenFour-4    2.66ms ± 2%    0.26ms ± 3%   -90.40%  (p=0.000 n=9+10)
```

**Comment by giongto35** [comment]
Really nice work on optimization (y). The Go Green Thread you are mentioning is GoRoutine right?
For something like this, I expect we have a thread pool. Im assuming you are using it for your "Go green threads" right? pthread in C is raw Thread, so the creation of it Is costly in terms of creation/space but goroutine is lighter (pseudo thread). If you use thread pool in C in the right way, I think it may be faster than go version: Spawning 4 threads beforehand and each one is dedicated for a region.
Besides, you mentioned that one thread for chroma, one for others. It sounds right, have you tried it? It simplify this region cutting approach.

> But it tone downs some colors, like text halo in Xenogear
The average makes the color blur (due to averadown), so I think the result we have makes sense. Top Left Image will be sharper.

**Comment by sergystepanov** [comment]
> Really nice work on optimization (y). The Go Green Thread you are mentioning is GoRoutine right?

Yes, keep forgetting how it is called (:

> For something like this, I expect we have a thread pool. Im assuming you are using it for your "Go green threads" right? pthread in C is raw Thread, so the creation of it Is costly in terms of creation/space but goroutine is lighter (pseudo thread). If you use thread pool in C in the right way, I think it may be faster than go version: Spawning 4 threads beforehand and each one is dedicated for a region.

I thought about C thread pool but it's and SIMD a little bit over my head (: at the current knowledge of C. Hard to implement your own and I didn't want to include yet another C lib for that purpose. It works well with goroutines anyway.

> Besides, you mentioned that one thread for chroma, one for others. It sounds right, have you tried it? It simplify this region cutting approach.

Initially, I did one goroutine for luma and one for both chromas both loop over all the pixels in the image. And yes, two separate loops work significantly faster than one loop for all. Next, I tried chunk images by two rows divided between some number of goroutines, and that way it was faster like x2-3 times.
I finished my implementation you can actually look at the final code in the PRs. Gonna merge it tommorow.

> > But it tone downs some colors, like text halo in Xenogear
> 
> The average makes the color blur (due to averadown), so I think the result we have makes sense. Top Left Image will be sharper. I think we face the same issue when you did the linear scale : D

Yes, you're right, thanks for the explanation.

**Comment by giongto35** [comment]
@sergystepanov the code looks good, nice abstraction as well. 
I commented in the diff, basically we can
- spawn goroutine before processing
- perfectly async, don't make each goroutine wait for each other, push out the frame when finish
It is not necessary for the diff but I think it can help optimize more. : D

**Comment by sergystepanov** [comment]
@giongto35, I don't think it will make a noticeable difference since coroutines mapped to OS threads and they say that they are cheap, plus we spawn on each image just 2*cores coroutines. If we go further, I'm afraid, we just overload the CPU. But you have a valid point, I think. As a coding exercise, it'll be cool to do. I have some questions below.

> spawn goroutine before processing
> It also costs some goroutine creation per frame here same like thread.
> What I recommend is to do something like threadpool. You spawn goroutine up most before process any frames, each goroutine will be in charge of a predefined area.
> Then for each frame, we just notify each goroutine to process their corresponding area.

For that you will need channels, right?

> perfectly async, don't make each goroutine wait for each other, push out the frame when finish
> It is not necessary for the diff but I think it can help optimize more. : D

> After that, we can go one step further by omitting wg.Wait. We make each area is processed separately in async manner. Once a frame finishes processing, then we push out the frame
> 
> For example:
> We have a frame 4x4, we spawn 4 goroutines, each one is in charge of 2x2
> Game controller get to frame 4th
> go routine 1: 2x2 finished 3 frames
> go routine 2: 2x2 finished 2 frames
> go routine 3: 2x2 finished 1 frames
> go routine 4: 2x2 finished 3 frames
> 
> Once goroutine 3 finished, => it sends a completed first frame. and so one

I'm not quite following you on this. Could you please explain how we know if some frame is finished? A code snippet even on pseudocode will be helpful, maybe.

**Comment by giongto35** [comment]
in my mind it's like
```
process1Channel = make(chan *rect, 10)
...
process4Channel = make(chan *rect, 10)

go process(0, 0, 2, 2, process1Channel)
go process(0, 2, 2, 4, process2Channel)
go process(2, 2, 4, 2, process3Channel)
go process(2, 4, 4, 4, process4Channel)
go procedure()

func procedure() {
  for {
    area1 <- process1Channel
    area2 <- process2Channel
    area3 <- process3Channel
    area4 <- process4Channel
    frame = combine(area1, area2, area3, rea4)
   output<-frame
  }
}

```
Each channel is buffered, each time we poll each channel, if the region for that is ready.
Seems complicated but it's my idea.

**Comment by sergystepanov** [comment]
Oh, it makes sense. An interesting serialization approach. So it sequential and we will get a block on an empty channel on the receiver side. As a downside for the concurrent approach, I see that we will need to guard our input/output frames pretty carefully.
OK, thanks for explaining this to me, I'm gonna try it sometime.

**Comment by giongto35** [comment]
Yes, Thanks very much for experimenting with different ways of optimization. You have raised many interesting problems and It's nice that we both discuss and learn about it!
