### ISSUE TITLE
can't change x264 params

### ISSUE THREAD

**Issue by 50infivedays** [giongto35/cloud-game#300]
i find it strange that i can't change x264 params, when i changed it  it doesn't work
i'm on ubuntu 20.04

**Comment by sergystepanov** [comment]
If I understand you correctly, most likely you are changing the wrong config file. Make sure that the `config.yaml` file is only in one of the dirs (relative to the current dir from which you started the app): run dir, `configs` folder, `/home/{user}/.cr`. Try to change logLevel: 0 to 3, it will show some info if x264 params are changing in the console output.
Don't have any problems with Ubuntu 20.10 whatsoever.

**Comment by 50infivedays** [comment]
![image](https://user-images.githubusercontent.com/2149747/112601666-ae21aa80-8e4d-11eb-9b74-989fff2ded8d.png)

my config.yaml is just in `configs` but it appears to have problem shown above.
the program crashed

> If I understand you correctly, most likely you are changing the wrong config file. Make sure that the `config.yaml` file is only in one of the dirs (relative to the current dir from which you started the app): run dir, `configs` folder, `/home/{user}/.cr` folder. Try to change logLevel: 0 to 3, it will show some info if x264 params are changing in the console output.
> Don't have any problems with Ubuntu 20.10 whatsoever.

**Comment by sergystepanov** [comment]
So, when you change params it will crash, right? Could you show me your modified config file?

**Comment by 50infivedays** [comment]
first of all, thanks for your patience!

**Comment by sergystepanov** [comment]
That's interesting. I wrote my wrapper from the C headers of libx264 v160 and it's possible that it still incompatible with the previous version 155 but I'm pretty sure I tested it on 155. OK, Then it's probably version 155 of libx264. Could you try to install version [160](https://packages.ubuntu.com/groovy/libx264-dev) from Ubuntu 20.10/Debian Groovy, you will need dev version and just libx264 160 installed as well.
I'll try to run it on 20.04 with libx264-155 when I have time.

**Comment by 50infivedays** [comment]
> That's interesting. I wrote my wrapper from the C headers of libx264 v160 and it's possible that it still incompatible with the previous version 155 but I'm pretty sure I tested it on 155. OK, Then it's probably version 155 of libx264. Could you try to install version [160](https://packages.ubuntu.com/groovy/libx264-dev) from Ubuntu 20.10/Debian Groovy, you will need dev version and just libx264 160 installed as well.
> I'll try to run it on 20.04 with libx264-155 when I have time.

yes , i'm using 155
ok, i'll try , and i'm still interested at your test on 155. please tell me if you find the reason

**Comment by sergystepanov** [comment]
I've successfully reproduced this "bug" with v155. If you are interested in the main reason for these crashes, I'll say that's because since version 158 (or so) they changed their structure for codec params by adding new param avcintra_flavor. As you can imagine if you use a new struct with the old encoder it will change completely different fields. In our case with log_level it writes some garbage into param that should take a string (pointer) containing file path for YUV dump file.

To fix this I have atm only an ugly solution, 2 copies of param structs switched depending on the installed codec version.
I'd like to solve this a bit better (:

![image](https://user-images.githubusercontent.com/846874/112622662-65152a80-8e3c-11eb-94ea-29fc90bd7de8.png)

Example of quality change.
```
-- crf: 17 ---
x264 [info]: frame I:8     Avg QP:17.50  size: 12265
x264 [info]: frame P:1946  Avg QP:21.02  size:  1802
x264 [info]: mb I  I16..4: 19.3%  0.0% 80.7%
x264 [info]: mb P  I16..4:  1.4%  0.0%  0.5%  P16..4: 29.9% 11.9%  7.7%  0.0%  0.0%    skip:48.6%
x264 [info]: coded y,uvDC,uvAC intra: 31.2% 56.2% 44.4% inter: 13.7% 30.5% 25.8%
x264 [info]: i16 v,h,dc,p: 84%  8%  8%  0%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 45% 12% 23%  3%  3%  4%  4%  3%  3%
x264 [info]: i8c dc,h,v,p: 44%  8% 48%  0%
x264 [info]: Weighted P-Frames: Y:0.8% UV:0.6%
x264 [info]: kb/s:369.02

--- crf: 3 ---
x264 [info]: frame I:2     Avg QP: 3.27  size: 13288
x264 [info]: frame P:424   Avg QP: 7.94  size:  3639
x264 [info]: mb I  I16..4: 51.3%  0.0% 48.7%
x264 [info]: mb P  I16..4:  2.2%  0.0%  0.7%  P16..4: 34.9% 10.9%  5.8%  0.0%  0.0%    skip:45.5%
x264 [info]: coded y,uvDC,uvAC intra: 24.0% 43.7% 40.8% inter: 15.3% 35.4% 32.7%
x264 [info]: i16 v,h,dc,p: 87%  4% 10%  0%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 46% 11% 26%  2%  3%  4%  2%  3%  2%
x264 [info]: i8c dc,h,v,p: 57%  4% 39%  0%
x264 [info]: Weighted P-Frames: Y:3.8% UV:2.6%
x264 [info]: kb/s:736.91
```

**Comment by 50infivedays** [comment]
> I've successfully reproduced this "bug" with v155. If you are interested in the main reason for these crashes, I'll say that's because since version 158 (or so) they changed their structure for codec params by adding new param avcintra_flavor. As you can imagine if you use a new struct with the old encoder it will change completely different fields. In our case with log_level it writes some garbage into param that should take a string (pointer) containing file path for YUV dump file.
> And I probably tested it on version 158.
> 
> To fix this I have atm only an ugly solution, 2 copies of param structs switched depending on the installed codec version.
> I'd like to solve this a bit better (:
> 
> ![image](https://user-images.githubusercontent.com/846874/112622662-65152a80-8e3c-11eb-94ea-29fc90bd7de8.png)
> 
> Example of quality change on v155 with a temporary fix.
> 
> ```
> -- crf: 17 ---
> x264 [info]: frame I:8     Avg QP:17.50  size: 12265
> x264 [info]: frame P:1946  Avg QP:21.02  size:  1802
> x264 [info]: mb I  I16..4: 19.3%  0.0% 80.7%
> x264 [info]: mb P  I16..4:  1.4%  0.0%  0.5%  P16..4: 29.9% 11.9%  7.7%  0.0%  0.0%    skip:48.6%
> x264 [info]: coded y,uvDC,uvAC intra: 31.2% 56.2% 44.4% inter: 13.7% 30.5% 25.8%
> x264 [info]: i16 v,h,dc,p: 84%  8%  8%  0%
> x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 45% 12% 23%  3%  3%  4%  4%  3%  3%
> x264 [info]: i8c dc,h,v,p: 44%  8% 48%  0%
> x264 [info]: Weighted P-Frames: Y:0.8% UV:0.6%
> x264 [info]: kb/s:369.02
> 
> --- crf: 3 ---
> x264 [info]: frame I:2     Avg QP: 3.27  size: 13288
> x264 [info]: frame P:424   Avg QP: 7.94  size:  3639
> x264 [info]: mb I  I16..4: 51.3%  0.0% 48.7%
> x264 [info]: mb P  I16..4:  2.2%  0.0%  0.7%  P16..4: 34.9% 10.9%  5.8%  0.0%  0.0%    skip:45.5%
> x264 [info]: coded y,uvDC,uvAC intra: 24.0% 43.7% 40.8% inter: 15.3% 35.4% 32.7%
> x264 [info]: i16 v,h,dc,p: 87%  4% 10%  0%
> x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 46% 11% 26%  2%  3%  4%  2%  3%  2%
> x264 [info]: i8c dc,h,v,p: 57%  4% 39%  0%
> x264 [info]: Weighted P-Frames: Y:3.8% UV:2.6%
> x264 [info]: kb/s:736.91
> ```
> 
> v160 should work without issues.

Great! this really helps lot , thanks!

**Comment by sergystepanov** [comment]
So, I tried to add parallel support of both versions and it's actually quite hard to do in Go without proper conditional compiler tags like in C. The code is becoming a mess between conditionals, tags, copy-paste as a result. Can't think of any elegant way of the implementation. 
Don't think it's a good idea to increase complexity for x264. Also, v155 is 2 years old and it's not really worth it to support it, IMHO.

**Comment by 50infivedays** [comment]
yes , and i'll try to upgrade to version160 . thanks again .
And by the way, can you give me some advice on how to debug with cgo? gdb doesn't work well with the program, which makes  the `c/c++` part  hard to trace

**Comment by 50infivedays** [comment]
yes , and i'll try to upgrade to version160 . thanks again .
And by the way, can you give me some advice on how to debug with cgo? gdb doesn't work well with the program, which makes  the `c/c++` part  hard to trace

**Comment by sergystepanov** [comment]
> And by the way, can you give me some advice on how to debug with cgo? gdb doesn't work well with the program, which makes the `c/c++` part hard to trace

I'm afraid I'm not the right person for such advice. From my modest experience with CGO based solely on this project, I can tell that GDB was not well supported in Go/Cgo ecosystem at the time I needed it but we use pretty basic C interactions and code, that even half-broken GDB traces are fine enough for getting the idea of some issue. I'm not sure how well GDB works right now but it's the best option for this purpose AFAIK. There's a dedicated Go debugger called [Delve](https://github.com/go-delve/delve), maybe you should check it out if it works better (or at all (: ) with Cgo.
The most painful moment in my experience is debugging actual bugs in Libretro cores (or any external libs) which are stripped of debugging info. Oh my, was it joyful.

**Comment by 50infivedays** [comment]
> The most painful moment in my experience is debugging actual bugs in Libretro cores (or any external libs) which are stripped of debugging info. Oh my, was it joyful.

haha， interesting. it's very kind of you . thanks .
