### ISSUE TITLE
Cloudretro not in horizontal mode.

### ISSUE THREAD

**Issue by MegaTKC** [giongto35/cloud-game#315]
![Screenshot_2021-05-05-16-24-59](https://user-images.githubusercontent.com/59368582/117221561-5ec08980-adbe-11eb-9cb9-1965453ca024.png)
The cloud gaming service is in vertical mode not horizontal. I am using a samsung galaxy tab 3 or 4. Android Lollypop 5. Tablet.

**Comment by sergystepanov** [comment]
@MegaTKC, thanks for the report. cloudretro.io is running on a pretty old codebase.
I fired up a test server [here](http://130.61.254.42:8000/) with the latest code, could you try it on your devices to see if it works? Maybe, I already fixed the orientation issue.

**Comment by giongto35** [comment]
I sometimes redeploy a code and just figured out that my deploy script is failing now. Will try investigating.
Thanks Sergy for fixing the issue. Can you add version to Frontend as well so that I can aware of how behind my code is.

**Comment by sergystepanov** [comment]
You mean build version info? Sure, I'll try to add (don't know yet how to do this in Go, though) both v-tagged and just git-snapshot labels somewhere.
Not sure when I finish rewrite for k8s / Swarm, hope sometime in the summer (:, so we could finally update the main site.
Recently, Pion added [single port multiplexing](https://github.com/pion/webrtc/commit/0ecbcfeb4fe7d1ece085e2b802ef49d7c196369e) and it seems with that we don't need to specify large amount of port forwarding records, just one, this' great for Docker.

**Comment by MegaTKC** [comment]
Hello, thanks. It works.

**Comment by sergystepanov** [comment]
The cloud-retro site is updated now.

**Comment by giongto35** [comment]
I rolled back to the old version yesterday because I needed to demo cloudretro to some people. The old one can serve more traffic with multiplexing sessions. I will update the new one with multiplex and redeploy again.
