### ISSUE TITLE
The screen is cut off in some games

### ISSUE THREAD

**Issue by xxxsen** [giongto35/cloud-game#332]
game name: 1945kiii

![image](https://user-images.githubusercontent.com/3880276/127172043-1f07e1bd-dd78-4363-8cb9-14030e319496.png)

it shows correctly after ticked `height:100%` 

![image](https://user-images.githubusercontent.com/3880276/127172658-1bc9f585-75d0-45da-ac5f-afb89c640154.png)

**Comment by sergystepanov** [comment]
Thanks. Bugs are expected for games in TATE mode since I haven't fixed UI for that too much.
