### ISSUE TITLE
picture get stuck in some games

### ISSUE THREAD

**Issue by xxxsen** [giongto35/cloud-game#334]
In some games, the picture will be stuck for a period of time. At this time, there is only sound. In addition, when the picture is stuck, the CPU utilization is not high.

**Comment by sergystepanov** [comment]
Without knowing specific steps in order to reproduce this behavior, I'm afraid it's impossible to fix this floating bug.

**Comment by xxxsen** [comment]
howerver, which data shall i provide, it is easy to reproduce in my pc.
I tested three roms (1942.nes/1945kiii.zip/SnowBros.nes), all of them reproduced this problem, and when this problem occurred, all indicators were normal (network/cpu)

**Comment by xxxsen** [comment]
![image](https://user-images.githubusercontent.com/3880276/127345350-c61694d5-7a7f-4636-b2cb-89612b379c48.png)

It seems like a stream problem, frame drop to zero when got stuck

**Comment by sergystepanov** [comment]
Personally, I've never had such issues on local or cloud servers. One relatively similar issue that I had was when the video stops playing when you switch tabs in chrome and it just disables video rendering until a next keyframe would be received from the server.
I could look at your dump if you want, maybe there will be some useful info.
Make a dump attach it here after some time when this happens. The dump button should be in Chrome in chrome://webrtc-internals/ at the very top, then it can be imported into https://fippo.github.io/webrtc-dump-importer/.

**Comment by xxxsen** [comment]
[webrtc_internals_dump (2).txt](https://github.com/giongto35/cloud-game/files/6895153/webrtc_internals_dump.2.txt)

dump file here
@sergystepanov

**Comment by sergystepanov** [comment]
Yeah, this' definitely something on the Go's side. Those 5 second lags are quite strange. Right now there is no option to gather useful logs on the server side but I had plans for some metrics especially related to blocking and waiting.

Right now you could try to run these games with some  old version (e.g. https://github.com/giongto35/cloud-game/commit/9d17435d7eca09a01bc5d4d7cd54019dfd4a59a7) just to compare lags with old Libretro cores.

![изображение](https://user-images.githubusercontent.com/846874/127374014-80c846bf-c4b4-4973-9f01-f8fef7cc7935.png)

**Comment by xxxsen** [comment]
even worse when use old version, but i found what the problem is, it would be my network problem, i re-deploy it in the vm of my pc, it works smoothly, but problem occurs when i deploy it in my nuc in the same network of my pc.

**Comment by xxxsen** [comment]
I test it with wired network, it work too. it got stuck when in wireless network.
however, latency in wireless network is about 1-3ms and 0-1ms in wired network.

**Comment by sergystepanov** [comment]
I wonder how it could affect your video stream... without meaningful server logs, it's just a guessing game (;
Maybe, WebRTC congestion control mechanism on the server cuts your video in order to sustain continuous streaming anyhow.
OK, thanks, I'll keep this issue in mind in case if I will test the server via wi-fi.
