### ISSUE TITLE
key binding problem

### ISSUE THREAD

**Issue by xxxsen** [giongto35/cloud-game#338]
press A, B key together will cause player QUIT current room. (reproduce when use joystick)

is it possible to rebind keys? it binds right trigger to quit room and it it very easy to touch right trigger in mistake.

**Comment by xxxsen** [comment]
it seems not only press A & B together but also press A or B more vigorously will cause QUIT action too.

**Comment by giongto35** [comment]
It's not replicable to me though. It may depend on what game you play. Some games have magic combinations to restart game (ABXY to restart pokemon).

My attempt
https://user-images.githubusercontent.com/7755543/127733362-a4ab1a0f-e4a7-43a8-a4a6-ade863303b2b.mp4

**Comment by xxxsen** [comment]
to reproduce you should press A & B more vigorously in joystick

**Comment by xxxsen** [comment]
after refreshing ui, it doesnt reproduce now..

**Comment by xxxsen** [comment]
emmm, is it possible to support joystick rebinding in the future? i need it..

**Comment by sergystepanov** [comment]
I'll try to hack together this feature after I'm done with other features.
