### ISSUE TITLE
Very slow video performance

### ISSUE THREAD

**Issue by indie-cloud** [giongto35/cloud-game#343]
Hi,

I succesfully installed in my own VPS a version of cloud-game.

From a functional point of view, everything seems to work right, but the performance of the videostream makes the emulation unplayable. 

Audio is smooth and responsive, but video halts constantly. Video works during 2-3 seconds, halts but audio and emulation goes ahead, Video catchs ups after severe frameskipping.

I've tried cloudretro.io and work great, with the same game (NES Contra in this case).

Some extra info:

```
C:\Users\anton>ping cloudretro.io

Haciendo ping a cloudretro.io [167.172.70.98] con 32 bytes de datos:
Respuesta desde 167.172.70.98: bytes=32 tiempo=167ms TTL=47
Respuesta desde 167.172.70.98: bytes=32 tiempo=167ms TTL=47
Respuesta desde 167.172.70.98: bytes=32 tiempo=166ms TTL=47
Respuesta desde 167.172.70.98: bytes=32 tiempo=168ms TTL=47

Estadísticas de ping para 167.172.70.98:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    **Mínimo = 166ms, Máximo = 168ms, Media = 167ms**

C:\Users\anton>ping 161.22.43.92 (-----> my VPS)

Haciendo ping a 161.22.43.92 con 32 bytes de datos:
Respuesta desde 161.22.43.92: bytes=32 tiempo=33ms TTL=57
Respuesta desde 161.22.43.92: bytes=32 tiempo=38ms TTL=57
Respuesta desde 161.22.43.92: bytes=32 tiempo=32ms TTL=57
Respuesta desde 161.22.43.92: bytes=32 tiempo=32ms TTL=57

Estadísticas de ping para 161.22.43.92:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    **Mínimo = 32ms, Máximo = 38ms, Media = 33ms**

```
my VPS seems to deal with things properly:

- 2 vCORES using 15% of capacity in worst scenario
- 800 kbps on network bandwith consumption when playing

Any clue on where to try to find the source of my problem?

Kind Regards

**Comment by giongto35** [comment]
Your machine configuration looks enough. Where does your server locate? I would suggest your server is as closer to you as possible.

**Comment by indie-cloud** [comment]
Hi again,

I'm in Spain an my VPS server where my copy of cloud-game is installed is also in Spain. Ping from my client machine to my VPS is in the range of 30ms.

From my client computer to cloudretro.io itself the ping jumps to near 170ms.

Point is that the 170ms ping version of cloud-game (cloudretro.io) works great and is responsible from my client machine and my VPS with 30ms Ping has a severe (video) lag as described previously. Seems that something in wrong somewere in my deploy and I need to tackle this somehow. Both tests has been done with the same machine, same browser (Brave) only a tab apart.

Any suggestion on logs or reports to look at would it be great finding my way on this.

Thanks a lot for your support

**Comment by indie-cloud** [comment]
Hi again, I've been taking a look into WebRTC Internals and here is the shape of framesReceived:

![image](https://user-images.githubusercontent.com/88707875/129438312-d1352ae7-d924-4668-9885-4ee30ddbdb6b.png)

As you can see the 60fps flow is being interrupted and falls to zero many times, this is what from an user point of view experiences: video stops but audio and emulation goes on normally.

When accessing to cloudretro.io, from the same browser/machine this is how stats compare:

![image](https://user-images.githubusercontent.com/88707875/129438473-734f4611-f73f-42d8-90c4-59f10d677a2c.png)

In this case, everything is working fine without freeze count

Kind Regards

**Comment by giongto35** [comment]
oh interesting graph. It may be because of the bandwidth limit of your VPS. What is your VPS, can you try digital ocean?

**Comment by sergystepanov** [comment]
Hard to tell.
@indie-cloud, could you try [my contra](http://130.61.254.42:8000/?id=5e8eee90230834b8___Contra) with the latest master snapshot, if it runs well? This' Oracle free tier VPS.

**Comment by indie-cloud** [comment]
> oh interesting graph. It may be because of the bandwidth limit of your VPS. What is your VPS, can you try with Digital Ocean?
> Btw, is your laptop under any VPN?

HI, there is no VPN in my connection, the connection is direct from my hot to the VPS

**Comment by indie-cloud** [comment]
> iperf3 -u -c

Hi @sergystepanov . Thanks for your support.

Answers to the question:

1) Your Contra deployment (on Oracle VPS) generates the same behaviour I'm experiencing, with my own VPS with a ping in the 40ms and frameskipping 1 or <1. My VPS show similar info in the emulation console (better ping in the range of 30ms)

<img width="300" alt="Captura Contra Oracle" src="https://user-images.githubusercontent.com/88707875/129475960-891f6f3c-4711-4557-9dcc-e5f3cfcf705b.PNG">

<img width="219" alt="Traces" src="https://user-images.githubusercontent.com/88707875/129475970-b12226af-6b28-496a-bf68-32e8ab13c59b.PNG">

2) Regarding iperf3, results are these:

Client machine (Ubuntu VirtualBox on Windows 10)

```
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms  0/898 (0%)  sender
[  5]   0.00-10.08  sec  1.24 MBytes  1.03 Mbits/sec  0.841 ms  5/898 (0.56%)  receiver
```

Server VPS

```
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datag rams
[  5]   0.00-1.00   sec   117 KBytes   958 Kbits/sec  32900.008 ms  1/83 (1.2%)  
[  5]   1.00-2.00   sec   127 KBytes  1.04 Mbits/sec  106.399 ms  1/90 (1.1%)
[  5]   2.00-3.00   sec   125 KBytes  1.03 Mbits/sec  2.858 ms  1/89 (1.1%)
[  5]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  1.076 ms  0/90 (0%)
[  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  0.553 ms  0/90 (0%)
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  0.942 ms  0/90 (0%)
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  0.828 ms  0/90 (0%)
[  5]   7.00-8.00   sec   127 KBytes  1.04 Mbits/sec  0.743 ms  1/90 (1.1%)
[  5]   8.00-9.00   sec   125 KBytes  1.03 Mbits/sec  0.945 ms  1/89 (1.1%)
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  1.088 ms  0/90 (0%)
[  5]  10.00-10.08  sec  9.98 KBytes  1.02 Mbits/sec  0.841 ms  0/7 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datag rams
[SUM]  0.0-10.1 sec  1 datagrams received out-of-order
[  5]   0.00-10.08  sec  1.24 MBytes  1.03 Mbits/sec  0.841 ms  5/898 (0.56%)  r eceiver
```

I believe the jitter value of 0.841 ms 0,56% loss rate is acceptable and isn't the source of the problem?

Regards

**Comment by sergystepanov** [comment]
@indie-cloud, this is interesting. I'm not experiencing such severe frame drops playing on my server or iperf packet drops at all.
Regarding iperf results, could you please re-run the test on my server for a longer period, e.g. 1 minute (-t param in seconds):
```
iperf3.exe -t 60 -u -V -c 130.61.254.42
``` 
And could you try to switch the video codec on your server to vp8? From `h264` to `vpx`.
https://github.com/giongto35/cloud-game/blob/12312edd03653d3827ff433df9e2577f19caafa7/configs/config.yaml#L186
Also it will be useful if you could attach the full webrtc log like I described here https://github.com/giongto35/cloud-game/issues/334#issuecomment-888456492

**Comment by indie-cloud** [comment]
I've run a couple of test using lperf3 both in Windows and Ubuntu (VM over Windows) pointing to your server with these results:

Windows:

```
C:\Program Files\iperf-3.1.3-win64>iperf3.exe -t 60 -u -V -c 130.61.254.42
iperf 3.1.3
CYGWIN_NT-10.0 DESKTOP-AM9A5N4 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Time: Sun, 15 Aug 2021 14:26:40 GMT
Connecting to host 130.61.254.42, port 5201
      Cookie: DESKTOP-AM9A5N4.1629037600.313853.02
[  4] local 192.168.100.12 port 63694 connected to 130.61.254.42 port 5201
Starting Test: protocol: UDP, 1 streams, 8192 byte blocks, omitting 0 seconds, 60 second test
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   144 KBytes  1.18 Mbits/sec  18
[  4]   1.00-2.00   sec   120 KBytes   984 Kbits/sec  15
[  4]   2.00-3.00   sec   120 KBytes   982 Kbits/sec  15
[  4]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   6.00-7.00   sec   136 KBytes  1.11 Mbits/sec  17
[  4]   7.00-8.00   sec   120 KBytes   984 Kbits/sec  15
[  4]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  10.00-11.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  11.00-12.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  12.00-13.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  13.00-14.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  14.00-15.00  sec   112 KBytes   918 Kbits/sec  14
[  4]  15.00-16.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  16.00-17.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  17.00-18.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  18.00-19.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  19.00-20.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  20.00-21.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  21.00-22.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  22.00-23.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  23.00-24.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  24.00-25.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  25.00-26.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  26.00-27.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  27.00-28.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  28.00-29.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  29.00-30.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  30.00-31.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  31.00-32.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  32.00-33.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  33.00-34.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  34.00-35.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  35.00-36.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  36.00-37.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  37.00-38.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  38.00-39.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  39.00-40.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  40.00-41.00  sec   120 KBytes   984 Kbits/sec  15
[  4]  41.00-42.00  sec   144 KBytes  1.18 Mbits/sec  18
[  4]  42.00-43.00  sec   112 KBytes   917 Kbits/sec  14
[  4]  43.00-44.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  44.00-45.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  45.00-46.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  46.00-47.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  47.00-48.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  48.00-49.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  49.00-50.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  50.00-51.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  51.00-52.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  52.00-53.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  53.00-54.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  54.00-55.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  55.00-56.00  sec   136 KBytes  1.11 Mbits/sec  17
[  4]  56.00-57.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  57.00-58.00  sec   120 KBytes   983 Kbits/sec  15
[  4]  58.00-59.00  sec   128 KBytes  1.05 Mbits/sec  16
[  4]  59.00-60.00  sec   128 KBytes  1.05 Mbits/sec  16
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-60.00  sec  7.50 MBytes  1.05 Mbits/sec  1.756 ms  94/959 (9.8%)
[  4] Sent 959 datagrams
CPU Utilization: local/sender 0.7% (0.3%u/0.5%s), remote/receiver 0.0% (0.0%u/0.0%s)

iperf Done.
```

Ubuntu over Windows:

```
iperf 3.7
Linux mourules-VirtualBox 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64
Control connection MSS 1460
Setting UDP block size to 1460
Time: Sun, 15 Aug 2021 14:33:07 GMT
Connecting to host 130.61.254.42, port 5201
      Cookie: 27voaeiorvoryunqql6cj2xm6t524qj5ai4l
      Target Bitrate: 1048576
[  5] local 10.0.2.15 port 51330 connected to 130.61.254.42 port 5201
Starting Test: protocol: UDP, 1 streams, 1460 byte blocks, omitting 0 seconds, 60 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   4.00-5.00   sec   127 KBytes  1.04 Mbits/sec  89  
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  5]   8.00-9.00   sec   127 KBytes  1.04 Mbits/sec  89  
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  10.00-11.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  11.00-12.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  12.00-13.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  13.00-14.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  14.00-15.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  15.00-16.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  16.00-17.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  17.00-18.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  18.00-19.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  19.00-20.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  20.00-21.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  21.00-22.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  22.00-23.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  23.00-24.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  24.00-25.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  25.00-26.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  26.00-27.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  27.00-28.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  28.00-29.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  29.00-30.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  30.00-31.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  31.00-32.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  32.00-33.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  33.00-34.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  34.00-35.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  35.00-36.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  36.00-37.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  37.00-38.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  38.00-39.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  39.00-40.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  40.00-41.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  41.00-42.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  42.00-43.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  43.00-44.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  44.00-45.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  45.00-46.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  46.00-47.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  47.00-48.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  48.00-49.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  49.00-50.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  50.00-51.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  51.00-52.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  52.00-53.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  53.00-54.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  54.00-55.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  55.00-56.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  56.00-57.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  57.00-58.00  sec   127 KBytes  1.04 Mbits/sec  89  
[  5]  58.00-59.00  sec   128 KBytes  1.05 Mbits/sec  90  
[  5]  59.00-60.00  sec   128 KBytes  1.05 Mbits/sec  90  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  7.50 MBytes  1.05 Mbits/sec  0.000 ms  0/5387 (0%)  sender
[  5]   0.00-60.08  sec  7.12 MBytes   994 Kbits/sec  1.435 ms  275/5386 (5.1%)  receiver
CPU Utilization: local/sender 17.8% (0.0%u/17.7%s), remote/receiver 0.0% (0.0%u/0.0%s)

iperf Done.
```

**Comment by indie-cloud** [comment]
Hi again @sergystepanov 

Find attached the dump file for the webrtc session:

[webrtc_internals_dump.txt](https://github.com/giongto35/cloud-game/files/6988344/webrtc_internals_dump.txt)

This traces comes from VPX codec. From an user point of view, the game is _more playable_ than in h.264 because frameskip is perceived as less severe, but you will see in traces that this keeps happening.

In sumary, moving from h.264-> to vpx doesn't solve the problem, mitigates it from user point ov view but logs keeps showing freezeCount over time.

btw, my vps can be found in indie-cloud.com:8000

thanks a lot!!!

**Comment by sergystepanov** [comment]
Strange. 😕 at least I can see the stable rate of video frames from the server. 
But you still have some pretty noticeable packet losses in the rtc stats. On top of that, there are strange packet bursts.

![image](https://user-images.githubusercontent.com/846874/129486634-bbf0c592-bdfd-424e-95b0-58da63bd4be5.png)

This could be related to Pion WebRTC lib. Between master branch and cloudretro.io a year difference in Go libs updates.
I'll try to look into some stuff later when I finish the new deployment tasks.

**Comment by giongto35** [comment]
@sergystepanov your deployment seems fine to me, seems smooth 
![image](https://user-images.githubusercontent.com/7755543/129503771-071341cf-d736-4a56-8b06-5c75c9de39df.png)
@indie-cloud Can you setup your VPS again. I will try yours too to see if it has slow video performance

**Comment by indie-cloud** [comment]
Hi @giongto35 , my VPS is live again at indie-cloud.com:8000.

As a wrap-up of the issue:

- My VPS has ping in the range of 30ms, with reasonable iperf3 values but frameskipping is taking place, both in h.264 and vpx codecs. However vpx codec shows a better behaviour on end user side, making things more or less playable vs h.264 that is unplayable

- @sergystepanov 's Oracle VPS shows the very same wrong behaviour on my end, with slightly slower ping (in the range of 40ms)

- cloud-retro.com works from my side despite the high ping in the range of 170ms there is some lack of responsiveness in the controls (I believe due to ping) but no perceived frameskipping (nor in the webinternals stats) 

Thanks a lot @giongto35 and @sergystepanov for your support

**Comment by sergystepanov** [comment]
Just tried a bit to play in indie-cloud and it was flawless except for one initial glitch.

This' how it should look like, but in your case, you have progressive packet losses and it seems this happens on your client. (first - mine, second - yours)

![image](https://user-images.githubusercontent.com/846874/129602720-239c4995-a32c-4667-bcea-74b49cfe5bac.png)
![image](https://user-images.githubusercontent.com/846874/129604058-caf439d5-4a4c-4e9b-a1ee-e9139f2c1065.png)

@indie-cloud, could you try a different ISP, maybe on a different device? 3/4/5G network from a smartphone?
I lowered the h264 codec's decoding complexity on my VPS, you can try it also how it runs for you.
I guess, something isn't right with your client network. Right now no idea why considering cloudretro.io's normal behavior.

**Comment by giongto35** [comment]
indie-cloud.com:8000 works perfect for me as well. Good thing is that your host is still playable to other people.
So yeah, I think maybe it's your network as well. Trying with 3/4/5G can help.
But it's interesting that the current CloudRetro behaves differently :-?. @sergystepanov is working on deploying a new version to CloudRetro, we can try again.

**Comment by indie-cloud** [comment]
Hi!

I've changed the ISP and the way of connection. Now I've tried with new ISP + Ethernet (previously WiFi) and everything works flawlessly.

The ping is in the range of 10ms and there is not frame skipping.

I will close this issue
