### ISSUE TITLE
Seems like only webui is loaded

### ISSUE THREAD

**Issue by CharlesLTH** [giongto35/cloud-game#362]
Hi, I tried your demo and want to host the wanderful game service on my server, so I tried on my nas and bandwagon vps, but both have the same issue. 
I use `docker-compose up --build` to build, and open port 8000, 9000.
when I visit ip:8000, webui is loaded, but I wait for a long time, no pixel font come out from the orange color screen texture.

there are logs
`I0125 05:57:18.683610       9 handlers.go:116] Coordinator: A user is connecting...
I0125 05:57:18.688744       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Generated worker ID
I0125 05:57:18.689705       9 browser.go:29] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Get Room  Zone  From URL /ws?room_id=&zone=
I0125 05:57:18.690700       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Send sync[http://localhost:9000/echo]http://localhost:9000/echo
I0125 05:57:19.968135       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Latency mapmap[0xc000246360:9999]
I0125 05:57:20.119980       9 browser.go:29] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received init_webrtc request -> relay to worker: e23e66e1-1821-400d-b433-646e263d7e15
I0125 05:57:20.124399      10 internalhandlers.go:41] Received a request to createOffer from browser via coordinator
I0125 05:57:20.128484      10 webrtc.go:108] === StartClient ===
I0125 05:57:20.137432      10 webrtc.go:124] Add video track
I0125 05:57:20.141129      10 webrtc.go:217] Created Offer
I0125 05:57:20.142172      10 internalhandlers.go:61] Start peerconnection 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785
I0125 05:57:20.143489       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received SDP from worker -> sending back to browser
I0125 05:57:20.149498      10 webrtc.go:178] OnIceCandidate: candidate:2878742611 1 udp 2130706431 127.0.0.1 8443 typ host
I0125 05:57:20.149969       9 worker.go:61] Worker e23e66e1-1821-400d-b433-646e263d7e15] Received IceCandidate from worker -> relay to browser
I0125 05:57:20.160846      10 webrtc.go:178] OnIceCandidate: candidate:850826790 1 udp 1694498815 45.78.51.190 43838 typ srflx raddr 0.0.0.0 rport 43838
I0125 05:57:20.162665       9 worker.go:61] Worker e23e66e1-1821-400d-b433-646e263d7e15] Received IceCandidate from worker -> relay to browser
I0125 05:57:20.164692       9 worker.go:61] Worker e23e66e1-1821-400d-b433-646e263d7e15] Received IceCandidate from worker -> relay to browser
I0125 05:57:20.305637       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received browser answered SDP -> relay to worker
I0125 05:57:20.308732      10 internalhandlers.go:74] Received answer SDP from browser
I0125 05:57:20.318525      10 webrtc.go:261] Set Remote Description
I0125 05:57:20.320648      10 webrtc.go:162] ICE Connection State has changed: checking
I0125 05:57:20.322593       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received IceCandidate from browser -> relay to worker
I0125 05:57:20.324040      10 internalhandlers.go:91] Received remote Ice Candidate from browser
I0125 05:57:20.324639      10 webrtc.go:272] Decoded Ice: candidate:3400866012 1 udp 2113937151 10.11.131.11 38158 typ host generation 0 ufrag a6zd network-cost 999
I0125 05:57:20.325273      10 webrtc.go:280] Add Ice Candidate: candidate:3400866012 1 udp 2113937151 10.11.131.11 38158 typ host generation 0 ufrag a6zd network-cost 999
I0125 05:57:20.329910       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received IceCandidate from browser -> relay to worker
I0125 05:57:20.333197      10 internalhandlers.go:91] Received remote Ice Candidate from browser
I0125 05:57:20.334070      10 webrtc.go:272] Decoded Ice: candidate:3409178877 1 udp 2113939711 240e:476:340:4d65:80a1:b2d8:e977:3ed 49264 typ host generation 0 ufrag a6zd network-cost 999
I0125 05:57:20.334838      10 webrtc.go:280] Add Ice Candidate: candidate:3409178877 1 udp 2113939711 240e:476:340:4d65:80a1:b2d8:e977:3ed 49264 typ host generation 0 ufrag a6zd network-cost 999
I0125 05:57:20.417840       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Received IceCandidate from browser -> relay to worker
I0125 05:57:20.419999      10 internalhandlers.go:91] Received remote Ice Candidate from browser
I0125 05:57:20.421039      10 webrtc.go:272] Decoded Ice: candidate:842163049 1 udp 1677729535 139.204.167.6 6679 typ srflx raddr 10.11.131.11 rport 38158 generation 0 ufrag a6zd network-cost 999
I0125 05:57:20.422060      10 webrtc.go:280] Add Ice Candidate: candidate:842163049 1 udp 1677729535 139.204.167.6 6679 typ srflx raddr 10.11.131.11 rport 38158 generation 0 ufrag a6zd network-cost 999
I0125 05:57:50.347267      10 webrtc.go:162] ICE Connection State has changed: failed
I0125 05:57:54.879705       9 cws.go:181] [!] read: read tcp 172.18.0.2:8000->139.204.167.6:6869: i/o timeout
I0125 05:57:54.880025       9 browser.go:33] Browser 1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785] Disconnect from coordinator
I0125 05:57:54.880713      10 internalhandlers.go:25] Received a terminate session  1ca1ec0c-90d0-48f1-b83f-7f1e3ae17785
I0125 05:57:54.880814      10 handlers.go:149] [worker] closing peer connection
`

**Comment by sergystepanov** [comment]
Hey! Take a look at [docker-compose.yml](https://github.com/giongto35/cloud-game/blob/master/docker-compose.yml) example from the repository. Apart from two HTTP/WebSocket ports (for coordinator and worker, that you've opened), the worker application requires a bunch of additional UDP ports to be opened as well. In that Docker Compose example, port 8443 is used for that purpose (in so-called UDP multiplex configuration mode). As an alternative solution, it is possible just to open all Docker ports with `host` mode config param (see an [example](https://github.com/giongto35/cloud-game/blob/master/.github/workflows/cd/docker-compose.yml#L7) as we configure cloudretro.io).
After that don't forget to check if your server (host) firewall doesn't block configured ports.

**Comment by CharlesLTH** [comment]
Thanks!
