### ISSUE TITLE
dosbox_pure_libretro.so keyboard mapping

### ISSUE THREAD

**Issue by Kenneth-Audenaert** [giongto35/cloud-game#363]
my end goal is to get dosbox games running in the same way that the other cores work.

I successfully installed dosbox_pure_libretro.so as a new core and added a game to the games folder
adjusted config.yaml, started up the server and worker and got a game running.

however it seems the keyboard does not map to what the dosbox core expects.

imho I would expect that web/js/input/input.js and web/js/input/keyboard.js have a role to play in the client side of the controller support.

no clue about the server side though.

**Comment by Kenneth-Audenaert** [comment]
dosbox_pure_libretro does some fancy automapping which works quite ok if you use a controller.

I tried with both an xbox style controller (logitech rumblepad 2) on a pc and an xbox controller on an xbox one x, this does seem to map quite ok in most cases (dos platformers work mostly ok)

however there does not seem to be a way to switch to fullscreen mode in cloudretro with an xbox style controller (other then plugging in a keyboard to press the "F" key).

I also noticed that the right stick is not mapped to anything nor are the push functions of both sticks. (usually L3 en R3)

maybe these could be mapped to the function for the F key on controllers?

I know that dosbox_pure_libretro is able to display an onscreen keyboard when playing games. cfr: https://github.com/schellingb/dosbox-pure#on-screen-keyboard
This is handy when playing dosgames which require some weird unmapped key press (dos games tend to have these).

but there is no way to call this onscreen keyboard with the current cloudretro controller mapping scheme. (if i'm not mistaken this is mapped to L3 by default in dosbox_pure_libretro)

This onscreen keyboard is a nice way of allowing for additional keypresses without actually implementing all the seperate keypresess natively through the entire cloud-retro stack.

could the L3 functionality be enabled?

**Comment by Kenneth-Audenaert** [comment]
joystick.js
`
125         } else {
126             // default of other OS is KeyMap2
127             joystickMap = {
128                 0: KEY.A,
129                 1: KEY.B,
130                 2: KEY.START,
131                 3: KEY.SELECT,
132                 // allow L3 mapping for dosbox_pure to be able to call t    he virtual keyboard
133                 4: KEY.L3,
134                 8: KEY.LOAD,
135                 9: KEY.SAVE,
136                 6: KEY.HELP,
137                 7: KEY.QUIT,
138                 12: KEY.UP,
139                 13: KEY.DOWN,
140                 14: KEY.LEFT,
141                 15: KEY.RIGHT,
142             };
`

**Comment by Kenneth-Audenaert** [comment]
maybe best to do a controller mapping scheme based on what core is loaded (if that is possible)?

**Comment by Kenneth-Audenaert** [comment]
-testing on windows client with rumble pad 2 works great.
-testing on xbox all works fine in "game controller mode", except that pressing "B" in fullscreen mode quits fullscreen mode 
(mostly mapped to the jump key in dosbox_pure games, so only really playable in windowed mode for now)

**Comment by sergystepanov** [comment]
There is no option for the client (browser) to know what core is running at the moment.
Could you try B remap in the options? Will it work with a controller? (I think it won't)

**Comment by Kenneth-Audenaert** [comment]
yes it just exits full screen, the game keeps running just fine

**Comment by Kenneth-Audenaert** [comment]
B only exits

**Comment by Kenneth-Audenaert** [comment]
is there a way to just run the app in fullscreen by default, and disabling fullscreen/windowed togling?

appart from the cool handheld aesthetic, I don't see a good reason (at least for my intended purposes) to have it in a window anyway.

**Comment by sergystepanov** [comment]
Not possible, but it'll be not that hard to add.
Yeah, this handheld-like UI makes sense only with smartphones (touch screens). Not sure about making it fullscreen by default, but as an option, why not.

**Comment by Kenneth-Audenaert** [comment]
e.g. different configurable defaults depending on client device string (ios, windows, android, ...)
