### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by yangyuguo** [giongto35/cloud-game#369]
Hello! I'm try run command  make dev.run
go version is 1.16 
here there are logs
mkdir -p bin/
go build -o bin/ ./cmd/coordinator
go build -o bin/ ./cmd/worker
# github.com/giongto35/cloud-game/v2/pkg/encoder/yuv
pkg/encoder/yuv/options.go:4:11: undefined: ChromaPos
pkg/encoder/yuv/options.go:29:17: undefined: ChromaPos
# github.com/giongto35/cloud-game/v2/pkg/encoder/opus
pkg/encoder/opus/encoder.go:10:2: undefined: LibOpusEncoder
pkg/encoder/opus/encoder.go:16:18: undefined: NewOpusEncoder
pkg/encoder/opus/encoder.go:16:50: undefined: AppRestrictedLowdelay
# github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch
pkg/emulator/libretro/nanoarch/persistence.go:7:11: undefined: naEmulator
pkg/emulator/libretro/nanoarch/persistence.go:11:18: undefined: getSaveRAM
pkg/emulator/libretro/nanoarch/persistence.go:14:23: undefined: getSaveState
pkg/emulator/libretro/nanoarch/persistence.go:22:11: undefined: naEmulator
pkg/emulator/libretro/nanoarch/persistence.go:27:3: undefined: restoreSaveRAM
pkg/emulator/libretro/nanoarch/persistence.go:30:10: undefined: restoreSaveState
make: *** [dev.build-local] Error 2

**Comment by sergystepanov** [comment]
Hi,
could you show the output of these commands: ```go env``` and then ```go build -x ./cmd/worker/```?

**Comment by yangyuguo** [comment]
Hello! go env

**Comment by sergystepanov** [comment]
Try with the env variable CGO_ENABLED=1 (disabled on your system for some reason).

**Comment by yangyuguo** [comment]
I set CGO_ENABLED=1 ，now it works！Thank you for your enthusiastic help！
