### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by Heath123** [giongto35/cloud-game#380]
The site doesn't seem to do anything, giving this error:
![image](https://user-images.githubusercontent.com/13787163/196056475-4b9b5f94-5fa5-4466-95ed-59c1e0166ab8.png)
(seems like the game list is empty?)
If I follow a link to a game then it still doesn't work:
![image](https://user-images.githubusercontent.com/13787163/196056522-cf755680-e712-42b3-892f-a837a590901e.png)

**Comment by sergystepanov** [comment]
Could you try to select **usw** server from the menu that you can open by clicking on the **w** symbol at the top left corner of the interface (between question and options button).
![image](https://user-images.githubusercontent.com/846874/196137486-b72041bc-f055-46bd-bd61-c9f86766155b.png)

**Comment by giongto35** [comment]
Yes, select the usw.cloudretro.io works. Somehow the undefined address messes up the routing. Let me find way to exclude that @sergystepanov

**Comment by sergystepanov** [comment]
I removed "undefined" workers, so the issue should be fixed.
