### ISSUE TITLE
Can I change the streaming screen to a desktop or a the program's ui?

### ISSUE THREAD

**Issue by wangdemon** [giongto35/cloud-game#381]
This project is really amazing to me.
I want to change the game screen to desktop screen or a program ui.as shown in the following figure.
Original picture:
![1](https://user-images.githubusercontent.com/20681339/197094629-1946d03c-6dec-41f2-9a1e-06d75e0705b0.png)
The picture I expect:
![2](https://user-images.githubusercontent.com/20681339/197094642-3cb1591b-547a-4b99-b9f5-b90ce3bb58d7.png)

**Comment by giongto35** [comment]
Hi @wangdemon , you can check https://github.com/giongto35/cloud-morph. It is to stream windows application
