### ISSUE TITLE
make dev-run error~

### ISSUE THREAD

**Issue by icemanyandy** [giongto35/cloud-game#386]
mkdir -p bin/
go build -o bin/ ./cmd/coordinator
go build -o bin/ ./cmd/worker
# github.com/veandco/go-sdl2/sdl
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:572:17: could not determine kind of name for C.SDL_GameControllerGetSensorDataRate
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:572:68: could not determine kind of name for C.SDL_SensorType
cgo: 
gcc errors for preamble:
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:177:81: error: unknown type name 'SDL_SensorType'
 static SDL_bool SDL_GameControllerHasSensor(SDL_GameController *gamecontroller, SDL_SensorType type)
                                                                                 ^
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:182:83: error: unknown type name 'SDL_SensorType'
 static int SDL_GameControllerSetSensorEnabled(SDL_GameController *gamecontroller, SDL_SensorType type, SDL_bool enabled)
                                                                                   ^
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:187:87: error: unknown type name 'SDL_SensorType'
 static SDL_bool SDL_GameControllerIsSensorEnabled(SDL_GameController *gamecontroller, SDL_SensorType type)
                                                                                       ^
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:192:80: error: unknown type name 'SDL_SensorType'
 static int SDL_GameControllerGetSensorData(SDL_GameController *gamecontroller, SDL_SensorType type, float *data, int num_values)
                                                                                ^
../../../go/pkg/mod/github.com/veandco/go-sdl2@v0.4.20/sdl/gamecontroller.go:227:86: error: unknown type name 'SDL_SensorType'
 static float SDL_GameControllerGetSensorDataRate(SDL_GameController *gamecontroller, SDL_SensorType type)
                                                                                      ^

Makefile:73: recipe for target 'dev.build-local' failed

could you please give me some tips?

**Comment by sergystepanov** [comment]
@icemanyandy, did you fix it? My guess is that might be a problem with old Go version or GCC on the system.
