### ISSUE TITLE
Controllers do not work in the fullscreen mode

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#416]
@sergystepanov
Exactly, usb gamepad not working in fullscreen mode

in normal screen work but

lag, delay on d-pad
not remap keys

_Originally posted by @discordfar in https://github.com/giongto35/cloud-game/issues/414#issuecomment-1750241037_

**Comment by discordfar** [comment]
hi brother
i try now https://cloudretro.io/
and usb gamepad now work on fullscreen mode.

However, how do you play n64?
d-analog and c-buttons do not exist in keymap

many  thanks!

**Comment by sergystepanov** [comment]
There is a slider for analog/d-pad switch over the quit button.
![image](https://github.com/giongto35/cloud-game/assets/846874/9236fcad-a265-4211-a685-716c8032be03)
And yes, it's missing L2 R2 buttons (they exist but not forwarded to the controls).
I will be working on controls at some point in the future.

**Comment by discordfar** [comment]
nice slide function,
but in n64 need work d-pad, d-analag, c-buttons, z-button same time all for change camera and other function
in zelda ocarina example need c-buttons for choose itens

see n64 with all buttons

![Captura-de-pantalla-2017-03-26-16 57 29](https://github.com/giongto35/cloud-game/assets/142048925/d62a2b44-1a9e-4347-9172-ab692aceb5c6)

**Comment by sergystepanov** [comment]
What a strange controller it was. In Libretro that should be L2 R2 L3 R3. 
The thing is that multiplayer cloud-game was not designed for such cores like Mupen (N64) where one player can use multiple control ports (devices) at once which is called multitap. This analog stick option was just a hack to toy with the core. And I'm not the author of this feature.
In general, the controls in cloud-game should work on simpler Nintendo cores, and the rest may work if you are lucky.
I'll be working on rewriting the controller system in the future. It's not easy. We will see.

**Comment by discordfar** [comment]
Other thing
mega drive gamepad have 6 buttons, A,B,C,X,Y,Z
in keymap have A,B,X,Y
C and Z not

other old system too use similar gamepad

bests!

**Comment by sergystepanov** [comment]
Successfully tested with an XBOX controller on the latest version. Issue is not reproducible.
