### ISSUE TITLE
can it support android app?

### ISSUE THREAD

**Issue by LTYF** [giongto35/cloud-game#435]
how can it support android app?

**Comment by sergystepanov** [comment]
Run as a native Android app, everything on a mobile device? If so, that'd be quite hard to do, but in theory that could be possible, not possible right now. 
At the moment it only works in a mobile browser (chrome) with the touch controls supported.

**Comment by LTYF** [comment]
no，i mean that can this cloud-game support android app game？how can i add an android game to game list?




***@***.***

From: ::::::
Date: 2023-11-15 18:40
To: giongto35/cloud-game
CC: LTYF; Author
Subject: Re: [giongto35/cloud-game] can it support android app? (Issue #435)
Run as a native Android app, everything on a mobile device? If so, that'd be quite hard to do, but in theory that could be possible, not possible right now.
At the moment it only works in a mobile browser (chrome) with the touch controls supported.

**Comment by sergystepanov** [comment]
Not possible. Only [Libretro](https://www.libretro.com/) cores (console emulators) are supported. There are some other projects that allow capturing and streaming arbitrary apps including Android emulators, but not this one.

**Comment by LTYF** [comment]
Can you recommend one to me ?  thanks very much!




***@***.***

From: ::::::
Date: 2023-11-15 19:49
To: giongto35/cloud-game
CC: LTYF; Author
Subject: Re: [giongto35/cloud-game] can it support android app? (Issue #435)
Not possible. Only Libretro cores (console emulators) are supported. There are some other projects that allow capturing and streaming arbitrary apps including Android emulators, but not this one.

**Comment by sergystepanov** [comment]
I think, the best option for your case is [Rustdesk](https://rustdesk.com/) and (or) [Bluestacks](https://www.bluestacks.com/).
And the other projects like cloud-morph ([CopeGaming](https://github.com/hxt365/CopeGaming), [Arc3dia](https://github.com/wanjohiryan/Arc3dia)) are not ready (yet) for general use.

**Comment by LTYF** [comment]
Thank you very much！




***@***.***

From: ::::::
Date: 2023-11-15 22:25
To: giongto35/cloud-game
CC: LTYF; Author
Subject: Re: [giongto35/cloud-game] can it support android app? (Issue #435)
I think, the best option for your case is Rustdesk and (or) Bluestacks.
And the other projects like cloud-morph (CopeGaming, Arc3dia) are not ready (yet) for general use.
