### ISSUE TITLE
No games List

### ISSUE THREAD

**Issue by nzlov** [giongto35/cloud-game#439]
clone and run:
```
docker compose up --build
```

![image](https://github.com/giongto35/cloud-game/assets/2859981/6a601248-33b6-471e-9f11-3ea233f79a82)
![image](https://github.com/giongto35/cloud-game/assets/2859981/c520df22-f519-4e7d-8bd5-499e3182beaa)

**Comment by sergystepanov** [comment]
What's in your browser console tab (控制台)? I assume, this is the latest Firefox?
Could you try to reload the page without the cache? That's Ctrl+Shift+R in FF, and Ctrl+F5 in Chrome.
