### ISSUE TITLE
When saving Windows 98 game state , worker.exe will exit the process

### ISSUE THREAD

**Issue by guozanhua** [giongto35/cloud-game#464]
It seems that if the game save state file is  too long size , will block worker process, then causing worker.exe to exit the process?

**Comment by sergystepanov** [comment]
It might block the app during the save operation, so either WebSocket or WebRTC could drop the connection in the browser, but it won't end the worker process; otherwise, that's probably a bug.
If you can provide me with the information (a guide) on how to run Win98 myself, I'll try to look into it.

**Comment by sergystepanov** [comment]
I added a simple non-blocking save method, which is enabled for DosBox now, you can try it (latest commit in the main branch).
