### ISSUE TITLE
ARM UBUNTU18报错NO ABI matched

### ISSUE THREAD

**Issue by zhuangzhuang3** [giongto35/cloud-game#474]
请问是否是不支持在这个系统部署该项目
![image](https://github.com/user-attachments/assets/dbf3b7fb-96ac-49b2-8ba0-119a127ed364)
![image](https://github.com/user-attachments/assets/e5b5b51e-002f-4773-bfe2-d0d18c1bdf32)
![image](https://github.com/user-attachments/assets/63e59e65-42d1-4775-a658-6447c407c0ba)

**Comment by sergystepanov** [comment]
我猜測你的系統配置不支援靜態鏈接的 SDL2。可以參考這裡：[這裡](https://www.reddit.com/r/golang/comments/1eyowun/compiling_static_binary_with_sdl2/) 和 [這裡](https://github.com/veandco/go-sdl2/issues/513)。

我認為你可以編譯它，但不能靜態鏈接。在 Dockerfile 中，將以下這行的 GO_TAGS=static,st 刪除：
RUN --mount=type=cache,target=/root/.cache/go-build make GO_TAGS=static,st build.worker
然後添加所需的庫：libopus-dev、libsdl2-dev、libvpx-dev、libyuv-dev、libjpeg-turbo8-dev、libx264-dev；如果需要 OpenGL，還需要 x11 和 mesa；以及 ca-certificates。這應該是 Docker 映像的最後一步。
