### ISSUE TITLE
Joystick recognized but unable to use

### ISSUE THREAD

**Issue by ThiagoProg37** [giongto35/cloud-game#475]
Guys, sorry for just getting to this topic, but I'm having this little problem when running the project locally. The joystick is recognized as shown in the image, but it's not available for use. How can I test it in the application?

Windows 11 with Firefox and Chrome
![image](https://github.com/user-attachments/assets/b261c6f6-054b-46c7-a6d0-dd3069f4aeb4)

**Comment by sergystepanov** [comment]
@ThiagoProg37,

that was a bug, now it's fixed. Get the latest version from the master branch (or try cloudretro.io) and **clear the cache** of the app in your browser (it caches frontend for 3 days).
Also, those weird joystick button mappings can only be changed manually in the joystic.js file.

**Comment by ThiagoProg37** [comment]
@sergystepanov 

Thanks for responding. It worked perfectly!
Indeed, the buttons have a random configuration but, I must say, just by being available, it deserves all the respect.
Congratulations on a job well done.

I have a random question, it's not related to the topic but if you could give some direction I would appreciate it.
I would like, when two players connect to play, to first know if it would be possible to record the game between them.
If so, could this recording be generated in the format of the emulator itself (snes9x)?

**Comment by ThiagoProg37** [comment]
@sergystepanov 

cool, it worked :) and Sorry for using this space for random questions, I promise they will be the last. 

I loaded the application using the "make dev.run" command and started it normally in the browser, but I noticed that it is only possible to create one instance at a time, that is, if I am already running the application and open another browser, it sends me the message that the slots are busy and the second instance does not load the game list. Is there any setting that disables this behavior? 

The second observation is: when I share a room, the guest player always connects using controller 1 and the default should be to connect with controller 2. Is this a bug or is it on purpose? Thank you very much for your attention and keep up the great work

**Comment by sergystepanov** [comment]
> I loaded the application using the "make dev.run" command and started it normally in the browser, but I noticed that it is only possible to create one instance at a time, that is, if I am already running the application and open another browser, it sends me the message that the slots are busy and the second instance does not load the game list. Is there any setting that disables this behavior?

By design, only one person can connect to a free worker at a time, while any number of people can connect to a worker running a shared game. You can simply spin up multiple worker instances if needed. On CloudRetro.io, there are currently four workers, which you can check by clicking the 'W' symbol under the options button in the app's interface.

> The second observation is: when I share a room, the guest player always connects using controller 1 and the default should be to connect with controller 2. Is this a bug or is it on purpose? Thank you very much for your attention and keep up the great work

This is not a bug. It's a design decision by the author, or rather something unimportant that might be 'fixed' later.
