### ISSUE TITLE
Proposal: Split binaries for overlordhost and overlord into separate binary

### ISSUE THREAD

**Issue by sadlil** [giongto35/cloud-game#68]
Currently, cloud-game generates only one binary for both the program included in a single binary. While running we have to explicitly set flags to indicate which mode we intend it to run.
I am suggesting to split the two binaries into two different executables. They might share some of the same library packages but should live in different executables. I think there are some benefits - like - 
```
1. we could include runtime flags specific to one program,
2. We could do different versioning for overlordhost and overlord,
3. one executable doesn't include the life cycle of the other one.
```

Here is some package restructure proposal that I think would suit nicely
```
cloud-game
|-- assets     // includes all static .so or game file
|-- assests/games
|-- assests/lib

|-- cmd         // will include all the executables
|-- cmd/overlord  // will include the main.go for overlord. can use spf13/cobra
|-- cmd/overlordhost  // main.go for overlordhost

|-- docs      // includes all the static docs
|-- docs/design
|-- docs/userguide
|-- docs/site    // includes static site pages for projects

|-- hack       // Includes various scripts, build files
|-- hack/docker // includes docker build files
|-- hack/config  // includes various config files like prometheus.conf
|-- hack/k8s    // includes k8s runtime files
|-- hac/scripts  // various scripts to build env or others

|-- pkg  // includes all go/ cgo librarie codes. ie-
|-- pkg/api
|-- pkg/util
|-- pkg/config
|-- pkg/webrtc

| -- static   // include project-level static resources like the logo
| -- static/logo
| -- static

|-- web      // all the files for the web frontend
|-- web/

|-- vendor // go vendor directory

|-- Makefiles
|-- go.mod
|-- go.sum
|-- README.md
```

@giongto35  Let me know what you think about this? I can go forward with a PR if it seems okay. Thanks for this awesome project. 😄

**Comment by giongto35** [comment]
@sadlil Thanks very much for your awesome proposal. 
Yes, splitting binary will definitely make the codebase clearer and reduce the dependency. We also need to update the run_local.sh and run_local_docker.sh to follow the new build.

I like your suggested code structure. I just wonder if we can move `/static` under `/web` and have better naming instead of "hack".
Besides, my terminology is "overlord" for coordinator and "worker" for server connecting to the coordinator - overlordhost in your thinking.

so the naming should be
`cmd/overlord` and `cmd/worker`

**Comment by giongto35** [comment]
By the way, my production is run on Docker + supervisor. Moving to K8S is also in my plan but I'm lacking knowledge on that so I haven't done it.

**Comment by sadlil** [comment]
@giongto35  
> so the naming should be
cmd/overlord and cmd/worker

the naming sounds good to me.

> I just wonder if we can move /static under /web

This is possible. I was just thinking if there is anything static that aren't specifically related to the website can go to a top-level directory. 

> better naming instead of "hack".

Hack is actually a common way to name a directory to put together random things like build scripts, test runner, deployment configs etc. I adopted this from kubernetes code base - https://github.com/kubernetes/kubernetes/tree/master/hack or https://github.com/appscode/voyager/tree/master/hack

> By the way, my production is run on Docker + supervisor. Moving to K8S is also in my plan but I'm lacking knowledge on that so I haven't done it.

I have a few experiences of running k8s. Will try to help on this. If you are okay with this I can go-ahead to put together a PR for the suggested change. It's a big change so please make the decision carefully. I will also fix necessary build files and scripts to go with new code structures.

**Comment by giongto35** [comment]
oh i see, thank you for introducing the concept of hack :p 

I think I will do it to follow your new code structure because I have other deployment repo that I need to update also. Hopefully by next week I can have the new code structure :p 
Thank you for your awesome suggestion again.

**Comment by giongto35** [comment]
Is it possible if we can have a script to spawn K8s with an overlord container and few workers container connecting to that overlord container. It will be a great example for production-level deployment.

**Comment by sadlil** [comment]
Actually, if you are busy working on something I think I can help to create a PR for organizing the codes per the proposal if that's alright with you guys.

> Is it possible if we can have a script to spawn K8s with an overlord container and few workers container connecting to that overlord container. It will be a great example for production-level deployment.

Yes. I can also include this in PR.

If that's okay feel free to assign the issue to me.  cheers.

**Comment by giongto35** [comment]
I'm in the progress of re-announcing it with some new updates, so I'm trying to update Wiki and Github page for easier contribution. It will be great with your help for the reorganization. I'm not touching the codebase much right now, so you can go forward with that.
I only have pending works on updating video encoding part and making PlayStation fully work.

**Comment by sadlil** [comment]
Sure man. I will put together a PR coming week.
