### ISSUE TITLE
Can't start any game

### ISSUE THREAD

**Issue by namkazt** [giongto35/cloud-game#84]
I got some  error when starting the server and can't start any game on `localhost:8000`.

```
2019/09/10 10:30:56 Listening at port: localhost:8000
2019/09/10 10:30:56 Running as worker
2019/09/10 10:30:56 Warn: Failed to create client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2019/09/10 10:30:56 Listening at port: localhost: 9000
.....
.....
2019/09/10 10:31:04 === StartClient ===
2019/09/10 10:31:04 Start peerconnection 1b9e405b-1c5f-4e67-84a8-26d76d84d7de
2019/09/10 10:31:04 Error: Cannot create new webrtc session mDNS: failed to join multicast group
2019/09/10 10:31:04 Overlord: Received sdp request from a worker
2019/09/10 10:31:04 Overlord: Sending back sdp to browser
Connected
```

**Comment by sadlil** [comment]
Can you provide some more details about the system you are trying to run. Like

OS
Arch
how are you running the programs etc.

**Comment by namkazt** [comment]
OS: Windows 10 with Ubuntu
Run by `make run` as in Readme.md

![2019-09-10 17_41_28-Window](https://user-images.githubusercontent.com/6035916/64607238-4da95480-d3f2-11e9-9faa-4ab96d9bad31.png)

**Comment by sadlil** [comment]
@namkazt You mean ubuntu inside a VM with Windows Host? Can you provide a screenshot what do you see in the browser? From the log, it looks like worker have been connected to overlord server.

**Comment by namkazt** [comment]
web display ok but display game not ready when select or try to start game.
`019/09/10 10:31:04 Error: Cannot create new webrtc session mDNS: failed to join multicast group` is the only error i see

**Comment by namkazt** [comment]
@sadlil windows 10 have WSL that is windows linux subsystems :
https://docs.microsoft.com/en-us/windows/wsl/install-win10





*
              Best Regards.Mr. Nam NguyễnPhone No. : 012.9595.8685*

*Skype Account : nam.kazt*

**Comment by giongto35** [comment]
Hi namkazt,
Nice to meet you.
Seems like another OS issue. Did you manage to run that?

**Comment by namkazt** [comment]
Still not playable :( I will take some time to dig deeper on this problem.

**Comment by giongto35** [comment]
Hi @namkazt , thanks for your interest in the repo.
This is the first time I see that problem. Can you update your chrome browser to latest version? By the way, we can talk over skype so I can understand your problem better and fix the repo. ( I try to find your account nam.kazt on skype but not found) 
As for ws improvement, actually ws is not the critical part of this project. Streaming relies on WebRTC, so optimize ws may not help much :D.

**Comment by sergystepanov** [comment]
Hi guys! A couple days ago I stumbled upon this interesting project of yours but I have no luck with making it run locally on Windows 10. Having the same problem as namkazt on WSL/Ubuntu. There is something to do with VM-to-Windows address expose (ws candidates?), I suppose. Here is a part of the logfile from the browser on WSL: 

> libopus.js?1:1 pre-main prep time: 0 ms
utils.js?1:5 WebSocket is opened. Send ping
utils.js?1:5 Send ping pong frequently
utils.js?1:5 Send latency list [object Object]
ws.js?6:120 {127.0.0.1: 22}
utils.js?1:5 received stunturn from worker [{"urls":"stun:stun.l.google.com:19302"},{"urls":"stun:127.0.0.1:3478"},{"urls":"turn:127.0.0.1:3478","username":"root","credential":"root"}]
utils.js?1:5 Received game list
utils.js?1:5 Load game menu
utils.js?1:5 v=0
...
utils.js?1:5 > [Pick] game 1/2 - Contra
ws.js?6:216 {"candidate":"candidate:1910078557 1 udp 2113937151 91f81f5a-1738-418d-b26c-3dd9d31be42b.local 57961 typ host generation 0 ufrag ULEr network-cost 999","sdpMid":"0","sdpMLineIndex":0}
ws.js?6:216 {"candidate":"candidate:1910078557 1 udp 2113937151 91f81f5a-1738-418d-b26c-3dd9d31be42b.local 57963 typ host generation 0 ufrag ULEr network-cost 999","sdpMid":"1","sdpMLineIndex":1}
ws.js?6:216 {"candidate":"candidate:1910078557 1 udp 2113937151 91f81f5a-1738-418d-b26c-3dd9d31be42b.local 57965 typ host generation 0 ufrag ULEr network-cost 999","sdpMid":"2","sdpMLineIndex":2}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57965 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag ULEr network-cost 999","sdpMid":"2","sdpMLineIndex":2}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57963 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag ULEr network-cost 999","sdpMid":"1","sdpMLineIndex":1}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57961 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag ULEr network-cost 999","sdpMid":"0","sdpMLineIndex":0}
utils.js?1:5 Ice gathering timeout, send anyway
utils.js?1:5 > [Pick] game 2/2 - Super Mario Bros

Inside a normal VirtualBox Ubuntu image the service is working and the log looks like this:

> ...
utils.js?1:5 Loading menu screen
utils.js?1:5 > [Pick] game 1/2 - Contra
ws.js?6:216 {"candidate":"candidate:547260449 1 udp 2113937151 10.0.2.15 35458 typ host generation 0 ufrag snrn network-cost 999","sdpMid":"0","sdpMLineIndex":0}
ws.js?6:216 {"candidate":"candidate:547260449 1 udp 2113937151 10.0.2.15 42765 typ host generation 0 ufrag snrn network-cost 999","sdpMid":"1","sdpMLineIndex":1}
ws.js?6:216 {"candidate":"candidate:547260449 1 udp 2113937151 10.0.2.15 32934 typ host generation 0 ufrag snrn network-cost 999","sdpMid":"2","sdpMLineIndex":2}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57468 typ srflx raddr 10.0.2.15 rport 35458 generation 0 ufrag snrn network-cost 999","sdpMid":"0","sdpMLineIndex":0}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57470 typ srflx raddr 10.0.2.15 rport 32934 generation 0 ufrag snrn network-cost 999","sdpMid":"2","sdpMLineIndex":2}
ws.js?6:216 {"candidate":"candidate:842163049 1 udp 1677729535 95.30.110.149 57469 typ srflx raddr 10.0.2.15 rport 42765 generation 0 ufrag snrn network-cost 999","sdpMid":"1","sdpMLineIndex":1}
utils.js?1:5 Ice gathering timeout, send anyway
utils.js?1:5 Got remote sdp
utils.js?1:5 iceConnectionState: checking
utils.js?1:5 iceConnectionState: connected
utils.js?1:5 inputChannel has opened

And the Docker image doesn't work as well in the same way as WSL. :(

**Comment by giongto35** [comment]
Hi @sergystepanov  
So sorry for the experience. Thank you for reporting that, I will try to dive into it.
Are you able to run the project now? I saw you said you can run in other ticker. 
So can you clarify what environment it will have troubles on and what environment you can make it work: 
not worked:
- Window 
- Ubuntu on Window (WSL)
worked: 
- Virtualbox Ubuntu.

**Comment by sergystepanov** [comment]
> Are you able to run the project now? I saw you said you can run in other ticker.
So as I understand you cannot make it worked on Window and Ubuntu on Window (WSL)
and it worked on Virtualbox Ubuntu?

Yes. It runs perfectly fine either inside a virtual machine or normal Linux but on the current WSL (haven't tried WSL2 yet) it doesn't work. It hangs somewhere at the ICE candidate picking stage from SDP (addresses not available on the host or provided ones are garbage?). No idea how to test WebRTC stuff.
Also, as I mentioned earlier, when I run the app in Docker, it has the same outcome.
Settings are similar to the Make script in the repo:
```
docker run --privileged -v $PWD/games:/cloud-game/games \ 
-d --name cloud-game-local -p 8000:8000 -p 9000:9000 \
cloud-game-local bash -c "overlord --v=5 & \ 
overworker --overlordhost ws://localhost:8000/wso"
```
How do you run it with Docker and does it work for you?

**Comment by giongto35** [comment]
@sergystepanov You mean you failed to run docker script on Window env right?
Is it ok if you run Docker within Virtual Machine + Normal Linux?

**Comment by sergystepanov** [comment]
> You mean you failed to run docker script on Window env right?

@giongto35, yes, the app is running but when you click play on the page -- games won't run. I think it's a similar problem to this issue.

> Is it ok if you run Docker within Virtual Machine + Normal Linux?

I'll try and tell.

**Comment by sergystepanov** [comment]
That's interesting, actually it works on Ubuntu through Docker. So, it seems there is a problem with Windows, then. (also, tried with audio, quite impressive (: ) 

![Screenshot from 2019-10-01 21-22-17](https://user-images.githubusercontent.com/846874/65989262-0151b180-e492-11e9-9093-e534271c2767.png)

**Comment by giongto35** [comment]
@sergystepanov  :D Thank you very much for testing all environments. I really appreciate it.
It surprised me when the project cannot start on Window even with Docker. The log seems fine. I think I need to install Window on my desktop to debug it more.

> tried with audio, quite impressive (: 
:( The audio used to work well though. Audio turns out harder than Video processing because it's a continuous wave.

**Comment by sergystepanov** [comment]
@giongto35, thanks for your concern, I was able to compile and run everything in Windows without Docker, so this issue doesn't matter now (at least for me (:) 

(Now I wonder why snes has 2sec and psx has a 4sec input latency)

![image](https://user-images.githubusercontent.com/846874/66043612-46c0be00-e528-11e9-9f71-7fad1e2be27e.png)

**Comment by giongto35** [comment]
@sergystepano
Wow, Awesome. How did you manage to run in on window :O.
If are close to the servers, the latency should < 1s. I think if you run on local, you can feel it seamless right :/ 
And for the discrepancy between PSX and SNES latency, PSX has heavier computation, so it makes things slower.

**Comment by sergystepanov** [comment]
> Wow, Awesome. How did you manage to run in on window. Can you show it so others can run when facing the same issue.

It's kinda easy. The hardest part is to find proper C libs and link it right to avoid segfaults. I'll PR a quick guide in the readme.

> Regarding to latency, If you are close to the servers, the latency should < 1s. I think if you run on local, you can feel it seamless with 0ms right :/
> And for the discrepancy between PSX and SNES latency, PSX has heavier computation, so it may makes things slower.

Not really seamless. For that, I just did a quick comparison with go-nanoarch (opengl) and there is no latency whatsoever for NES, SNES, PSX cores. Regarding cloud-game, there is no latency only when I run NES core and 2-3 sec overhead othervice. Maybe there is an additional slowdown in the rendering / encoding compared to nanoarch. Anyway, maybe I'll re-check it later on a desktop pc and open a different issue. (:

**Comment by giongto35** [comment]
Thanks @sergystepanov very much, It will be a great help if you can submit a PR solving window issue.
Regarding to the performance, I think it's CPU problem. cloud-game has encoding video + audio pipeline, which is even heavier than the game itself (Or I haven't optimized enough).  Maybe you are running VirtualBox and it also consumes some resource. 
You can try with fully free and see the result.
