### ISSUE TITLE
Clean up Commit History

### ISSUE THREAD

**Issue by sadlil** [giongto35/cloud-game#85]
It seems like the commit history contains some test commits that are not relevant. Like the commits here - https://github.com/giongto35/cloud-game/commits?author=torvalds.

It's not a good practice having commits like this, that uses some other usernames.
Please clean up commit history-related this. Thanks.

**Comment by sadlil** [comment]
I think for this you just need to rewrite the commits. May be squash a few and then force push to github. You also need to enable force push in master branch from settings.

**Comment by giongto35** [comment]
done with this.
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit
