### ISSUE TITLE
Reduce usages of CGo

### ISSUE THREAD

**Issue by sadlil** [giongto35/cloud-game#86]
There are a lot of c codes hardly coupled with the go codes. https://dave.cheney.net/2016/01/18/cgo-is-not-go. It is better to use to go as much as possible. I think there are some scopes to reduce some cgo codes. Let me know what is your thought about reducing the uses of cgo.

**Comment by giongto35** [comment]
Yes, that CGO is due to the library I'm relying on (Libretro) written in C. The only Golang port I found is using CGO :( Don't know how to get away with that.

**Comment by sadlil** [comment]
There are some other cgo code i found while refactoring. Like one in the util. We can start replacing those first. And may be in future we can try to rewrite the libraries.

**Comment by sadlil** [comment]
I will close this issue for now. If we feel we need to make changes related to this - we will reopen in this.
