### ISSUE TITLE
Please remove the ROMs to prevent this from being taken down

### ISSUE THREAD

**Issue by s1h4d0w** [giongto35/cloud-game#87]
Including ROMs on the github will get Nintendo or other developers on your asses in no time. Please remove them so this won't be taken down within a week.

**Comment by Hammersamatom** [comment]
This is not a joke. Nintendo will hand you a Cease and Desist letter. Remove the ROMs before you need to lawyer up.

**Comment by juraisa** [comment]
Roms are still available in your git history

**Comment by SpiffyJUNIOR** [comment]
Are the roms still available?

**Comment by s1h4d0w** [comment]
> 
> 
> Are the roms still available?

Don't ask for ROMs. These are property of Nintendo and all the other publishers/developers, hosting any of them here or providing links to them will get all this taken down. Don't be stupid.

**Comment by giongto35** [comment]
Guys. Thanks for your feedback. I removed all ROMs in git-history. I left Mario and Contra here so it can help new-comers run the project easier.
And please be polite on the discussion.

**Comment by deltabeard** [comment]
> I left Mario and Contra here

This is unacceptable. Contra and Mario are the property of Konami and Nintendo respectively.
As other have mentioned here, you have to only include software that you have permission to use. Otherwise these companies are fully within their right to take this project down, which is what we're trying to prevent.

**Comment by s1h4d0w** [comment]
Please see this list of public domain and homebrew roms: https://howchoo.com/g/otiwyjhlnzb/where-to-find-roms-for-retropie#list-of-public-domain-roms

You don’t need Mario or Contra to give people something to test with.
