### ISSUE TITLE
hello Giongto

### ISSUE THREAD

**Issue by michaelantonio** [giongto35/cloud-game#88]
hello giongto, it makes me happy to see and see that your project and the ideas I had and you told me a few months ago, come true ... ok now seeing the structure ... some questions arise.
regardless of the server where you are staying .. example a powerful one can I run demanding games say (ps2, xbox, xbox 360, game cube,? and another question can I add a frontend "launchbox" to the environment?

**Comment by SpiffyJUNIOR** [comment]
Lmao no. That requires power nobody is gonna give away for free.

**Comment by giongto35** [comment]
Hi @michaelantonio ,

Long time no see. 
After integrating with LibRetro, the platform has the ability to launch any kind of games LibRetro can support. PS2 and GameCube seem to be supported by LibRetro also, so there won't be much problem running those games.
However, running more demanding games requires better infrastructure, which I cannot afford. The purpose of this project is to demonstrate the methodology of cloud games, I'm happy with the current setting with some PS1 games.
