### ISSUE TITLE
can not see rom list.

### ISSUE THREAD

**Issue by shou1156226** [giongto35/cloud-game#93]
i had launch server and saw the website, but i can not see rom list. why?

**Comment by giongto35** [comment]
Thank you for giving a try.
Are you talking about launching server or local right? Do you run it on ubuntu or window? Can you copy the log from browser?

**Comment by shou1156226** [comment]
> 
> 
> Thank you for giving a try.
> Are you talking about launching server or local right? Do you run it on ubuntu or window? Can you copy the log from browser?
i'm on a local host on ubuntu.

it just output 
handlers.go:115] Browser connected to overlord
handlers.go:287] Send sync [127.0.0.1] 127.0.0.1
 no any other info

**Comment by sergystepanov** [comment]
@shou1156226, you can open Chrome console by pressing F12, then right click on any record in there and select "Save as...", or just expand the browser window to fit all text and print-screen it.

![image](https://user-images.githubusercontent.com/846874/66119426-505a2c80-e5e1-11e9-8970-b109ef9cb609.png)
