### ISSUE TITLE
it crash when use libretro

### ISSUE THREAD

**Issue by shou1156226** [giongto35/cloud-game#95]
when i used libretro about ps2 core, it crashed. i even doubt it is a core problem, but i tried the same core in retroarch, i workd without crash. the crash program is overworker, it may crash from cgo think.
golang output is at pkg/emulator/libretro/nanoarch/nanoarch.go:367. it says receive a unreconginze signal.

c++ output is the following sentence:
#0  0x00007fffe25bca87 in CGSHandler::WriteRegisterMassively(std::vector<std::pair<unsigned char, unsigned long long>, std::allocator<std::pair<unsigned char, unsigned long long> > >, CGsPacketMetadata const*) () from assets/emulator/libretro/cores/play_libretro.so
#1  0x00007fffe2588b4a in CGIF::ProcessSinglePacket(unsigned char const*, unsigned int, unsigned int, CGsPacketMetadata const&) ()
   from assets/emulator/libretro/cores/play_libretro.so
#2  0x00007fffe2588ed8 in CGIF::ProcessMultiplePackets(unsigned char const*, unsigned int, unsigned int, CGsPacketMetadata const&) ()
   from assets/emulator/libretro/cores/play_libretro.so
#3  0x00007fffe2588f49 in CGIF::ReceiveDMA(unsigned int, unsigned int, unsigned int, bool) ()
   from assets/emulator/libretro/cores/play_libretro.so
#4  0x00007fffe2606d10 in Dmac::CChannel::ExecuteNormal() () from assets/emulator/libretro/cores/play_libretro.so
#5  0x00007fffe2603422 in CDMAC::SetRegister(unsigned int, unsigned int) () from assets/emulator/libretro/cores/play_libretro.so
#6  0x00007fffe257f5d0 in Ee::CSubSystem::IOPortWriteHandler(unsigned int, unsigned int) ()
   from assets/emulator/libretro/cores/play_libretro.so
#7  0x00007fffe25e12d5 in CMemoryMap_LSBF::SetWord(unsigned int, unsigned int) () from assets/emulator/libretro/cores/play_libretro.so

**Comment by giongto35** [comment]
Yes, it is due to PS2 is not supported, Only PS, SNES, GBA. The platform relied on LibRetro, and libretro needs core to run game. Currently, there isn't cores for PS2, so we cannot set up it.
Can refer to https://docs.libretro.com/
