### ISSUE TITLE
Pokemon Gold Emulates with a odd screen

### ISSUE THREAD

**Issue by rswsaw22** [giongto35/cloud-game#97]
When trying to load Pokemon Gold ROM its graphics load oddly in a broken manner. Not sure if this is a ROM or emulator issue or something else, but worth looking into to make sure it can handle different ROMs.

**Comment by rswsaw22** [comment]
Here is what I see on my screen when running from Chrome.
![image](https://user-images.githubusercontent.com/11634937/66273275-af14e580-e82f-11e9-897f-611a6aa3fb5f.png)

**Comment by sergystepanov** [comment]
I've seen similar "pattern" on some PSX cores. I think something is not right with one of the core pixel-format to image converters.

**Comment by giongto35** [comment]
oh you fixed it :@) https://github.com/giongto35/cloud-game/pull/100/files
