### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#98]
I was trying to make audio streaming work (again) and it is kinda working now. It's synced with the video but overly compressed for some reason (see example on the video down below).

So, here what I fixed so far:

- it seems that non-blocking select-default goroutine in the emulator audio samples pusher drops a fair amount of samples [here](https://github.com/giongto35/cloud-game/blob/master/pkg/emulator/libretro/nanoarch/nanoarch.go#L242-L245). Tried it without select and it pushes all samples now. For the testing I wrote a simple function, which writes raw PCM samples into a file and then played it in the Audacity (Import -> Raw).
- I excluded resampler and used nestopia core because it runs in 48kHz audio rate to not to worry about resampling for Opus (which needs to be checked)
- I'm not quite sure why there is int16 to float32 sample conversion, Opus encoder by default operates with int16. When I tried to play saved float32 samples they were overly clipped or loud distorted, maybe I just saved it wrong, but I switched GO channel into int16 and it works fine.
- next I checked that Opus encoded frames before push into WebRTC are legit and they are, checked by decoding, saving to pcm, and playing.
- the last bit in the [webrtc.go](https://github.com/giongto35/cloud-game/blob/master/pkg/webrtc/webrtc.go#L294) where RTP audio packets are made. It seems the length of the payload should be equal (see the [doc](https://tools.ietf.org/html/rfc7587)) to the length of the encoded audio frame (for 2.5ms/48kHz it's 120 and so on) and not to the length of raw Opus encoded bytes as it is right now.

After these fixes I was able to run the app with sound, but it's distorted. I think there is something with RTP opus packets or something on the client-side. No idea what to do next.
Maybe you have some (:?

[Raw video with example](https://www.dropbox.com/s/sqdeks9q9az2rsg/2019-10-07%2014-56-17.mkv?dl=0) (it's loud)

**Comment by sergystepanov** [comment]
omg, it's working, just forgot to delete double encode to opus in the code, jeez
Right, I'll make a PR with audio fix.

Here is how it [works](https://www.dropbox.com/s/9jf1bcg89qq4dzv/2019-10-07%2019-54-48.mkv?dl=0).

**Comment by giongto35** [comment]
OMG. You made my day!!!
I was so desperate to make audio work. Thank you for the all the fix and explaination! All of them are very legit. 
1) yes I didn’t realize select default can drop the frame. Really Good finding!
2) So you are currently limited scope to make it works with NES right? Can just go first with it, the resampling for other cores will not be big issue
3) it should be int16, I think we made wrong assumption about the data type.
4) :D
5) Another awesome finding! 

Thank you again, I learned a lot from you. :D

**Comment by sergystepanov** [comment]
Glad that I could help with something (:
Just checked it on [a gaming PC](https://www.dropbox.com/s/rk1zu999t5ga332/2019-10-08%2013-01-24.mkv?dl=0) (forgot to check OBS before recording) and, yep, all lags are gone, even PSX has no latency for me at all (on the localhost ofc).
And it seems that your resampler works just fine. Ok, I will make a PR later this week sometime.

**Comment by giongto35** [comment]
It's a great help indeed.
I didn't know it's that good playing with sound. I will re-deploy ASAP with your change when your PR is merged, so you can experience your work over the internet.

**Comment by sergystepanov** [comment]
@giongto35, sure (:, I'll test a bit more and commit tomorrow, then.
Well, if you will to host a server close to me (: for some reason, then your best bet is Frankfurt from EC2, I guess. It's the closest one to Moscow (:./

**Comment by giongto35** [comment]
@sergystepanov 
It's ok. Don't worry. Don't need to be rush. Weekend we have more time.
You are in Moscow :p I will dedicate one server in Frankfurt for you to test. Currently, there is only London server in Europe.

**Comment by giongto35** [comment]
Closed
